- .github/workflows/dotnet-core.yml
Pack workflow wasn't running because we were pointing to a different file.
Changed to the correct file
> Updating pack workflow

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/AWSXRayEventSource.cs
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/AWSXRayIdGenerator.cs
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/AssemblyInfo.cs
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/OpenTelemetry.Contrib.Extensions.AWSXRay.csproj
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/Trace/AWSXRayPropagator.cs
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests.csproj
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/TestAWSXRayIdGenerator.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/Trace/TestAWSXRayPropagator.cs
As suggested by https://github.com/open-telemetry/opentelemetry-specification/issues/1047#issuecomment-703748553, moving AWS X-Ray trace id generator and propagator from main repo to contrib repo.
Id generator PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1268
Propagator PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/1300
> Added AWS X-Ray trace id generator and propagator.

- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/Implementation/DisplayNameHelper.cs
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/Implementation/MassTransitDiagnosticListener.cs
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/Implementation/SemanticConventions.cs
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/Implementation/TagName.cs
- test/OpenTelemetry.Contrib.Instrumentation.MassTransit.Tests/MassTransitInstrumentationTests.cs
Partially resolves #47
Fixed
- Span names do not match the spec (partially)
- Default tag names do not match the spec
- A lot of redundant tags
- Incorrect `span.kind`
- `net.peer.*` tags are not populated correctly
- The instrumentation produces an incorrect `peer.service` tag
> Adjust MassTransit to the semantic conventions

- .github/workflows/codeql-analysis.yml
Follow up to issue https://github.com/open-telemetry/oteps/issues/144
[CodeQL](https://github.com/github/codeql-action) is GitHub's static analysis engine which scans repos for security vulnerabilities. As the project grows and we near GA it might be useful to have a workflow which checks for security vulnerabilities with every PR so we can ensure every incremental change is following best development practices. Also passing basic security checks will also make sure that there aren't any glaring issues for our users.
* This PR adds [CodeQL](https://github.com/github/codeql-action) security checks to the repo
* After every run the workflow uploads the results to GitHub. Details on the run and security alerts will show up in the `security` tab of this repo.
**Workflow Triggers**
* daily …
> Add CodeQL security scan

- src/OpenTelemetry.Contrib.Extensions.AWSXRay/AWSXRayIdGenerator.cs
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/README.md
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests.csproj
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/TestAWSXRayIdGenerator.cs
When using `ActivitySource.StartActivity()` to create root activity, the sampling decision is decided [before](https://github.com/dotnet/runtime/blob/ae9da6432360728c77ab10b1ef0c414d1a9ee287/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/ActivitySource.cs#L207) invoking `ActivityListener`s. If user is using traceid-dependent sampler, root activity's sampling decision needs to be updated as well while replacing trace id. Here, we provide a new API called `AddXRayTraceIdWithSampler` to override the trace id and update sampling decision for this case.
> Update root activity's sampling decision when using ActivitySource.StartActivity()

- build/Common.prod.props
- src/OpenTelemetry.Contrib.Exporter.Stackdriver/OpenTelemetry.Contrib.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/OpenTelemetry.Contrib.Extensions.AWSXRay.csproj
- src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch/OpenTelemetry.Contrib.Instrumentation.ElasticsearchClient.csproj
- src/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore.csproj
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/OpenTelemetry.Contrib.Instrumentation.MassTransit.csproj
MinVer provides a feature to [version multiple projects in a single repo independently](https://github.com/adamralph/minver#can-i-version-multiple-projects-in-a-single-repo-independently) by defining a tag prefix for each project. I believe we can leverage this feature by defining specific tag prefix for each project and then creating a tag with `<projectPrefix>-<version>` when we want to do a release for the project.
For example, if the project name is `OpenTelemetry.Contrib.Extensions.AWSXRay`, the tag prefix will be `Extensions.AWSXRay-` and the tag name will be `Extensions.AWSXRay-1.0.0-rc2`. 
Any new project added to the repo must define the `<MinVerTagPrefix>` in its `csproj` file.
I checked the [naming requirements](https://git-scm.com/docs/git-tag#Documentation/git-tag.txt-lttagnam …
> Individual component versioning through tag prefixes

- README.md
As we are kick starting contrib repo, it'd be okay to waive the typical requirement of being an approver for 1 month, before being maintainer.
> Add Prashant as maintainer

- .github/workflows/package-Exporter.Stackdriver.yml
- .github/workflows/package-Extensions.AWSXRay.yml
- .github/workflows/package-Instrumentation.Elasticsearch.yml
- .github/workflows/package-Instrumentation.EntityFrameworkCore.yml
- .github/workflows/package-Instrumentation.MassTransit.yml
I missed to notice that the tests for the projects have `.Tests` suffixed to them and isn't the exact name as their source projects. So this PR aims to fix the test step in the workflows by explicitly calling the test projects rather than using the `PROJECT` variable.
I could have generalized this too but for some reason the EntityFrameworkCore project doesn't exactly follow the `.Tests` convention rather has the `Tests`  suffix. Maybe we can fix it later for the sake of consistency in the repo.
> Fix project name for test step

- .github/workflows/package-Instrumentation.AWS.yml
Sorry I missed this one before merging in the whole PR. Doing the same fix as done for the rest of the workflows in https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/73
> Fix test project name in AWS instrumentation

- src/OpenTelemetry.Contrib.Instrumentation.AWS/README.md
Setting the trace ID is only for X-Ray users, but this instrumentation is unrelated to X-Ray.
And it's almost never a good idea to set the global propagator to just the xray propagator, at least it should be both w3c and xray. But as the instrumentation is directly using xray propagation (nice), it's not necessary anyways.
> Remove X-Ray specific documentation from README

- src/OpenTelemetry.Contrib.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.AWS/OpenTelemetry.Contrib.Instrumentation.AWS.csproj
When referencing the source code of `Extensions.AWSXRay`, the [MinVer](https://github.com/adamralph/minver#how-it-works) will try to infer the version number for `Extensions.AWSXRay`, and causes stable version of `Instrumentation.AWS` to depend on a pre-release version of `1.0.2-alpha` for `Extensions.AWSXRay`, which is in conflict with what we wanted as `1.0.1`. Changing the project reference to package reference will resolve this.
> Instrumentation.AWS - Changed project dependency to package reference

- CODEOWNERS
Issue: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/67
Adding code owners for the separate components of the contrib repo. Right now, all the code defaults to the @open-telemetry/dotnet-approvers group and I intend to keep it as such until we get specific approvers for each project. 
For the AWS code, I'm adding myself and @lupengamzn to be the code owners. Please feel free to discuss if you feel otherwise.
One thing to note is that any code owner added in this file will also need to have write permissions for the repo to actually let them be the code owners in a true sense.
> Project code owners

- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/Implementation/MassTransitDiagnosticListener.cs
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/OpenTelemetry.Contrib.Instrumentation.MassTransit.csproj
- test/OpenTelemetry.Contrib.Instrumentation.MassTransit.Tests/MassTransitInstrumentationTests.cs
Extends the optimization done in the [PR #1894](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1894) to optimize MassTransit Instrumentation
- Added a check to return from the `OnStartActivity` method of the listener if the instrumentation is suppressed
- Wrap the logic in `OnStartActivity` to perform operations such as filter, set the activity DisplayName, etc. only when `activity.IsAllDataRequested` is set to `true`
- Removed the redundant filtering check in the `OnStopActivity` method of the listener
- Added unit tests to check if the instrumentation respects  `Sdk.SuppressInstrumentation` and `activity.IsAllDataRequested`
> Modify MassTransit Instrumentation to take advantage of sampling decision

- CODEOWNERS
- Added @ejsmith as the code owner for ElasticSearch instrumentation `src` and `test`
> Add code owner for ElasticSearch instrumentation

- src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch/Implementation/ElasticsearchRequestPipelineDiagnosticListener.cs
- src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch/OpenTelemetry.Contrib.Instrumentation.ElasticsearchClient.csproj
- test/OpenTelemetry.Contrib.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs
Extends the optimization done in [PR #1894](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1894) to optimize ElasticSearch Instrumentation
- Added a check to return from the OnStartActivity method of the listener if the instrumentation is suppressed
- Wrap the logic in OnStartActivity to perform operations such as fetch uri, set the activity DisplayName, etc. only when - activity.IsAllDataRequested is set to true
- Added unit tests to check if the instrumentation respects `Sdk.SuppressInstrumentation` and `activity.IsAllDataRequested`
> Modify ElasticSearch Instrumentation to take advantage of sampling decision

- .github/workflows/package-Exporter.Stackdriver.yml
- .github/workflows/package-Extensions.AWSXRay.yml
- .github/workflows/package-Instrumentation.AWS.yml
- .github/workflows/package-Instrumentation.AWSLambda.yml
- .github/workflows/package-Instrumentation.Elasticsearch.yml
- .github/workflows/package-Instrumentation.EntityFrameworkCore.yml
- .github/workflows/package-Instrumentation.GrpcCore.yml
- .github/workflows/package-Instrumentation.MassTransit.yml
- .github/workflows/package-Instrumentation.Wcf.yml
The workflows are currently manually triggered by maintainers (either from Action UI, or by pushing matching tags), and they publish packages to myget. This PR is updating the workflows to push to nuget, instead of myget. This removes one manual step maintainers have to do to release a component.
The secrets are not accessible to PRs from forks - this was the only thing which we wanted to validate, before making this change (as discussed in the 5/4 and 5/11 SIG meetings)
Myget was used previously by daily jobs which pushed daily builds to myget. We can bring it back, if there is a need. We haven't been doing nightly myget release for a long time from this repo now.
> Publish workflows to push to Nuget directly

- src/OpenTelemetry.Contrib.Shared/DiagnosticSourceInstrumentation/DiagnosticSourceListener.cs
- src/OpenTelemetry.Contrib.Shared/OpenTelemetry.Contrib.Shared.csproj
Avoids taking SDK dependency.
These checks are redundant since 1.1, as the SDK does this check (Supress) and all Activity start/stop goes through SDK only now.
> Cleanup diagnosticsource listeners

- .github/workflows/pr_build.yml
- test/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCoreTests/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore.Tests.csproj
WCF Tests was already having net5.0 target, but it was not running in the CI job. This enabled it for all projects which has net5.,0 test target
> Add net5.0 to CI build

- .github/workflows/package-Preview.yml
The net5.0 conditional target in OpenTelemetry.Contrib.Preview (added to get nullable analysis in VS/IDE working) causes the build to break: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/runs/2759435669?check_suite_focus=true
Since release builds are rare I figured just re-running a build during the pack step wouldn't be a big deal.
> Preview: Fix conditional net5.0 target breaking build

- .github/workflows/package-Preview.yml
- build/Common.props
Attempting to fix a couple of issues observed with the 1.0.0-beta1 push of OpenTelemetry.Contrib.Preview:
* Microsoft.CodeCoverage is showing up as a package dependency
* Symbols push failed
> Preview: Build fixes

- src/OpenTelemetry.Contrib.Instrumentation.GrpcCore/ClientStreamWriterProxy.cs
- src/OpenTelemetry.Contrib.Instrumentation.GrpcCore/ClientTracingInterceptor.cs
- test/OpenTelemetry.Contrib.Instrumentation.GrpcCore.Tests/GrpcCoreClientInterceptorTests.cs
Any exceptions during a write to a clientstreaming or duplexstreaming RPC were not tracked. They bubbled up to the caller and we were losing the opportunity to set the correct status code and description on the Span. Before this change, the newly added tests would fail with a status code of (1) canceled. That was getting set during Dispose instead of proactively at the time of the failure.
Behavior for non-streaming write failures was correct.
> [gRPC Core client interceptor] Wrong status code if write to clientstreaming or duplexstreaming RPC fails

- CONTRIBUTING.md
- README.md
Replacing Gitter links with Slack channel links
> Replace Gitter with Slack channel link

- src/OpenTelemetry.Contrib.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Contrib.Exporter.Stackdriver/Implementation/ExporterStackdriverEventSource.cs
- src/OpenTelemetry.Contrib.Exporter.Stackdriver/OpenTelemetry.Contrib.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Contrib.Exporter.Stackdriver/StackdriverTraceExporter.cs
- When stackdriver fails to communicate/export spans to stackdriver
service log errors.
- Upgrade Otel SDK to 1.1.0-beta4
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/139
> Add exception logging to stackdriver

- src/OpenTelemetry.Contrib.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.GrpcCore/ClientTracingInterceptor.cs
- test/OpenTelemetry.Contrib.Instrumentation.GrpcCore.Tests/FoobarService.cs
- test/OpenTelemetry.Contrib.Instrumentation.GrpcCore.Tests/GrpcCoreClientInterceptorTests.cs
- test/OpenTelemetry.Contrib.Instrumentation.GrpcCore.Tests/GrpcCoreServerInterceptorTests.cs
Retry interceptors that sit above the client interceptor would expect the original set of call headers, not mutated ones.
> [gRPC Core client interceptor] Don't mutate incoming call headers

- examples/wcf/client-netframework/App.config
- examples/wcf/server-netframework/App.config
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/README.md
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/TelemetryEndpointBehavior.cs
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/TelemetryEndpointBehaviorExtensionElement.cs
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/TelemetryServiceBehavior.cs
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/TelemetryServiceBehaviorExtensionElement.cs
Adds IServiceOperationBehavior implementation to enable based configuration of WCF services at the service level.
Refer [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.description.iservicebehavior?view=netframework-4.8)
> Add WCF ServiceBehavior implementation. Resolves #142.

- src/OpenTelemetry.Contrib.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/TelemetryClientMessageInspector.cs
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/TelemetryDispatchMessageInspector.cs
- test/OpenTelemetry.Contrib.Instrumentation.Wcf.Tests/TelemetryClientMessageInspectorTests.cs
- test/OpenTelemetry.Contrib.Instrumentation.Wcf.Tests/TelemetryDispatchMessageInspectorTests.netfx.cs
- test/OpenTelemetry.Contrib.Instrumentation.Wcf.Tests/WCF/IServiceContract.cs
- test/OpenTelemetry.Contrib.Instrumentation.Wcf.Tests/WCF/Service.netfx.cs
- test/OpenTelemetry.Contrib.Instrumentation.Wcf.Tests/WCF/ServiceClient.cs
` public string DisplayName
{
get
{
return _displayName ?? OperationName;
}
set
{
_displayName = (value ?? throw new ArgumentNullException("value"));
}`
Display name throws Argument null exception if action is null or operation contract name is defined in the WCF operationContract .
> WCF: action is assigned with null if operation name is not defined(#169)

- src/OpenTelemetry.Contrib.Extensions.AWSXRay/Resources/AWSEKSResourceDetector.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/Resources/TestAWSEKSResourceDetector.cs
#201 AWSEKSResourceDetector - Validate ClusterName/ContainerID independently before adding it to the resource
- Validates ClusterName/ContainerID independently before adding it to the resource
- Includes bug fix - IsEKSProcess should return non-null auth value to confirm if its running in EKS environment.
- Handled exceptions separately with more error information
- Added Unit Tests
>  #201 AWSEKSResourceDetector  - Validate ClusterName/ContainerID independently before adding it to the resource

- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetrics.cs
- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetricsOptions.cs
- test/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests.csproj
- test/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Remove metric name prefix as a public property
Remove unwanted dependencies from test
Add net5.0 target for tests
Modify the basic test structure to correctly use InMemoryExporter
> Minor improvements to Runtime metrics

- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Split the "process.cpu.time" metric into multiple values with a state tag as mentioned in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md#process
> Provide cpu time with state tags

- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetrics.cs
- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetricsOptions.cs
- test/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests/RuntimeMetricsOptionsTests.cs
- test/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
According to  https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md#process moving the "memory.usage" to the process metrics.
Change metric to expose value in bytes instead of MB.
Add "process.memory.virtual" also
> Move memory metric to process metrics

- src/OpenTelemetry.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcCore/OpenTelemetry.Instrumentation.GrpcCore.csproj
The full Grpc.Core package reference is not necessary.
Grpc.Core.Api is the only package shareable between the managed wrapper around Grpc.Core and grpc-dotnet.
> Reduce package dependency by swapping out Grpc.Core for Grpc.Core.Api.

- src/OpenTelemetry.Instrumentation.GrpcCore/CHANGELOG.md
> Release OpenTelemetry.Instrumentation.Grpc as 1.0.0-beta.5

- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
1. Fixes an issue which dropped the LogRecord.State, when it is a KVP of size1
2. Refactored  LogExporter code a bit:
LogExporter obtains the IReadOnlyList<KeyValuePair<string, object>> by either casting the State, or from the StateValues.
Serializes each KVP to form Part C fields.
Body is only populated if IncludeFormatMessage is true *OR*  special casing {OriginalFormat} from Log extension methods.
As a result:
The below log statement, will result in empty body, as there is no formatter provided by the user, and Exporter will not attempt "ToString() on the state" to populate body.
`logger.Log(LogLevel.Information, default, state: "somestringasdata", exception: null, formatter: null);`
The below log statement will also result in empty body, if `IncludeFormattedMessage = false`, else uses …
> GenevaExporter - LogSerialization Fixes

- .github/workflows/package-Exporter.Geneva.yml
Set filter for dotnet test. Otherwise, linux only tests will be ran and will fail.
> Geneva package workflow only run tests on windows

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/GenevaMetricExporterExtensions.cs
Ask for maintainers @open-telemetry/dotnet-maintainers 
- Release version 1.2.6 of the Geneva Exporter
- Unlist version 1.2.5 of the Geneva Exporter from NuGet
> Geneva Exporter - Set metric exporter temporality to delta

- .github/ISSUE_TEMPLATE/comp_exporter_geneva.md
- .github/ISSUE_TEMPLATE/miscellaneous.md
- .github/PULL_REQUEST_TEMPLATE.md
Created the issue templates and PR template.
Regarding issue template, I try to follow the specification repo so we have targeted issue for each project. In this PR I only included one example - once it's merged we can add similar templates for other projects (and also update the contributing.md doc to remind contributors when they add a new project).
These are the tags I would propose:
```text
comp:contrib.extensions.awsxray
comp:contrib.instrumentation.aws
comp:contrib.instrumentation.awslambda
comp:contrib.shared
comp:exporter.geneva
comp:exporter.stackdriver
comp:extensions
comp:extensions.azuremonitor
comp:extensions.persistentstorage
comp:instrumentation.elasticsearchclient
comp:instrumentation.entityframeworkcore
comp:instrumentation.grpccore
comp:instrumentation.hangfire …
```
> Add issue/pr templates

- src/OpenTelemetry.Internal/Guard.cs
Fixes this warning
Related https://github.com/open-telemetry/opentelemetry-dotnet/pull/3236
Made the parameters will null as default values nullable fields.
Added `#nullable enable` to the file so that I could use nullable fields.
> Fix nullable warnings in guard class

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/OpenTelemetry.Instrumentation.EntityFrameworkCore.csproj
- src/OpenTelemetry.Instrumentation.MassTransit/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MassTransit/OpenTelemetry.Instrumentation.MassTransit.csproj
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.MassTransit.Tests/OpenTelemetry.Instrumentation.MassTransit.Tests.csproj
- test/OpenTelemetry.Instrumentation.Wcf.Tests/OpenTelemetry.Instrumentation.Wcf.Tests.csproj
Upgrade MassTransit, WCF, and EntityFramework Core to OTel 1.2.0
MassTransit.Test build against Net5.0, Net6.0
EntityFrameworkCore.Test add Net6.0 and split EFCore dep based on the target version
> Target OTel 1.2.0 for MassTransit, WCF, and EntityFrameworkCore

- src/OpenTelemetry.Exporter.Geneva/README.md
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/341#issuecomment-1121673453
- Capitalize Logs, Traces, Metrics
- Omit note about using OTel 1.2.* since it is already the stable version
> exporter/geneva - Minor readme file tweaks

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
Related to https://github.com/open-telemetry/opentelemetry-dotnet/issues/2569
- Add support for the native Activity properties `Status` and `StatusDescription` for GenevaExporter. All the other exporters in the public repo have added support for the native Activity properties `Status` and `StatusDescription`.
There is no measurable impact on the perf numbers.
// * Summary *
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
Intel Core i7-9700 CPU 3.00GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.300
[Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
DefaultJob : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
|                    Method |      Mean | …
> Add support for the native Activity properties Status and StatusDescription

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
- test/OpenTelemetry.Exporter.Stackdriver.Tests/OpenTelemetry.Contrib.Exporter.Stackdriver.Tests.csproj
* Updated OTel SDK package version to 1.2.0
* Update minimum full framework support to net462
* Update Google.Cloud.Monitoring.V3 2.1.0 -> 2.6.0
* Update Google.Cloud.Monitoring.V3 2.0.0 -> 2.3.0
* Add runtime net5.0, net6.0 to test csproj
> Upgrade Stackdriver support to OTel 1.2.0

- src/OpenTelemetry.Contrib.Shared/Api/SpanHelper.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
> Don't mark Elasticsearch 404's as error

- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Exporter.Instana/Implementation/SpanSender.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Transport.cs
If environment variables are not defined but Instana exporter is added that can cause the application to crash. 
We have to check if env vars are defined before we try to start reporting to Instana backend.
> [Exporter.Instana] Check if env vars are defined

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
A potential approach to fix #389
- Add support for exporting ILogger scopes
This PR demonstrates one possible way of exporting scopes. We would release a beta package with this feature to gather feedback.
```
using (logger.BeginScope("MyScope"))
{
logger.LogInformation("Hello from {food} {price}.", "artichoke", 3.99);
}
```
Output:
Same table as before, with an additional column "Scopes", which will be a list of 1 element. That element is a Map with 1 key value pair. with "scope", ""MyScope" as values.
```
using (logger.BeginScope("MyOuterScope"))
using (logger.BeginScope("MyInnerScope"))
{
logger.LogInformation("Hello from {food} {price}.", "artichoke", 3.99);
}
```
Output:
Same table as before, with an additional column "Scopes", which will be a list of 2 elements. Each element is a Map …
> [Exporter.Geneva] Add support for ILogger scopes

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- Update CHANGELOG for RedisInstrumentation for `1.0.0-rc9.4` release
> [Instrumenation.StackExchangeRedis] Update CHANGELOG for RedisInstrumentation for 1.0.0-rc9.5 release

- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs
- Remove `Skip` from `ElasticSearchInstrumentation` as those unit tests are fixed now
> Remove skip from ElasticSearchInstrumentation

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- test/OpenTelemetry.Instrumentation.Runtime.Tests/OpenTelemetry.Instrumentation.Runtime.Tests.csproj
Fixes #.
Update OTel SDK package version to 1.3.0
> Update OTel SDK package version to 1.3.0

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- test/OpenTelemetry.Exporter.Geneva.Benchmark/OpenTelemetry.Exporter.Geneva.Benchmark.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNet.Tests/OpenTelemetry.Instrumentation.AspNet.Tests.csproj
- Update OTel package versions
> [Exporter.Geneva] Update OTel SDK version

- src/OpenTelemetry.Exporter.Geneva/ExporterEventSource.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/UnixDomainSocketDataTransport.cs
- Use a dedicated event for each signal when the exporter fails to send the data
- Add an event for other common exporter errors
> [Exporter.Geneva] Update exception logging

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/UnixDomainSocketDataTransport.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/UnixDomainSocketDataTransportTests.cs
Fixes #422 
- Updated `UnixDomainSocketDataTransport.Send` to throw the exception for `Export` methods to catch it and set `ExportResult` correctly
> [Exporter.Geneva] Fix ExportResult on Linux

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetricsOptions.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsOptionsTests.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
For #335.
Remove Process related metrics from .NET Runtime metrics.
These metrics should be added in a separate package and with OpenTelemetry.Instrumentation.Process as a potential name.
> Remove Process related metrics from .NET Runtime metrics

- examples/runtime-instrumentation/Program.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
Currently if you run https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/examples/runtime-instrumentation, the gc heapsize and fragmentation info will be zero instead of the real heap size/fragmentation. This is because there hasn't been any garbage collection so the GC info isn't available yet.
With this change, the code will detect if GC ever happened, and if not, do not report heapsize/fragmentation.
> Do not report 0 if GC info is not available yet

- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
Based on discussion with @noahfalk.
If you call:
```csharp
GC.Collect(0);
GC.Collect(1);
GC.Collect(2);
```
The current implementation would give:
```
process_runtime_dotnet_gc_collections_count{gen="gen2"} 1
process_runtime_dotnet_gc_collections_count{gen="gen1"} 2
process_runtime_dotnet_gc_collections_count{gen="gen0"} 3
```
This PR would change it to:
```
process_runtime_dotnet_gc_collections_count{gen="gen2"} 1
process_runtime_dotnet_gc_collections_count{gen="gen1"} 1
process_runtime_dotnet_gc_collections_count{gen="gen0"} 1
```
> Adjust the semantic of gc count to make it exclusive

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
Release a new alpha version 1.0.0-beta.1 for https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/335.
Changes
Update CHANGELOG.md
> Release Runtime instrumentation version 1.0.0-beta.1

- src/OpenTelemetry.Instrumentation.Runtime/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeInstrumentOptions.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeInstrumentOptionsTests.cs
Rename `RuntimeMetricsOptions` to `RuntimeInstrumentOptions` - it doesn't make sense to have the "metrics" name in the options as the instrumentation library could have other signals (logs, traces).
> refactor runtime instrumentation

- .github/workflows/package-Extensions.PersistentStorage.Abstractions.yml
- .github/workflows/package-Extensions.PersistentStorage.yml
- src/OpenTelemetry.Extensions.PersistentStorage/OpenTelemetry.Extensions.PersistentStorage.csproj
dotnet pack fails with following error
C:\Program Files\dotnet\sdk\6.0.301\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\src\OpenTelemetry.Extensions.PersistentStorage.Abstractions\OpenTelemetry.Extensions.PersistentStorage.Abstractions.csproj]
[10](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/runs/6976309124?check_suite_focus=true#step:5:11)C:\Program Files\dotnet\sdk\6.0.301\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5128: - …
> fix workflow persistenstorage.extensions

- examples/runtime-instrumentation/Program.cs
- src/OpenTelemetry.Instrumentation.Runtime/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
I've made a mistake and force pushed to the main directly, now revert it.
> Revert "clean up runtime instrumentation docs"

- examples/runtime-instrumentation/Program.cs
- src/OpenTelemetry.Instrumentation.Runtime/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Renamed `AddRuntimeMetrics` to `AddRuntimeInstrumentation`.
Cleaned up the docs.
> Clean up runtime instrumentation API/docs

- CONTRIBUTING.md
Addresses the [comment](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/470/files#r909677814).
- Update the contributing doc to mention about adding date to CHANGELOG
> Update the contributing doc to mention about adding date to CHANGELOG

- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
Update instrument type for `monitor.lock_contention.count` and `thread_pool.completed_items.count` to `ObservableCounter`
> [Instrumentation.Runtime] Update instrument type for monotonically increasing metrics

- CONTRIBUTING.md
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- Update CHANGELOG files to use a consistent date format
This follows the format used in the main repo.
> Update CHANGELOG files to use a consistent date format

- src/OpenTelemetry.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcCore/ServerTracingInterceptor.cs
Make the context propagation extraction case insensitive. See link:[#3149](https://github.com/open-telemetry/opentelemetry-dotnet/issues/3149)
Do a case-insensitive comparison in the Grpc.Core instrumentation
> Fix issue -propagation type is not case insensitive

- examples/redis/Examples.StackExchangeRedis/README.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs
Towards #484 
- Use the assembly name as the ActivitySource name
> [Instrumentation.StackExchangeRedis] Update ActivitySource name

- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/Food.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/LogExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/OpenTelemetry.Exporter.Geneva.Benchmark.csproj
Refactoring LogBenchmarks. 
Removed a lot stuff already covered by the core SDK itself : https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/test/Benchmarks/Logs/LogBenchmarks.cs
> Exporter-Geneva - Refactor benchmarks for logging

- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/LogExporterBenchmarks.cs
> Exporter-Geneva add formatted message to benchmarks

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
Update CHANGELOG for 1.0.0-beta.2 release
> [Instrumentation.Hangfire] Update CHANGELOG for 1.0.0-beta.2 release

- .github/component_owners.yml
Add @srprash as component owner for AWS instrumentation
> Add component owner for AWS instrumentation

- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/OpenTelemetry.Instrumentation.MySqlData.csproj
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/OpenTelemetry.Instrumentation.MySqlData.Tests.csproj
Fixes: N/A
Bump OpenTelemetry to 1.3.0 in MySqlData instrumentation
In AutoInstrumentation we have a plan to reuse this package. It will be good to have it build on top of the 1.3.0.
> Bump OpenTelemetry to 1.3.0 in MySqlData instrumentation

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
Use internal method `GC.GetGenerationSize` for GC Heap Size.
.NET 6.0 has a bug in computing those generation sizes for the `GC.GetGCMemoryInfo()` API and it was fixed in .NET 7.
Note that the heap sizes are not retrieved in one transactional query with `GC.GetGCMemoryInfo()`. It'd be better to change it back to `GC.GetGCMemoryInfo().GenerationInfo[i].SizeAfterBytes` for .NET 7 when appropriate.
> [Instrumentation.Runtime] Change API for GC Heap Size

- build/Common.nonprod.props
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests.csproj
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/OpenTelemetry.Contrib.Instrumentation.AWS.Tests.csproj
- test/OpenTelemetry.Contrib.Instrumentation.AWSLambda.Tests/OpenTelemetry.Contrib.Instrumentation.AWSLambda.Tests.csproj
- test/OpenTelemetry.Exporter.Instana.Tests/OpenTelemetry.Exporter.Instana.Tests.csproj
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/OpenTelemetry.Instrumentation.MySqlData.Tests.csproj
Fixes: N/A
Unify Moq across whole repository.
Use 4.17.2. It is last version supporting .NET Framework 4.5.2 - required by `AWS` and `AWSXRay` projects.
> Unify Moq (4.17.2+)

- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
Fixes: N/A
Remove obsolete comment from tests (reference to net452).
All frameworks are even by the newest version https://www.nuget.org/packages/MessagePack/2.4.35
Upgrade requires changes in the test code.
> [Geneva.Exporter] remove obsolete comment from tests

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
#509 intended to only remove the metrics for .NET 6.
For .NET 7 and later, the metrics should be available.
> [Instrumentation.Runtime] Add `gc.heap.fragmentation.size` back for .NET 7 and later

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs
Fixes N./A.
Related to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/947
Mark `DrainThread` as background.
Foreground threads prevent a process from terminating.
AutoIstrumentation dispose all instrumentation `OnExit` event. This thread prevents process to rise this event. Instrumented application cannot be closed.
> [Instrumentation.StackExchangeRedis] Mark Drain thread as background

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
Fixes N/A.
Follow up to #528 and #485
Request release Instrumentation.StackExchangeRedis v. 1.0.0-rc9.7
* Update the `ActivitySource` name used to the assembly name: `OpenTelemetry.Instrumentation.StackExchangeRedis`.
([#485](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/485))
* Drain thread is marked as background. It allows to close the application
even if the instrumentation is not disposed.
([#528](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/528))
> [Instrumentation.StackExchangeRedis] release 1.0.0-rc9.7

- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
Addressing https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/514#discussion_r929575424 and https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/514#discussion_r929576498.
FYI @xyq175com
> Fix bugs in the GenevaExporter PrepopulatedField handling

- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
- Simplify exporter options for PrepopulatedFields
- Add a test case for supported types to not throw an exception
> [Exporter.Geneva] Simplify exporter options for PrepopulatedFields

- .github/component_owners.yml
Docker extensions was created by Cisco / AppDynamics developer as team work assignment. @swetharavichandrancisco is no longer involved in this work and have not expressed wish to continue support it, so I'd updating owner to myself to continue support of project created by our team.
> Changed owner for OpenTelemetry.Extensions.Docker

- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
- Add test case for multithreading scenarios for `GenevaTraceExporter` and `GenevaLogExporter`
> [Exporter.Geneva] Add test case for multithreading scenarios

- src/OpenTelemetry.Instrumentation.Runtime/AssemblyInfo.cs
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
Enable CodeAnalysis for Runtime Instrumentation library.
Set `EnableAnalysis` to `true` in `OpenTelemetry.Instrumentation.Runtime.csproj`.
> [Instrumentation.Runtime] Enable CodeAnalysis for Runtime Instrumentation library

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeInstrumentationOptionsTests.cs
Rename options: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/553#issuecomment-1201709502
Rename `RuntimeInstrumentOptions` to `RuntimeInstrumentationOptions`
> [Instrumentation.Runtime] Rename `RuntimeInstrumentOptions` to `RuntimeInstrumentationOptions`

- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Fixes #.
Refactor some private code for minor non-blocker comments.
* Improve a unit test about `thread_pool.completed_items.count`: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/510#discussion_r927128513
* Change an internal variable type to `const`: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/555#discussion_r935004840
> [Instrumentation.Runtime] Two internal refactors

- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/netcoreapp3.1/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/netcoreapp3.1/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Release Runtime instrumentation version 1.0.0.
Update `CHANGELOG.md`.
> [Instrumentation.Runtime] Release Runtime instrumentation version 1.0.0

- src/OpenTelemetry.Instrumentation.Runtime/README.md
Fixes #.
* Reword README.md on how to enable runtime instrumentation
* Remove the troubleshooting section
> [Instrumentation.Runtime] Reword README.md

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
Fixes N/A
[Intrumentation.WCF] Bump OTel package to 1.3.0
This library is candidate to be part of AutoInstrumentation. It will be great to have released based on common OTel package version.
> [Intrumentation.WCF] Bump OTel package to 1.3.0

- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/LogExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/TraceExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/README.md
The benchmark methods that were removed in this PR are already covered in the main repo.
- Clean-up GenevaTraceExporter Benchmarks
- Add a README file to the project
> [Exporter.Geneva] Clean-up GenevaTraceExporter Benchmarks

- src/OpenTelemetry.Extensions.Docker/DockerExtensionsEventSource.cs
- src/OpenTelemetry.Extensions.Docker/Resources/DockerResourceDetector.cs
- src/OpenTelemetry.Extensions.Docker/Resources/DockerSemanticConventions.cs
- src/OpenTelemetry.Extensions.Docker/Utils/EncodingUtils.cs
- test/OpenTelemetry.Extensions.Docker.Tests/Resources/DockerResourceDetectorTests.cs
Towards #276.
[Extensions.Docker] File scoped namespace
> [Extensions.Docker] File scoped namespace

- .github/component_owners.yml
Add Component Owners for `OpenTelemetry.Extensions.AzureMonitor`
> Add Component Owners for OpenTelemetry.Extensions.AzureMonitor

- src/OpenTelemetry.Extensions.AzureMonitor/ApplicationInsightsSampler.cs
On successful sampling, add `sampleRate` attribute to `SamplingResult`.
TODO
* Update `CHANGELOG.md` in a follow up PR.
> OpenTelemetry.Extensions.AzureMonitor - Add sampleRate attribute to SamplingResult.

- src/OpenTelemetry.Extensions.AzureMonitor/CHANGELOG.md
Requesting a release for OpenTelemetry.Extensions.AzureMonitor v1.0.0-beta1, following instructions on [How to request for release of package](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md#how-to-request-for-release-of-package).
I used next Monday for the release date.
@rajkumar-rangaraj I added a changelog entry for #623.
@utpilla please review.
> changelog for release: Extensions.AzureMonitor 1.0.0-beta1

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/README.md
- src/OpenTelemetry.Instrumentation.Wcf/README.md
- Add the link for number of package downloads for:
- `OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule`
- `OpenTelemetry.Instrumentation.Wcf`
> Update README for projects missing the number of package downloads

- src/OpenTelemetry.Extensions.AzureMonitor/ApplicationInsightsSampler.cs
- src/OpenTelemetry.Extensions.AzureMonitor/CHANGELOG.md
- src/OpenTelemetry.Extensions.AzureMonitor/OpenTelemetry.Extensions.AzureMonitor.csproj
Fixes #.
- Updated TargetFrameworks from `net461` and `net6.0` to `netstandard2.0`.
- Updated `CHANGELOG.md`
- Changed `sampleRate` attribute to `float`.
*~~[ ] Design discussion issue #~~
> Replaced  TargetFrameworks from net461 and net6.0 to netstandard2.0

- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/590#issuecomment-1245999476, CC @utpilla
Changes version numbering scheme of the Instrumentation.AwsLambda which was previously released as 1.1.0.beta1 (& different package name) to use a dot before the pre-release number.
> Instrumentation.AwsLambda: Fix versioning scheme.

- src/OpenTelemetry.Contrib.Shared/Api/ActivityHelperExtensions.cs
Fixes #640
* Removed all the reflection enumeration code which wasn't being used including the stuff that is bugged when redirecting to the DS7 version. 
* Dropped in a TODO about updating to remove the rest. Need to wait for DS7/OTel 1.4.x to complete that part of it.
> Remove unused Activity reflection code

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
- Move `TableNameMappings` checks from `GenevaTraceExporter` and `GenevaLogExporter` ctor to `GenevaExporterOptions` class
> [Exporter.Geneva] Move TableNameMappings checks to GenevaExporterOptions class

- .github/workflows/windows-ci.yml
- build/Common.props
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- test/OpenTelemetry.Instrumentation.Owin.Tests/OpenTelemetry.Instrumentation.Owin.Tests.csproj
Updated to target `net462` and OTel 1.3.1 SDK
See https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/652#issuecomment-1252723191
/cc @Kielek
> [Owin] Bump target .NET Framework and OTel SDK version

- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Logs/GenevaLogExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/LogExporterBenchmarks.cs
`AddPartAField` method expects an `object` as a parameter. We can avoid calling this method to serialize `timestamp` as it would convert `DateTime` to an `object`.
- Avoid allocation due to boxing
> [Exporter.Geneva] Optimize GenevaLogExporter

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
> [TelemetryHttpModule] Update `OpenTelemetry.Api` reference and changelog

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
- src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNet.Tests/OpenTelemetry.Instrumentation.AspNet.Tests.csproj
Fixes N/A
Use variables defined in `Common.props` in Instrumentation.AspNet projects.
It was released few days ago, so it is good time to adjust it as it is common values.
> [Instrumentation.AspNet] use prop variables in project files

- build/Common.nonprod.props
- test/OpenTelemetry.Exporter.Geneva.Benchmark/OpenTelemetry.Exporter.Geneva.Benchmark.csproj
- Update BenchmarkDotNet version
> [Exporter.Geneva] Update BenchmarkDotNet version

- src/OpenTelemetry.Instrumentation.Process/ProcessMetrics.cs
- test/OpenTelemetry.Instrumentation.Process.Tests/ProcessMetricsTests.cs
Fixes #677.
Adds the `process.cpu.time` counter.
> [Instrumentation.Process] Add CPU metrics

- src/OpenTelemetry.Instrumentation.Runtime/README.md
> Instrumentation.Runtime - Fix incorrect readme content

- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs
This PR fixes two issues with the current implementation:
- Uses `EventLevel.Critical` instead of `EventLevel.LogAlways`
- Counters don't require a specific log level to work. Depending on the `EventSource` implementor, this change can avoid a lot of overhead (preparing and serializing event arguments, potentially taking more expensive code paths).
- Avoids a race condition when initializing the `EventCountersMetrics` instance
- As `OnEventSourceCreated` can run before the constructor is done, you can run into a situation where you fail to enable an `EventSource` instance. A simple lock avoids this race.
- Example course of events:
- Thread A calls into `OnEventSourceCreated` and sees options aren't set yet
- Thread B executes the constructor, processing any entries in …
> [Instrumentation.EventCounters] Avoid race condition and performance trap in EventCountersMetrics

- NuGet.config
Partially solves discussion under
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/680#issuecomment-1282415716
Comment out MyGet nuget source. I would keep it in the source code to allow user play with OTel SDK/API nightly builds.
It is not used in any typical scenario.
> Disable MyGet nuget source

- README.md
@Kielek has been actively contributing to this repo for a few months now. He is already an approver in the instrumentation repo (https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) since Apr 2022 and has made significant contributions to the overall project in the past year.
Contributions include active reviews, efforts to standardize code style, diagnostics, project structure across all components for this repo, and expanding test coverage.
Link to all the PRs submitted by Piotr: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pulls?q=is%3Apr+author%3Akielek
> Add Piotr as Approver

- build/Common.nonprod.props
- build/Common.props
- examples/AspNet/Examples.AspNet.csproj
- examples/AspNet/Global.asax.cs
- src/OpenTelemetry.Extensions.Docker/CHANGELOG.md
- src/OpenTelemetry.Extensions.Docker/OpenTelemetry.Extensions.Docker.csproj
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
- src/OpenTelemetry.Instrumentation.EventCounters/OpenTelemetry.Instrumentation.EventCounters.csproj
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
- src/OpenTelemetry.Instrumentation.MassTransit/OpenTelemetry.Instrumentation.MassTransit.csproj
- src/OpenTelemetry.Instrumentation.MySqlData/OpenTelemetry.Instrumentation.MySqlData.csproj
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- src/OpenTelemetry.Instrumentation.Process/OpenTelemetry.Instrumentation.Process.csproj
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
- test/OpenTelemetry.Exporter.Stackdriver.Tests/OpenTelemetry.Exporter.Stackdriver.Tests.csproj
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/OpenTelemetry.Instrumentation.MySqlData.Tests.csproj
"OpenTelemetryCoreLatestVersion" should point to the latest stable version of the core packages. The name reflects it is latest stable. We could add another latest-prerelease, for those projects that want to depend on it.
> Refactor props file to have latest version of core pkgs

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporterOptions.cs
This aligns with the default for OTLP Exporter, and also backend expectations.
> [Exporter.Geneva] - Change default metric exporter interval to 60sec

- NuGet.config
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/HangfireInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentationJobFilterAttribute.cs
- src/OpenTelemetry.Instrumentation.Hangfire/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/HangfireInstrumentationJobFilterAttributeTests.cs
Adds support to optionally record hangfire job exceptions.
> [Instrumentation.Hangfire] Add option to record exceptions

- NuGet.config
- src/OpenTelemetry.Instrumentation.Process/ProcessMetrics.cs
- test/OpenTelemetry.Instrumentation.Process.Tests/ProcessMetricsTests.cs
Update to use Process.Refresh() on each callback after benchmarking the perf https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/717 and found it cheap.
Also, addressing https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/664#discussion_r993403498.
> [Instrumentation.Process] Dropping Snapshot

- src/OpenTelemetry.Instrumentation.Runtime/README.md
Already mentioned this in changelog: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md#unreleased , so I think this is just too much notes.
> Remove unnecessary notes from readme

- src/OpenTelemetry.Contrib.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.AWS/Implementation/AWSTracingPipelineCustomizer.cs
Starting with version 3.7.100 of the AWS .NET SDK the EndpointResolver is replaced with a service specific version of the handler. This breaks the OpenTelemetry integration because OpenTelemetry was inserting itself just after EndpointResolver in the SDK's request pipeline.
The fix is for OpenTelemetry to inject itself before the RetryHandler which happens after endpoint resolutions. So the position will be the same in the request pipeline.
This fix will is compatible with both version 3.7.100 and versions before 3.7.100 so it will not break users that haven't upgrade their SDK version. 
This change is very similar to the AWS X-Ray change which this code is based off: https://github.com/aws/aws-xray-sdk-dotnet/pull/268 
For significant contributions please make sure you have completed the …
> Fix using version 3.7.100 of AWS SDK causing exception not finding EndpointResolver

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
1. Export scopes which have a non-null key as individual columns (each key-value pair from the scopes is exported as its own column; these columns would also be taken into consideration when the CustomFields option is applied)
2. GenevaExporter would not check for duplicate keys (if the scopes and log message together have any duplicate keys, they would all be exported)
**1. Key is null**
```csharp
using (logger.BeginScope("MyScope"))
{
logger.LogInformation("Hello from {food} {price}.", "artichoke", 3.99);
}
```
No scopes are exported in this case as there is no key provided for the scope.
**2. Using formatted string in scopes**
```csharp
using (logger.BeginScope("MyInnerInnerScope with {name} and {age} of custom", "John Doe", 35))
{
logger.LogInformation("Hello from {food} {price}.", …
```
> [Exporter.Geneva] Update scopes

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/OpenTelemetry.Instrumentation.Process.csproj
- src/OpenTelemetry.Instrumentation.Process/ProcessMetrics.cs
- src/OpenTelemetry.Instrumentation.Process/README.md
- test/OpenTelemetry.Instrumentation.Process.Tests/OpenTelemetry.Instrumentation.Process.Tests.csproj
- test/OpenTelemetry.Instrumentation.Process.Tests/ProcessMetricsTests.cs
Addressed TODO.
Update OTel API version to be `1.4.0-beta.2` and change process metrics type from ObservableGauge to `ObservableUpDownCounter`. Updated instruments are: "process.memory.usage", "process.memory.virtual" and "process.threads".
> [Instrumentation.Process] Update OTel API version to 1.4.0-beta.2 and change runtime metrics type to ObservableUpDownCounter

- build/Common.nonprod.props
- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Instrumentation.Process/OpenTelemetry.Instrumentation.Process.csproj
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- test/OpenTelemetry.Instrumentation.Process.Tests/OpenTelemetry.Instrumentation.Process.Tests.csproj
- test/OpenTelemetry.Instrumentation.Runtime.Tests/OpenTelemetry.Instrumentation.Runtime.Tests.csproj
Addressed https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/751#discussion_r1012232038
> Add vars for OpenTelemetryCoreLatestPreRelease and OpenTelemetryExporterInMemoryLatestPreReleasePkgVer.

- src/OpenTelemetry.Instrumentation.Hangfire/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/HangfireInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentationJobFilterAttribute.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/HangfireInstrumentationJobFilterAttributeTests.cs
Fixes #755.
Adds support for using custom display names in the activities display name.
> [Instrumentation.Hangfire] Added support for custom job display names

- src/OpenTelemetry.Contrib.Instrumentation.AWS/CHANGELOG.md
Request release of OpenTelemetry.Contrib.Instrumentation.AWS because currently this library is broken for the current release of the AWS .NET SDK and was fixed by PR https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/726.
Updated CHANGELOG for release of the OpenTelemetry.Contrib.Instrumentation.AWS package. 
> Request release of OpenTelemetry.Contrib.Instrumentation.AWS

- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
EventCounters instrumentation does not work for several [well-known EventSources](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters?source=recommendations).
E.g. `Microsoft-AspNetCore-Server-Kestrel` or most of the counters in `Microsoft.AspNetCore.Http.Connections`.
It happens because of instrument length limitations (63 symbols).
End users can't do anything about it except republish all events, so we need to find a reasonable way to allow at least well-known event sources. Kestrel counters, for example, are extremely useful and can't be measured in other ways (DiagSource/ActivitySource instrumentation in hosting).
So, `EventCounters.Microsoft-AspNetCore-Server-Kestrel.` is already 50 chars and it doesn't even include event name.
This change proposes:
- use …
> [Instrumentation.EventCounters] Support long event source names better in EventCounters instrumentation

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModule.cs
Fixes https://github.com/open-telemetry/opentelemetry-dotnet/issues/3286
> restore Activity.Current before all IIS LifeCycle events

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
Follow up to #774
`Instrumentation.Process` Release `1.0.0-alpha.2.`
It will make easier way to bump OTel in AutoInstrumentation project.
> [Instrumentation.Process] Release 1.0.0-alpha.2

- .github/workflows/package-Exporter.Geneva.yml
- .github/workflows/package-Exporter.Instana.yml
- .github/workflows/package-Exporter.Stackdriver.yml
- .github/workflows/package-Extensions.AWSXRay.yml
- .github/workflows/package-Extensions.AzureMonitor.yml
- .github/workflows/package-Extensions.Docker.yml
- .github/workflows/package-Extensions.PersistentStorage.yml
- .github/workflows/package-Extensions.yml
- .github/workflows/package-Instrumentation.AWS.yml
- .github/workflows/package-Instrumentation.AWSLambda.yml
- .github/workflows/package-Instrumentation.AspNet.TelemetryHttpModule.yml
- .github/workflows/package-Instrumentation.AspNet.yml
- .github/workflows/package-Instrumentation.Elasticsearch.yml
- .github/workflows/package-Instrumentation.EntityFrameworkCore.yml
- .github/workflows/package-Instrumentation.EventCounters.yml
- .github/workflows/package-Instrumentation.GrpcCore.yml
- .github/workflows/package-Instrumentation.Hangfire.yml
- .github/workflows/package-Instrumentation.MassTransit.yml
- .github/workflows/package-Instrumentation.MySqlData.yml
- .github/workflows/package-Instrumentation.Owin.yml
- .github/workflows/package-Instrumentation.Process.yml
- .github/workflows/package-Instrumentation.Quartz.yml
- .github/workflows/package-Instrumentation.StackExchangeRedis.yml
- .github/workflows/package-Instrumentation.Wcf.yml
Follow up to #789
Follow up to #759
Adding NET7 to Test projects broke these package workflows because they try to restore the entire solution, including test projects.
- Only restore the required project
> Update package workflows to only restore specific project

- .github/workflows/package-Instrumentation.Runtime.yml
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Package publish workflow is failing for this project: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/3528050002/jobs/5917735748
- Setup .NET 7
> Update package workflow for runtime

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MessagePackSerializer.cs
Many .NET users are adopting DateTimeOffset, there seem to be a common expectation that DateTimeOffset should be handled in the same way as DateTime.
Additional context:
* https://stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset
* https://github.com/open-telemetry/opentelemetry-dotnet/blob/943c856c1c6295a536bc8a1c89896febc0be6107/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/TimestampHelpers.cs
> Handle DateTimeOffset in the same way as DateTime

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
Requesting release for https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/761
> release Instrumentation.AspNet.TelemetryHttpModule 1.0.0-rc9.7

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
Fixes #783.
Update of underlying Google dependencies to be more in line with potential other Google dependencies used in the same project as the Stackdriver exporter.
> [Exporter.Stackdriver] Update dependencies

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
The values for overflow buckets should be serialized as the value-count pair: __LastBucketValue + 1_,count_
For eg. for a Histogram with the boundaries: [25,50,100], if the value recorded is 150, it should be serialized as the following value-count pair: (101, 150)
- Fix the serialization for overflow bucket
> [Exporter.Geneva] Fix overflow bucket value serialization for Histogram

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/GenevaMetricExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
Refer to #805
The values for overflow buckets should be serialized as the value-count pair: __LastBucketValue + 1_,count_
For eg. for a Histogram with the boundaries: [25,50,100], if the value recorded is 150, it should be serialized as the following value-count pair: (101, 1)
- Fix the serialization for overflow bucket
> [Exporter.Geneva][Patch for 1.3.0] Fix overflow bucket serialization for GenevaExporter

- src/OpenTelemetry.Exporter.Geneva/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MessagePackSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- When serializing objects, recognize ISpanFormattable on .NET 6 in order to avoid a temp string allocation in that case.
- Use binary primitives to serialize scalar types more efficiently (avoiding repeated bound checks).
> Leverage modern .NET features for improved perf.

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Internal/ExporterEventSource.cs
Fixes #753 
- Fix EventSource logging for GenevaExporter
> [Exporter.Geneva] Fix EventSource logging for GenevaExporter

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes N/A.
Bump OpenTelemetry prereleased to 1.4.0-rc.1.
Then I will create PR/PRs to release Process and Runtime packages.
> Bump OpenTelemetry prereleased to 1.4.0-rc.1

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/WcfInstrumentationConstants.cs
Fixes N/A
Adjust tag to otel-spec requierments.
https://github.com/open-telemetry/opentelemetry-specification/blob/5b6d22512ef72214f7cbd52747a1fbfe49f8121f/CHANGELOG.md?plain=1#L611-L612
> [Instrumentation.WCF] fix rpc.system tag

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
* Updates `MsgPackTraceExporter` to use the new DS7 "Enumerate" APIs which help with perf.
(Modified the benchmark to also use links for this run.)
Before:
|            Method |     Mean |   Error |  StdDev |   Gen0 | Allocated |
|------------------ |---------:|--------:|--------:|-------:|----------:|
| SerializeActivity | 341.9 ns | 5.34 ns | 4.99 ns | 0.0076 |      96 B |
After:
|            Method |     Mean |   Error |  StdDev | Allocated |
|------------------ |---------:|--------:|--------:|----------:|
| SerializeActivity | 260.0 ns | 4.42 ns | 4.13 ns |         - |
> [GenevaExporter] Update MsgPackTraceExporter for new Enumerate* DS7 APIs

- src/OpenTelemetry.Extensions.AzureMonitor/ApplicationInsightsSampler.cs
- src/OpenTelemetry.Extensions.AzureMonitor/OpenTelemetry.Extensions.AzureMonitor.csproj
- Enable Code Analysis for AzureMonitor Extensions
- Move hash computation to an `unchecked` block
> [Extensions.AzureMonitor] Enable Code Analysis for AzureMonitor Extensions

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
Fixes N/A.
* Update OTel SDK version to `1.3.1`.
([#631](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/631))
* Change value `rpc.system` from `wcf` to `dotnet_wcf`.
([#837](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/837))
> [Instrumentation.WCF] Release 1.0.0-rc.8

- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- Fix potential NullReferenceException thrown when the values for the tags `otel.status_code` and `otel.status_description` is null
> [Exporter.Geneva] Update GenevaTraceExporter

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes N/A.
Bump OTel to last unstable release for packages using unstable release.
Needed by AutoInstrumentation project.
> Bump OTel to 1.4.0-rc.2

- test/OpenTelemetry.Extensions.AzureMonitor.Tests/ApplicationInsightsSamplerTests.cs
Fixes #891
This test validates the sampler. The test is evaluating two TraceIds, and asserting that for a given sampling ratio, one should be dropped and the other should be sampled. It seems that sampling ratio is too high.
The sampling calculator was changed in #846, `TraceId.ToHexString().ToLowerInvariant()` was changed to `TraceId.ToHexString().ToUpperInvariant()`. This broke the unit test, but wasn't caught because the test wasn't executing in the CI.
#890 fixed the project to run tests, and disabled this broken test.
- Changed unittest sample ratio `0.86` to `0.5`.
- some refactoring to make the test easier to read.
> [Extensions.AzureMonitor.ApplicationInsightsSampler] fix unit test

- src/OpenTelemetry.Extensions.Docker/CHANGELOG.md
Update CHANGELOG for 1.1.0-beta.1 release, that will include CGroup V2 support (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/839, https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/693). It still will have `-beta.1` suffix to make it prerelease until decision on package name will be done (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/881, https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/869)
> [Extensions.Docker] Update CHANGELOG for 1.0.0-beta.2 release

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
It was failing. frequently.
Fixes #903
> Disabling `EventSourceNameShortening` unit test

- .github/workflows/assign-reviewers.yml
I opened #908 as a draft to prevent spamming people, but as a custom workflow is used instead of `CODEOWNERS` it didn't have the desired effect.
This PR changes the workflow to only assign when the pull request is not a draft.
If the current behaviour is intentional, feel free to close this pull request.
> Do not assign people to draft pull requests

- src/OpenTelemetry.Instrumentation.Process/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Process/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Runtime/MeterProviderBuilderExtensions.cs
Follow up #893 #892
make configure action nullable
based on https://github.com/open-telemetry/opentelemetry-dotnet/pull/3653/files#r970049254 and conversation with @alanwest 
> [Instrumentation.Process, Instrumentation.Process] make configure action nullable

- build/Common.props
- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Extensions.Docker/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/915#discussion_r1084280076
Bump OpenTelemetry Core packages to 1.3.2
Changelog messages based on local, in-file wording.
> Bump OpenTelemetry Core packages to 1.3.2

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Wcf/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/TracerProviderBuilderExtensions.cs
Propagate recommendations from https://github.com/open-telemetry/opentelemetry-dotnet/pull/3653/files#r970049254
Remove `AddEntityFrameworkCoreInstrumentation` with default parameter
> [Instrumentation.WCF] Remove AddWcfInstrumentation with default parameter

- src/OpenTelemetry.Instrumentation.AspNet/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/TracerProviderBuilderExtensions.cs
Propagate recommendations from https://github.com/open-telemetry/opentelemetry-dotnet/pull/3653/files#r970049254
Remove `AddAspNetInstrumentation `  with default parameter
> [Instrumentation.AspNet] Remove AddAspNetInstrumentation with default parameter

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes N/A.
Bump OTel to last unstable release for packages using unstable release.
Needed by AutoInstrumentation project (please expect release for Process and Runtime projects).
> Bump OTel to 1.4.0-rc.3

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
[xUnit.net 00:00:10.56]     OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.EventCounter [FAIL]
[xUnit.net 00:00:10.56]       Assert.Equal() Failure
[xUnit.net 00:00:10.56]       Expected: 1997.0201999999999
[xUnit.net 00:00:10.56]       Actual:   0
[xUnit.net 00:00:10.56]       Stack Trace:
[xUnit.net 00:00:10.56]         D:\a\opentelemetry-dotnet-contrib\opentelemetry-dotnet-contrib\test\OpenTelemetry.Instrumentation.EventCounters.Tests\EventCountersMetricsTests.cs(53,0): at OpenTelemetry.Instrumentation.EventCounters.Tests.EventCountersMetricsTests.EventCounter()
> Ignore unstable tests

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
Fix code analysis warnings in OpenTelemetry.Instrumentation.EventCounters.
> [Instrumentation.EventCounters] Fix analysis warnings

- src/OpenTelemetry.Extensions.PersistentStorage/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.PersistentStorage/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.PersistentStorage/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.PersistentStorage/FileBlob.cs
- src/OpenTelemetry.Extensions.PersistentStorage/FileBlobProvider.cs
- src/OpenTelemetry.Extensions.PersistentStorage/PersistentStorageHelper.cs
Fix/suppress code analysis warnings in OpenTelemetry.Contrib.Extensions.PersistentStorage.
> [Extensions.PersistentStorage] Fix analysis warnings

- src/OpenTelemetry.Instrumentation.AWSLambda/AWSLambdaWrapper.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaHttpUtils.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/SampleLambdaContext.cs
Fix/suppress code analysis warnings in OpenTelemetry.Contrib.Instrumentation.AWSLambda.
> [Instrumentation.AWSLambda] Fix analysis warnings

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/ProcessMetrics.cs
- src/OpenTelemetry.Instrumentation.Process/README.md
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
- test/OpenTelemetry.Instrumentation.Process.Tests/ProcessMetricsTests.cs
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/831.
Related to: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/948
Used static ctor for ProcessMetrics and made Meter static.
Removed/updated CPU utilization related tests.
Added tests to check thread safety.
> [Instrumentation.Process] Removed CPU utilization metric `process.cpu.utilization`.

- .github/workflows/package-Exporter.Geneva.yml
- .github/workflows/package-Exporter.Instana.yml
- .github/workflows/package-Exporter.Stackdriver.yml
- .github/workflows/package-Extensions.AWSXRay.yml
- .github/workflows/package-Extensions.AzureMonitor.yml
- .github/workflows/package-Extensions.Docker.yml
- .github/workflows/package-Extensions.PersistentStorage.Abstractions.yml
- .github/workflows/package-Extensions.PersistentStorage.yml
- .github/workflows/package-Extensions.yml
- .github/workflows/package-Instrumentation.AWS.yml
- .github/workflows/package-Instrumentation.AWSLambda.yml
- .github/workflows/package-Instrumentation.AspNet.TelemetryHttpModule.yml
- .github/workflows/package-Instrumentation.AspNet.yml
- .github/workflows/package-Instrumentation.Elasticsearch.yml
- .github/workflows/package-Instrumentation.EntityFrameworkCore.yml
- .github/workflows/package-Instrumentation.EventCounters.yml
- .github/workflows/package-Instrumentation.GrpcCore.yml
- .github/workflows/package-Instrumentation.Hangfire.yml
- .github/workflows/package-Instrumentation.MySqlData.yml
- .github/workflows/package-Instrumentation.Owin.yml
- .github/workflows/package-Instrumentation.Process.yml
- .github/workflows/package-Instrumentation.Quartz.yml
- .github/workflows/package-Instrumentation.Runtime.yml
- .github/workflows/package-Instrumentation.StackExchangeRedis.yml
- .github/workflows/package-Instrumentation.Wcf.yml
- .github/workflows/package-ResourceDetectors.Azure.yml
- build/RELEASING.md
Fixes N/A
Extend releasing process.
Automate creating GitHub releases for each package.
Current, tags-only approach does not create GitHub notifications about new releases. 
On the GitHub you can subscribe for the new releases
Tested on my fork with disabled nuget.org step:
> Create GitHub releases

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes #.
Bump OTel to 1.4.0-rc.4
Needed for OpenTelemetry Automatic Instrumentation for .NET. Expect follow upr PR with request to release Process and Runtime.
> Bump OTel to 1.4.0-rc.4

- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpanSerializer.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Transport.cs
- src/OpenTelemetry.Exporter.Instana/OpenTelemetry.Exporter.Instana.csproj
Fixes #.
Instana backend reported generated JSON by InstanaExporter as wrong. 
JSON should contains spans node as a root but it was not a case.
> [Instana Exporter] Wrong JSON format for serialized spans

- build/Common.props
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/993#discussion_r1104966748
Allow to use further releases of OTel for prerelease version
> Allow to use further releases of OTel for prerelease version

- .github/workflows/ci-Instrumentation.Process.yml
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
As more components being added, CI is getting slower.
This PR is the first step exploring a per-component CI approach.
Here are my thoughts:
* A catch-all CI would still exist, and will only be triggered for any one of the following conditions:
* The trigger is a pull (PR), and it includes changes to a global file (e.g. CI rules, shared files such as https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Internal
* The trigger is a push (push should run all the tests)
* If a pull request does not include global changes, it should not trigger the catch-all CI; instead, it will only trigger a component specific CI which saves execution time
> First step towards decoupling the CI

- CONTRIBUTING.md
Update the `CONTRIBUTING.md` with the required .NET framework(s) to build things based on changes to the repo.
- `global.json` currently requires .NET 7.
- Project TFM for .NET desktop are all `net462`.
> Updated contribution guide .NET build requirements.

- .vscode/extensions.json
- .vscode/tasks.json
- Add `extensions.json` to match [the main `opentelemetry-dotnet` project](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.vscode/extensions.json).
- Add `tasks.json` to execute the build and test from inside VS Code.
This should make it easier for VS Code folks to iterate in their workflow.
> Add settings for VS Code build support.

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/EntityFrameworkInstrumentationOptions.cs
Fix code analysis warning in OpenTelemetry.Instrumentation.EntityFrameworkCore.
> [Instrumentation.EntityFrameworkCore] Fix analysis warning

- test/OpenTelemetry.Extensions.Tests/Trace/AutoFlushActivityProcessorTests.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
Addressing https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/977 and https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/941 as unstable tests are really affecting overall CI health.
> Disable flaky tests

- .github/PULL_REQUEST_TEMPLATE.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/ProcessMetrics.cs
- src/OpenTelemetry.Instrumentation.Process/README.md
- test/OpenTelemetry.Instrumentation.Process.Tests/ProcessMetricsTests.cs
Based on spec discussion: https://github.com/open-telemetry/opentelemetry-specification/pull/2392#discussion_r832488855
Related to: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/972.
Exposed required metric `process.processors` for computing CPU utilization in the backend.
> [Instrumentation.Process] Exposed required metric `process.cpu.count` for computing CPU utilization in the backend.

- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorLogExporterOptions.cs
Switch to a constant for the default event namespace. The previous version `Assembly.GetEntryAssembly()?.GetName().Name ?? string.Empty` would throw when run from testhost.
> [OneCollector] Use a constant for DefaultEventNamespace

- src/OpenTelemetry.Instrumentation.Quartz/Implementation/QuartzDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Quartz/OperationName.cs
- src/OpenTelemetry.Instrumentation.Quartz/QuartzInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Quartz/TraceProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/QuartzDiagnosticListenerTests.cs
Fix/suppress code analysis warnings in OpenTelemetry.Instrumentation.Quartz.
> [Instrumentation.Quartz] Fix analysis warnings

- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentation.cs
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/MySqlDataTests.cs
Fix/suppress code analysis warnings in OpenTelemetry.Instrumentation.MySqlData.
> [Instrumentation.MySqlData] Fix analysis warnings

- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentationJobFilterAttribute.cs
Fix/suppress code analysis warnings in OpenTelemetry.Instrumentation.Hangfire.
> [Instrumentation.Hangfire] Fix analysis warnings

- examples/grpc.core/Examples.GrpcCore.AspNetCore/Startup.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ClientTracingInterceptor.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ClientTracingInterceptorOptions.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/RpcScope.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ServerTracingInterceptor.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ServerTracingInterceptorOptions.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/FoobarService.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreClientInterceptorTests.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreServerInterceptorTests.cs
Fix/suppress code analysis warnings in OpenTelemetry.Instrumentation.GrpcCore.
> [Instrumentation.GrpcCore] Fix analysis warnings

- src/OpenTelemetry.Exporter.OneCollector/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/net7.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/netstandard2.1/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorLogExporterBuilder.cs
- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorLogExporterOptions.cs
- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorOpenTelemetryLoggerOptionsExtensions.cs
- src/OpenTelemetry.Exporter.OneCollector/OneCollectorExporterOptions.cs
- src/OpenTelemetry.Exporter.OneCollector/OneCollectorExporterTransportOptions.cs
- src/OpenTelemetry.Exporter.OneCollector/README.md
- test/OpenTelemetry.Exporter.OneCollector.Tests/OneCollectorOpenTelemetryLoggerOptionsExtensionsTests.cs
* Tenant token is now parsed automatically from the instrumentation key
* Registration extensions now operate on a builder instead of options directly. This is kind of a WIP I think it will make things easier as more and more features get added. But it may be removed before stable.
> [OneCollector] Registration extension + tenant token tweaks

- examples/process-instrumentation/process-instrumentation-grafana-dashboard-sample.json
- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/README.md
Addressed https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/447#issuecomment-1434004065
Added Grafana dashboard template to the example folder.
> [Instrumentation.Process] Added Grafana dashboard template to the example folder.

- src/OpenTelemetry.Exporter.OneCollector/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/net7.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/netstandard2.1/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/ConnectionStringParser.cs
- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorLogExporterBuilder.cs
- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorLogExporterOptions.cs
- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorOpenTelemetryLoggerOptionsExtensions.cs
- src/OpenTelemetry.Exporter.OneCollector/OneCollectorExporterOptions.cs
- src/OpenTelemetry.Exporter.OneCollector/OneCollectorExporterTransportOptions.cs
- src/OpenTelemetry.Exporter.OneCollector/OneCollectorExporterValidationException.cs
- src/OpenTelemetry.Exporter.OneCollector/README.md
- test/OpenTelemetry.Exporter.OneCollector.Tests/ConnectionStringParserTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/OneCollectorOpenTelemetryLoggerOptionsExtensionsTests.cs
Follow-up to: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1032#discussion_r1114877266
* Switch to a connection string design instead of passing instrumentation key directly.
> [OneCollectorExporter] Connection string design

- src/OpenTelemetry.Exporter.Geneva/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- Update publicAPI files for GenevaExporter for the stable release 1.4.0
> [Exporter.Geneva] Update publicAPI files for GenevaExporter

- src/OpenTelemetry.Exporter.Instana/.publicApi/net461/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.Instana/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Exporter.Instana/OpenTelemetry.Exporter.Instana.csproj
- src/OpenTelemetry.Exporter.Instana/README.md
- src/OpenTelemetry.Exporter.Instana/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Exporter.Instana.Tests/OpenTelemetry.Exporter.Instana.Tests.csproj
Follow up to #1038 where Instana was unpinned from $(OpenTelemetryCoreLatestVersion)
Towards #1031
Bump OTel 1.4.0, as this version is not supporting .NET Framework 4.6.1 and .NET Core App 3.1
The package will produce libraries for .NET Framework 4.6.2 and test was switched to `net7.0;net.60;net462`
> [Exporter.Instana] Bump OTel to 1.4.0

- examples/AspNet/Examples.AspNet.csproj
- examples/AspNet/Global.asax.cs
- examples/AspNet/Web.config
- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/README.md
- src/OpenTelemetry.Instrumentation.MassTransit/README.md
- src/OpenTelemetry.Instrumentation.Quartz/README.md
Related to https://github.com/open-telemetry/opentelemetry-specification/pull/2858
Remove references to Jaeger exporter. Replace by OTLP for most cases.
It will be fully deprecated in July.
> Remove references to Jaeger exporter

- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInMetricsListener.cs
Fixes [#4169](https://github.com/open-telemetry/opentelemetry-dotnet/issues/4169)
Is a continuation of [#4171](https://github.com/open-telemetry/opentelemetry-dotnet/pull/4171)
Initiated by [this issue](https://github.com/open-telemetry/opentelemetry-demo/issues/737) on the OpenTelemetry Demo
Fixes the metric description to conform with specifications and prevent errors from the Prometheus exporter in the collector.
> [Instrumentation.AspNet] fix metric description

- README.md
Proposing to add @Kielek as a Maintainer for the contrib repo.
Piotr has been an active Approver and has made significant contributions to general maintenance and upkeep of the repo. He became the # 3 top contributor of this repo in less than a year. He is also a Maintainer of the instrumentation repo (https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) and I feel it would be great to utilize his expertise and increase his scope of involvement.
> Add Piotr as Maintainer

- build/Common.props
- build/OpenTelemetryContrib.test.ruleset
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/Resources/AWSECSResourceDetector.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/Resources/TestAWSECSResourceDetector.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/Resources/TestAWSEKSResourceDetector.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/Trace/TestAWSXRayPropagator.cs
- Enable `AnalysisLevel` at `latest-All`.
- Add relevant suppressions for test projects.
Resolves #950.
Depends on:
- #951
- #952
- #953
- #954
- #955
- #956
- #957
- #958
- #959
- #960
- #961
- #962
- #963
- #964
- #965
- #966
- #967
- #968
- #1043
- #1061
> Enable AnalysisLevel latest-All

- .github/component_owners.yml
- opentelemetry-dotnet-contrib.sln
- test/OpenTelemetry.Exporter.OneCollector.Benchmarks/LogRecordCommonSchemaJsonHttpPostBenchmarks.cs
- test/OpenTelemetry.Exporter.OneCollector.Benchmarks/OpenTelemetry.Exporter.OneCollector.Benchmarks.csproj
- test/OpenTelemetry.Exporter.OneCollector.Benchmarks/Program.cs
* Adds a benchmark project for OneCollectorExporter and benchmarks for LogRecord export.
| Method | NumberOfBatches | NumberOfLogRecordsPerBatch | EnableCompression |         Mean |       Error |      StdDev | Allocated |
|------- |---------------- |--------------------------- |------------------ |-------------:|------------:|------------:|----------:|
| Export |               1 |                       1000 |             False |     474.8 us |     6.18 us |     5.16 us |     857 B |
| Export |               1 |                       1000 |              True |   1,683.1 us |     7.87 us |     6.98 us |    1066 B |
| Export |               1 |                      10000 |             False |     748.2 us |    14.62 us |    16.83 us |     857 B |
| Export |               1 | …
> [OneCollector] Add benchmark project

- src/OpenTelemetry.Contrib.Shared/Api/StatusHelper.cs
- src/OpenTelemetry.Instrumentation.MySqlData/.publicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.MySqlData/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.MySqlData/MySqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentation.cs
- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataTraceCommand.cs
- src/OpenTelemetry.Instrumentation.MySqlData/OpenTelemetry.Instrumentation.MySqlData.csproj
- src/OpenTelemetry.Instrumentation.MySqlData/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Contrib.Tests.Shared/ActivityHelperExtensions.cs
- test/OpenTelemetry.Contrib.Tests.Shared/TestActivityExportProcessor.cs
- test/OpenTelemetry.Contrib.Tests.Shared/TestActivityProcessor.cs
- test/OpenTelemetry.Contrib.Tests.Shared/TestSampler.cs
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/MySqlDataTests.cs
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/OpenTelemetry.Instrumentation.MySqlData.Tests.csproj
Towards #894.
[Instrumentation.MySqlData] Nullable.
Part of shared files also updated.
> [Instrumentation.MySqlData] Nullable

- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- Fix serialization issue when there are no exemplars
- Add unit test for the new serialization approach
> [Exporter.Geneva] Fix serialization issue when there are no exemplars

- src/OpenTelemetry.Extensions/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Extensions/Internal/ActivityEventAttachingLogProcessor.cs
- src/OpenTelemetry.Extensions/Internal/OpenTelemetryExtensionsEventSource.cs
- src/OpenTelemetry.Extensions/Logs/LogToActivityEventConversionOptions.cs
- test/OpenTelemetry.Extensions.Tests/ActivityEventAttachingLogProcessorTests.cs
I found it useful to be able to filter which log message will be attached to an Activity. This PR adds a Filter callback which can simply filter out a log message.
~~[ ] Design discussion issue~~
> [Extensions] Add LogToActivityEventConversionOptions.Filter callback

- build/Common.nonprod.props
- build/Common.props
- build/process-codecoverage.ps1
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/OpenTelemetry.Contrib.Instrumentation.AWS.Tests.csproj
Fixes #.
As there is no more project referencing .NET Framework 4.5.2 packages can be updated (including Moq and xunit.runner).
> Bump test dependencies

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/TableNameSerializer.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
[Note: This is going into a branch I created off the GenevaExporter-1.4.0 tag.]
Fixes #1105
* Backport the fix from #1109 for a 1.4.0 hotfix.
> [GenevaExporter] [1.4.0 hotfix] Backport remove extra table name mapping validation

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
- Update TldLogExporter to log `eventId.Id` as a PartB field
> [Exporter.Geneva][TldLogExporter] Update TldLogExporter to log eventId.Id as a PartB field

- src/OpenTelemetry.Exporter.Geneva/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Geneva/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/EventNameExportMode.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
Towards #584 
This PR adds a new option called `EventNameExportMode` which can be used to export `eventId.Name`. When this option is set to `EventNameExportMode.ExportAsField`, GenevaLogExporter would export `eventId.Name` as a value for the field `env_name`.
```csharp
public class Program
{
public static void Main()
{
using var loggerFactory = LoggerFactory.Create(builder =>
{
builder.AddOpenTelemetry(options =>
{
options.AddGenevaLogExporter(options =>
{
options.ConnectionString = "EtwSession=OpenTelemetry;";
});
});
});
// Creates a logger with the Category name as "Program"
// GenevaExporter exports Category name under the column `name`
var logger = loggerFactory.CreateLogger<Program>();
logger.LogInformation(new EventId(100, "CustomEventName"), "Hello from log with EventId {food} …
```
> [Exporter.Geneva] Update GenevaLogExporter to export eventName

- src/OpenTelemetry.Contrib.Instrumentation.AWS/Implementation/AWSTracingPipelineCustomizer.cs
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/Tools/TestAmazonDynamoDBClient.cs
Allow any type in `AmazonServiceClient` hierarchy to be instrumented rather than just direct subtypes.
> Allow subtypes of default AWS service clients to be instrumented

- src/OpenTelemetry.Extensions.AzureMonitor/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.AzureMonitor/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.AzureMonitor/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.AzureMonitor/ApplicationInsightsSampler.cs
- src/OpenTelemetry.Extensions.AzureMonitor/ApplicationInsightsSamplerOptions.cs
- src/OpenTelemetry.Extensions.AzureMonitor/CHANGELOG.md
- test/OpenTelemetry.Extensions.AzureMonitor.Tests/ApplicationInsightsSamplerTests.cs
Fixes #.
This PR updates the `ApplicationInsightsSampler` constructor to accept an `ApplicationInsightsSamplerOptions` object instead of a float sampling ratio and introduces the `ApplicationInsightsSamplerOptions` class for providing Dependency Injection support for the sampler configuration.
```C#
.SetSampler(sp =>
{
var options = sp.GetRequiredService<IOptionsMonitor<ApplicationInsightsSamplerOptions>>().Get(Options.DefaultName);
return new ApplicationInsightsSampler(options);
})
builder.Services.Configure<ApplicationInsightsSamplerOptions>(options => { options.SamplingRatio = 1.0F; });
```
> [AzureMonitor] Add ApplicationInsightsSamplerOptions to improve Dependency Injection support

- .github/component_owners.yml
- Add @atshaw43 as a co-owner for AWS components.
- Remove @lupengamzn as he isn't on the project anymore.
> Add atshaw43 as AWS components co-owner

- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
Small trivial update. Fixes #1174.
Change variable used to index result string.
> Fix indexing issue in GetSanitizedCategoryName

- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentation.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
Fixes N/A.
Remove calls Activity.SetStatus(Unset)
It is probably leftover from older OTel SDK/API or older DiagnosticSource package.
> [Instrumentation.MySqlData,Instrumentation.StackExchangeRedis] Avoid SetStatus(Unset)

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
I was testing the Geneva TldExporter locally (it produces very nice info into the EventSource) and I noticed the spanId value was too long and the same as traceId, so I looked in the code and noticed it was assigning the wrong property to the field.
> Assign correct value to ext_dt_spanId in Tld Geneva exporter

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/OpenTelemetry.Instrumentation.Hangfire.Tests.csproj
Support Hangfire.Core >=1.7 and <1.9
> [Instrumentation.Hangfire] Support Hangfire 1.8

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisConnectionInstrumentation.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisInstrumentation.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
Following up on https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1193#discussion_r1201616561
* Append the name of the options (when used) to the background thread responsible for draining Redis profiling sessions.
> [redis] Append options name to the background thread

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
Relates to #1207
* Switch CHANGELOG for Redis from `1.0.0-rc11` to `1.0.0-rc9.9` because `rc11` doesn't resolve correctly with all the previous ~mistakes~ releases 🤣
> [redis] Switch CHANGELOG to use version rc9.9

- src/OpenTelemetry.Exporter.Geneva/README.md
Based on reading the code and talking with the authors inside of Microsoft, CustomFields is expected to have different behavior when set to null vs. non-null.
Capture this distinction in the README.
> [Geneva.Logs] Refine CustomFields documentation

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
This is to avoid confusion and make it easy for users to understand what version of core packages this would work with.
- Update CHANGELOG for 1.4.0 release
> [Instrumentation.Runtime] Update CHANGELOG for 1.4.0 release

- examples/InfluxDB/Examples.InfluxDB/Examples.InfluxDB.csproj
Fix NU1604 for Examples.InfluxDB
RuntimeInstrumentationPkgVer is not defined
> Fix NU1604 for Examples.InfluxDB

- build/Common.props
- examples/AspNet/Examples.AspNet.csproj
- examples/process-instrumentation/process-instrumentation.csproj
- examples/runtime-instrumentation/runtime-instrumentation.csproj
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/CHANGELOG.md
- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Cassandra/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
- test/OpenTelemetry.Extensions.Enrichment.Tests/OpenTelemetry.Extensions.Enrichment.Tests.csproj
Fixes N/A
Bumps OpenTelemetry API/SDK for most packages.
Exceptions, should be handled separately:
* OpenTelemetry.Exporter.Geneva - relays on exemplars which is temporary unavailable
* OpenTelemetry.Exporter.OneCollector - tests relays on private/internals fields which are no longer available in 1.5.0
* OpenTelemetry.Extensions - using obsolete API + failing tests after upgrade, reason: https://github.com/open-telemetry/opentelemetry-dotnet/pull/4334
> Bump OpenTelemetry to 1.5.0

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
Fixes #.
Releases with OTel SDK/API 1.5.0 for packages used by Automatic Instrumentation
Versioning - just bumping last version (as all of them are not stable yet).
Please let me know, if I should go with 1.5.0-[alpha|beta|rc].1
> Releases with OTel SDK/API 1.5.0

- test/OpenTelemetry.Sampler.AWS.Tests/TestAWSXRayRemoteSampler.cs
- Skip a [flaky unit test](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/5217733841/jobs/9417858726?pr=1228) that keeps delaying merging of PRs
> [Sampler.AWS] Skip flaky unit test

- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/EtwDataTransport.cs
- Remove `EventSource` attribute from `EtwDataTransport` as it was only required for older targets (e.g net452). The `EventSource` ctor overload which takes the sourceName as a parameter is available on all the supported targets now
- Minor refactoring
> [Exporter.Geneva] Remove EventSource attribute from EtwDataTransport

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- Update OTel SDK version to 1.5.0
- Remove Exemplars support
> [Exporter.Geneva] Update OTel SDK version to 1.5.0 and remove Exemplars support

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Fixes #1163.
Add a new metric for total paused duration in GC `process.runtime.dotnet.gc.duration` with data from [GC.GetTotalPauseDuration Method](https://learn.microsoft.com/en-us/dotnet/api/system.gc.gettotalpauseduration?view=net-7.0).
It is recommended over the `time-in-gc` EventCounter in the [Well-known EventCounters in .NET](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters).
The metrics would show in the output of [Prometheus Exporter HttpListener](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.Prometheus.HttpListener/README.md) (for how to set it up, follow [this getting-started guide](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started-prometheus-grafana)) like …
> [Instrumentation.Runtime] Add a metric for total paused duration in GC for .NET 7 and greater versions

- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBMetricsExporter.cs
- src/OpenTelemetry.Exporter.InfluxDB/PointDataExtensions.cs
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV1.cs
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV2.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/InfluxDBMetricsExporterTests.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/MeterProviderBuilderTestExtensions.cs
Fixes #1206.
This PR introduces support for Resource attributes in OpenTelemetry.Exporter.InfluxDB. With this change, resource attributes will now be passed as InfluxDB tags.
~~* [ ] Design discussion issue #~~
~~* [ ] Changes in public API reviewed~~
> [Exporter.InfluxDB] Add support for Resources attributes

- README.md
Emeritus might change company, there is no expectation that anyone will be actively tracking/maintaining the info here.
> Remove company info from emeritus

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs
Mitigates https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1024.
Below is an example of when the deadlock can occur:
|                 | Thread 1 | Thread 2 |  locks acquired at this timestamp|
| ---------- | ----------|-----------|-----------|
| Time **↓**| call ctor of `EventCountersMetrics` | | |
|                 | [lock](https://github.com/Yun-Ting/opentelemetry-dotnet-contrib/blob/3e2015dd2a2884b1c89e596bcb53d599b6f961f4/src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs#L50C1-L50C40) `preInitEventSources` |  | lock on `preInitEventSources` object by thread 1|
|                | iterate through the HashSet of `EventSources` [AND enable](https://github.com/Yun-Ting/opentelemetry-dotnet-contrib/blob/3e2015dd2a2884b1c89e596bcb53d599b6f961f4/src/ …
> [EventCounters] fix deadlock

- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
Release EventCounters instrumentation version 1.5.1-alpha.1
@open-telemetry/dotnet-contrib-maintainers 
> [Instrumentation.EventCounters] Release EventCounters instrumentation version 1.5.1-alpha.1

- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaHttpUtils.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/Implementation/AWSLambdaHttpUtilsTests.cs
**Problem**
For AWS Lambda functions (V1 only) invoked via HTTP depending on setup there might be different sources for setting http.method and http.target: original request (APIGatewayProxyRequest) and request context (ProxyRequestContext) defined inside of the request.
**Fix**
Consider Path and HttpMethod properties of APIGatewayProxyRequest and APIGatewayProxyRequest.ProxyRequestContext when setting http.target and http.method. Request context should be prioritised over request while setting http.target and http.method
> [OpenTelemetry.Instrumentation.AWSLambda]: consider two sources when setting http.method and http.target: original request and request context.

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
Compare with #1238 which removed Exemplar support
- Update OTel SDK version to `1.6.0-alpha.1`
- Add back Exemplar support
- Suppress warnings about `LogRecord.LogLevel` being Obsolete
> [Exporter.Geneva] Add Exemplar support back

- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/Implementation/AWSMessagingUtilsTests.cs
Closes #1270 (alternative to that PR).
Related to a similar change in the XRay dependency: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1092
Quoting the CHANGELOG:
* Add explicit dependency on Newtonsoft.Json, upgrading the mimimum version.
This resolves a warning that some dependency analyzers may produce where this
package would transitively depend on a vulnerable version of Newtonsoft.Json
through [Amazon.Lambda.APIGatewayEvents][].
This also avoids a potential issue where the instrumentation would try to call
a Newtonsoft.Json function when no other package nor the app itself depends on
Newtonsoft.Json, since the transitive dependency would be ignored unless using
application were compiled against a TargetFramework older than Core 3.1. …
> Instrumentation.AWSLambda: Upgrade & explicitly depend on Newtonsoft.Json

- .github/workflows/ci-Instrumentation.Process.yml
- .github/workflows/ci-md.yml
- .github/workflows/ci.yml
- .github/workflows/integration-md.yml
- .github/workflows/integration.yml
- build/docker-compose.netcoreapp3.1.yml
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.GrpcCore/ClientTracingInterceptorOptions.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/FoobarService.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreClientInterceptorTests.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreServerInterceptorTests.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/InterceptorActivityListener.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/OpenTelemetry.Instrumentation.GrpcCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/proto/foobar.proto
Towards #1031
* update testing framework in Instrumentation.GrpcCore from netcoreapp3.1 to net6.0
* after changes test was failing due to https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/default-activityidformat-changed
* Bum `Grpc` package in test to latest released. It is currently obsolete, unmaintained package so update to the latest release seems to be reasonable
* mitigation of Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory 
* Drop netcoreapp3.1 from CI
* Minor opportunistic changes
As part of working on this `redis-test (netcoreapp3.1)` was removed from required …
> Drop netcoreapp3.1 from CI & update testing framework in Instrumentation.GrpcCore to net6.0

- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.ResourceDetectors.AWS/CHANGELOG.md
Towards #1268
Prerequisite to release another AWS packages.
Please check changes in changelog for details.
The question is if it should be released as 1.3.0-beta.1 (as we changed the package name) or it has to be major release (2.0.0-beta.1) for Extension package.
My recommendation is to use the same version for ResourceDetectors as it was extracted from the old package.
@srprash, @Oberon00, @rypdal, please let me know what do you think about versioning.
> [Extensions.AWS, ResourceDetectors.AWS] Release 1.3.0-beta.1

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
Towards #1268
Update dependency to OpenTelemetry.Extensions.AWS
> [Instrumentation.AWS] Update dependency to OpenTelemetry.Extensions.AWS

- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaResourceDetector.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaUtils.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
- src/OpenTelemetry.Instrumentation.AWSLambda/TracerProviderBuilderExtensions.cs
Towards #1268
Update dependency to OpenTelemetry.Extensions.AWS
> [Instrumentation.AWSLambda] Update dependency to OpenTelemetry.Extensions.AWS

- build/Common.nonprod.props
Bump coverlet.collector from 3.2.0 to 6.0.0
Huge version bump due to changes in versioning strategy https://github.com/coverlet-coverage/coverlet/releases/tag/v6.0.0
> Bump coverlet.collector from 3.2.0 to 6.0.0

- src/OpenTelemetry.Exporter.Stackdriver/README.md
Update documentation for #1263.
[Exporter.Stackdriver] Documentation - remove reference to metric exporterorter
which is not implemented
> [Exporter.Stackdriver] Documentation - remove reference to metric exporter

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/LogRecordCommonSchemaJsonSerializer.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/LogRecordCommonSchemaJsonSerializerTests.cs
* Adds support for `LogRecord.Body` if `{OriginalFormat}` key is not found
* Adds support for sending formatted message if it is present and differs from the body
> [OneCollectorExporter] Add LogRecord.Body support

- .github/workflows/ci-aot.yml
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
This ensures that the OpenTelemetry.Instrumentation.EventCounters library stays AOT-compatible.
Contributes to https://github.com/open-telemetry/opentelemetry-dotnet/issues/3429
cc @Yun-Ting
> Add EventCounters to AotCompatibility.Test

- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryBindingElementForHttpTests.cs
Fixes #1325
Increase reliability of WCF HTTP tests - do not assume the order of the stopped activities
> Increase reliability of WCF HTTP tests

- src/OpenTelemetry.Exporter.Geneva/Common.GenevaExporter.props
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/OpenTelemetry.Exporter.Geneva.Benchmark.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- Add a build time constant to check if experimental features should be set or not
- This helps in avoiding adding/commenting out Exemplar related code for every stable release
> [Exporter.Geneva] Add build time constant for experimental features

- build/Common.props
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update OTel SDK version to 1.6.0-rc.1
> [Exporter.Geneva] Update OTel SDK version to 1.6.0-rc.1

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Release Runtime instrumentation version `1.5.1` to release the `process.runtime.dotnet.gc.duration` metric.
> [Instrumentation.Runtime] Release Runtime instrumentation version 1.5.1

- build/Common.props
- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Cassandra/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcCore/OpenTelemetry.Instrumentation.GrpcCore.csproj
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.AWS/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/CHANGELOG.md
Fixes N/A.
Bump OTel SDK/API to 1.6.0
Exporter.Geneva statys on 1.6.0-rc.1 as it depends on non-stable features.
* ~~[  ] Design discussion issue #~~
> Bump OTel SDK/API to 1.6.0

- .github/workflows/dotnet-format.yml
- build/Common.prod.props
- build/Common.props
- build/Common.targets
- examples/AspNet/App_Start/RouteConfig.cs
- examples/AspNet/Controllers/HomeController.cs
- examples/AspNet/Controllers/WeatherForecastController.cs
- examples/AspNet/Examples.AspNet.csproj
- examples/AspNet/Global.asax.cs
- examples/AspNet/Properties/AssemblyInfo.cs
- examples/AspNet/Properties/launchSettings.json
- examples/AspNet/Web.config
- examples/Directory.Build.props
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- src/OpenTelemetry.Instrumentation.EventCounters/OpenTelemetry.Instrumentation.EventCounters.csproj
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- src/OpenTelemetry.Instrumentation.Process/OpenTelemetry.Instrumentation.Process.csproj
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
- src/OpenTelemetry.PersistentStorage.Abstractions/OpenTelemetry.PersistentStorage.Abstractions.csproj
- src/OpenTelemetry.ResourceDetectors.Azure/OpenTelemetry.ResourceDetectors.Azure.csproj
- src/OpenTelemetry.Sampler.AWS/AWSXRaySamplerClient.cs
- src/Shared/ExceptionExtensions.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/OpenTelemetry.Exporter.InfluxDB.Tests.csproj
- test/OpenTelemetry.Exporter.OneCollector.Benchmarks/OpenTelemetry.Exporter.OneCollector.Benchmarks.csproj
- test/OpenTelemetry.Exporter.OneCollector.Tests/OpenTelemetry.Exporter.OneCollector.Tests.csproj
Fixes #1274
* Updates the `dotnet-format` ci workflow to use the SDK version
* Cleans up new warnings manifested by `dotnet format`
* Removes `EnableAnalysis` property as it is now globally enabled in common props
> [repo+ci] Use SDK dotnet format in CI

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Common.GenevaExporter.props
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- Update OTel SDK version to `1.6.0`
- Update CHANGELOG for 1.6.0 release
> [Exporter.Geneva] Update OTel SDK version and CHANGELOG for 1.6.0 release

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/LogRecordCommonSchemaJsonSerializer.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/LogRecordCommonSchemaJsonSerializerTests.cs
Fixes #1313
* Removes `ext.dt.traceFlags` because it isn't currently supported by OneCollector
> [onecollector] Remove ext.dt.traceFlags

- .github/workflows/ci-Exporter.OneCollector-Integration.yml
- build/Projects/OpenTelemetry.Exporter.OneCollector.proj
- opentelemetry-dotnet-contrib.sln
* Adds a new workflow for running OneCollector integration tests. Those tests are being added on #1347
The goal is simple: We have a secret defined `OTEL_ONECOLLECTOR_INSTRUMENTATION_KEY` to set as an environment variable of the same name when running the tests.
Turns out this is not super easy to do!
A workflow defined as...
```yaml
on:
pull_request:
```
...when opened from a fork does NOT see secrets.
There is a special trigger for this: [pull_request_target](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks).
But the problem with `pull_request_target` is, it runs on the targert repo, not the fork. That means the integration tests won't run with the code being PRed (which is what we want).
The reason …
> [OneCollector] Integration tests prep

- src/OpenTelemetry.Instrumentation.Hangfire/.publicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.Hangfire/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Hangfire/HangfireInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentationJobFilterAttribute.cs
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
- src/OpenTelemetry.Instrumentation.Hangfire/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/TestJob.cs
Towards #894
Nullable Hangfire.
Tests project already covered.
> Nullable Hangfire

- examples/grpc.core/Examples.GrpcCore.AspNetCore/Controllers/WeatherForecastController.cs
- examples/grpc.core/Examples.GrpcCore.AspNetCore/Examples.GrpcCore.AspNetCore.csproj
- examples/grpc.core/Examples.GrpcCore.AspNetCore/WeatherForecast.cs
- examples/owin/Controllers/TestController.cs
- examples/owin/Examples.Owin.csproj
- examples/wcf/client-core/Program.cs
- examples/wcf/client-netframework/Program.cs
- examples/wcf/shared/Examples.Wcf.Shared.csproj
- examples/wcf/shared/StatusRequest.cs
> Nullable examples

- src/OpenTelemetry.ResourceDetectors.Azure/AzureVmMetaDataRequestor.cs
Fixes #.
Adding a timeout to reduce start up time when the application is not running on Azure VM.
> [ResourceDetectors.Azure] Update AzureVmMetaDataRequestor [Add timeout for HttpClient]

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/ExtensionFieldInformation.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/ExtensionFieldInformationManager.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializationHelper.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializationState.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/CommonSchemaJsonSerializationHelperTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/CommonSchemaJsonSerializationStateTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/ExtensionFieldInformationManagerTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/LogRecordCommonSchemaJsonSerializerTests.cs
[These changes were originally part of #1327]
* Adds the utf8 encoded json to what is stored in the extension cache
* Adds a special case for IReadOnlyList<KeyValuePair<string, object?>> values in json serializer
* Use raw string literals for JSON in tests
* Improves the validation of extension fields to protect against invalid data
> [OneCollectorExporter] Perf improvements

- build/Common.nonprod.props
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- test/OpenTelemetry.Exporter.InfluxDB.Tests/OpenTelemetry.Exporter.InfluxDB.Tests.csproj
- test/OpenTelemetry.Exporter.Instana.Tests/OpenTelemetry.Exporter.Instana.Tests.csproj
- test/OpenTelemetry.Exporter.OneCollector.Tests/OpenTelemetry.Exporter.OneCollector.Tests.csproj
- test/OpenTelemetry.Exporter.Stackdriver.Tests/OpenTelemetry.Exporter.Stackdriver.Tests.csproj
- test/OpenTelemetry.Extensions.AWS.Tests/OpenTelemetry.Extensions.AWS.Tests.csproj
- test/OpenTelemetry.Extensions.Enrichment.Tests/OpenTelemetry.Extensions.Enrichment.Tests.csproj
- test/OpenTelemetry.Extensions.Tests/OpenTelemetry.Extensions.Tests.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/OpenTelemetry.Instrumentation.AWS.Tests.csproj
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/OpenTelemetry.Instrumentation.AWSLambda.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNet.Tests/OpenTelemetry.Instrumentation.AspNet.Tests.csproj
- test/OpenTelemetry.Instrumentation.Cassandra.Tests/OpenTelemetry.Instrumentation.Cassandra.Tests.csproj
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/OpenTelemetry.Instrumentation.EventCounters.Tests.csproj
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/OpenTelemetry.Instrumentation.GrpcCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/OpenTelemetry.Instrumentation.Hangfire.Tests.csproj
- test/OpenTelemetry.Instrumentation.Owin.Tests/OpenTelemetry.Instrumentation.Owin.Tests.csproj
- test/OpenTelemetry.Instrumentation.Process.Tests/OpenTelemetry.Instrumentation.Process.Tests.csproj
- test/OpenTelemetry.Instrumentation.Quartz.Tests/OpenTelemetry.Instrumentation.Quartz.Tests.csproj
- test/OpenTelemetry.Instrumentation.Runtime.Tests/OpenTelemetry.Instrumentation.Runtime.Tests.csproj
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests.csproj
- test/OpenTelemetry.Instrumentation.Wcf.Tests/OpenTelemetry.Instrumentation.Wcf.Tests.csproj
- test/OpenTelemetry.PersistentStorage.FileSystem.Tests/OpenTelemetry.PersistentStorage.FileSystem.Tests.csproj
- test/OpenTelemetry.ResourceDetectors.AWS.Tests/OpenTelemetry.ResourceDetectors.AWS.Tests.csproj
- test/OpenTelemetry.ResourceDetectors.Azure.Tests/OpenTelemetry.ResourceDetectors.Azure.Tests.csproj
- test/OpenTelemetry.ResourceDetectors.Container.Tests/OpenTelemetry.ResourceDetectors.Container.Tests.csproj
- test/OpenTelemetry.Sampler.AWS.Tests/OpenTelemetry.Sampler.AWS.Tests.csproj
Follow-up on this comment: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1355#discussion_r1329623925
* Moved the `xunit` references out of test project files and into the props
> [repo] Move xunit references for test projects into props

- .github/codecov.yml
- .github/workflows/ci-Exporter.Geneva.yml
- .github/workflows/ci.yml
- build/Projects/OpenTelemetry.Exporter.Geneva.proj
- opentelemetry-dotnet-contrib.sln
* Adds dedicated CI for `OpenTelemetry.Exporter.Geneva`
> [repo] Add dedicated CI for Geneva Exporter

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
Fixes #1186
Allow overriding the "name" field in the Geneva Log Exporter
This allows big codebases to be migrated to OpenTelemetry while still maintaining back-compatibility of the emitted logs
> Allow overriding the Part B "name" field value in GenevaLogExporter

- .github/codecov.yml
- .github/workflows/ci-Instrumentation.Wcf.yml
- .github/workflows/ci.yml
- .github/workflows/package-Instrumentation.Wcf.yml
- build/Projects/OpenTelemetry.Instrumentation.Wcf.proj
- opentelemetry-dotnet-contrib.sln
* Adds dedicated CI for the `OpenTelemetry.Instrumentation.Wcf` project.
> [repo] Add dedicated CI for WCF Instrumentation

- src/OpenTelemetry.Instrumentation.Owin/Implementation/DiagnosticsMiddleware.cs
Without the cast to double, precision of the HTTP server duration is lower.
* ~[ ] Appropriate `CHANGELOG.md` updated for non-trivial changes~
* ~[ ] Design discussion issue #~
* ~[ ] Changes in public API reviewed~
> Improve OWIN server metric precision

- .github/workflows/Component.BuildTest.yml
- .github/workflows/Component.Package.yml
- build/Projects/OpenTelemetry.Exporter.Geneva.proj
- build/Projects/OpenTelemetry.Exporter.OneCollector.proj
- build/Projects/OpenTelemetry.Instrumentation.AspNet.proj
- build/Projects/OpenTelemetry.Instrumentation.Owin.proj
- build/Projects/OpenTelemetry.Instrumentation.Process.proj
- build/Projects/OpenTelemetry.Instrumentation.StackExchangeRedis.proj
- build/Projects/OpenTelemetry.Instrumentation.Wcf.proj
- opentelemetry-dotnet-contrib.sln
Follow-up to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1386#issuecomment-1755893651
#1386 combined Instrumentation.AspNet + Instrumentation.AspNet.TelemetryHttpModule into the same CI & release workflows but only the tests for Instrumentation.AspNet were being run. This PR changes the workflows to use the project files which now have targets for testing.
> [repo] Use project files for tests in dedicated CI flows

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/ActivityHelperTest.cs
Fixes #1138.
This PR implements the fix suggested by @jdaigle.
I have tested this on an a .NET Framework 4.8 ASP MVC application I've been maintaining.
I ran into this issue trying to modify the span name to be prefixed by the http method as [recommended by the spec](<https://github.com/open-telemetry/semantic-conventions/blob/4040095eda0159e38edfe7084ed32d3077a6ffb0/docs/http/http-spans.md?plain=1#L70>). The problem I ran into was the `HttpInListener` overriding whatever changes the processor made to the span name.
It also seems odd to me that the activity is closed and *then* updated (through `HttpInListener.OnStopActivity`). I think there is a race condition with exporters here. I was able to trigger this by setting a breakpoint before `onRequestStoppedCallback` is called; sometimes …
> [Instrumentation.AspNet] Fix activity being closed before processing completes

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- Bump up version to `1.6.0-beta.1` similar to instrumentation packages from main repo
- Update CHANGELOG for `1.6.0-beta.1` release
> [Instrumentation.AspNet] Update CHANGELOG for 1.6.0-beta.1 release

- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBExporterExtensions.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBMetricsExporterOptions.cs
`InfluxDBExporterExtensions.AddInfluxDBMetricsExporter(MeterProviderBuilder, Action<InfluxDBMetricsExporterOptions>)` uses a `PeriodicExportingMetricReader` instance to pass the metrics to the InfluxDB exporter at an interval.  However, the extension method provides no means to make this interval user-configurable.
This PR introduces a new property, `MetricExportIntervalMilliseconds`, to `InfluxDBMetricsExporterOptions` to configure the said interval.  The property value is then passed as an argument to the `exportIntervalMilliseconds` parameter in the `PeriodicExportingMetricReader` constructor.
The default value for `InfluxDBMetricsExporterOptions.MetricExportIntervalMilliseconds` is set to 60000, matching the default that's specified with …
> Export metrics to InfluxDB at a configurable interval

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldTraceExporter.cs
- Update mapping for http tags based on the new semantic conventions
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/Shared/SemanticConventions.cs#L120-L121
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/Shared/SemanticConventions.cs#L126
> [Exporter.Geneva] Update mapping for http tags

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
[Instrumentation.Wcf] Release 1.0.0-rc.13
* Update OpenTelemetry SDK version to `1.6.0`.
([#1344](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1344))
* Fixed span hierarchy when hosted in ASP.NET
([#1342](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1342))
* **Breaking Change** `TelemetryClientMessageInspector` and `TelemetryDispatchMessageInspector`
changed from public to internal
([#1376](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1376))
* Added support for `IRequestSessionChannel` and `IDuplexChannel` channel shapes
([#1374](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1374))
Planned to adjust Automatic …
> [Instrumentation.Wcf] Release 1.0.0-rc.13

- .github/workflows/ci.yml
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisConnectionInstrumentation.cs
- src/Shared/PropertyFetcher.AOT.cs
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
- Add net6.0 target, so we can annotate the code correctly and use new APIs.
- Copy PropertyFetcher from open-telemetry/opentelemetry-dotnet which was made AOT compatible. Made a new shared version that other libraries can opt into using over time, so this change has no affect on other libraries.
- Add StackExchangeRedis to the AotCompatibility.TestApp.
- Address warnings to make the code work under AOT/trimmed.
Fix #1341
cc @Yun-Ting @utpilla @vitek-karas
> Fix AOT warnings in StackExchangeRedis

- examples/AspNet/Web.config
Fixes #1417.
Add missing binding redirect to web.config
> Add missing Binding Redirect for Examples.AspNet project

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
#1415 had an issue in it due to how the DynamicDependency attribute is written.
1. Referring to a nested type with `+` isn't correct in DynamicDependency attributes. You need to just use a normal `.`. The current code is producing a warning when using the .NET 8.0 SDK to publish for AOT. "warning IL2036: OpenTelemetry.Instrumentation.StackExchangeRedis.Implementation.RedisProfilerEntryToActivityConverter.<.cctor>g__GetCommandAndKey|5_3(PropertyFetcher`1<String>,Object,String&): Unresolved type 'StackExchange.Redis.RedisDatabase+ScriptEvalMessage' in 'DynamicDependencyAttribute'."
This wasn't caught in our CI because we use the .NET 7.0 SDK to publish, which doesn't catch this bug.
2. The "CommandAndKey" property isn't on the nested ScriptEvalMessage type, but instead a virtual on the base …
> Fix up Redis trimming annotations

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs
Fixes a bug introduced in #1388 as mentioned by @vishweshbankwar.
- Explicitly set the end duration of the activity before `onRequestStoppedCallback` is called.
- Updated tests to catch this in the future.
> [Instrumentation.AspNet] Fix metric http.server.duration always being zero

- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
Fixes #.
This is always `true`
```c#
Assert.True(activity.ActivityTraceFlags.HasFlag(ActivityTraceFlags.None));
```
This is a correct assertion
```c#
Assert.False(activity.ActivityTraceFlags.HasFlag(ActivityTraceFlags.Recorded));
```
> Fix ActivityTraceFlags assertion

- src/OpenTelemetry.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcCore/OpenTelemetry.Instrumentation.GrpcCore.csproj
Fixes https://github.com/advisories/GHSA-77rm-9x9h-xj3g - detected by .NET8 local update
Update minimal Google.Protobuf to 3.15.0
> [Instrumentation.GrpcCore] Update minimal Google.Protobuf to 3.15.0

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/OpenTelemetry.Instrumentation.AWS.Tests.csproj
Update the AWS .NET SDK dependencies for the OpenTelemetry.Instrumentation.AWS package. This is needed because the version that was previously had a max range cap of `3.6` but the SDK has been on version `3.7` since 2021. Without this change users are getting restore warnings whenever they are using an SDK versions released in the last 2 years.
For background purposes I'm a developer of the AWS .NET SDK.
> [Instrumentation.AWS] Update AWS SDK references

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
Requesting to release OpenTelemetry.Instrumentation.AWS. I need the change to continue some experimenting work I'm trying to do with the new .NET Aspire project with AWS and the AWS .NET SDK.
> Request to release OpenTelemetry.Instrumentation.AWS package

- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/LogExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/SerializationBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/TLDLogExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/TLDTraceExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/TraceExporterBenchmarks.cs
- Update Benchmark results
The benchmarks were run with an ETW listener running in parallel. This is done to measure the true cost of exporting telemetry.
> [Exporter.Geneva] Update Benchmark results

- test/OpenTelemetry.Instrumentation.Cassandra.Tests/OpenTelemetry.Instrumentation.Cassandra.Tests.csproj
Related to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1467
Remove the Moq library from the Instrumentation.Cassandra.Tests project.
- Removed Moq dependency
> Remove Moq from Instrumentation.Cassandra.Tests

- test/OpenTelemetry.Instrumentation.Wcf.Tests/OpenTelemetry.Instrumentation.Wcf.Tests.csproj
Related to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1467
Remove the Moq library from the Instrumentation.Wcf.Tests project.
- Removed Moq dependency
> Remove Moq from Instrumentation.Wcf.Tests

- test/OpenTelemetry.Instrumentation.Quartz.Tests/OpenTelemetry.Instrumentation.Quartz.Tests.csproj
- test/OpenTelemetry.Instrumentation.Quartz.Tests/QuartzDiagnosticListenerTests.cs
Related to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1467
Remove the Moq library from the Instrumentation.Quartz.Tests project.
- Updated unit tests
- Removed Moq dependency
> Remove Moq from Instrumentation.Quartz.Tests

- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests.csproj
Related to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1467
Remove the Moq library from the Instrumentation.ElasticsearchClient.Tests project.
- Updated unit tests
- Removed Moq dependency
> Remove Moq from Instrumentation.ElasticsearchClient.Tests

- src/OpenTelemetry.Exporter.InfluxDB/PointDataExtensions.cs
- src/OpenTelemetry.Exporter.Instana/OpenTelemetry.Exporter.Instana.csproj
- Fix errors introduced in #1486
> Fix build errors

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
Fixes #1500.
Temporarily downgrading the OTel dependency. The version will be restored after the instrumentation release.
> Hangfire: Downgrade OpenTelemetry.Api.ProviderBuilderExtensions to 1.6.0 to avoid MS.Extensions.* v8 dependencies

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
Update CHANGELOG for AspNet and AspNet.TelemetryHttpModule instrumentation to 1.7.0-beta.1.
- Followed pattern from previous release PR [here](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1427).
- Primary reason for requesting a release is to enable the currently unreleased Enrich() functionality tracked in this issue: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1226
> [Instrumentation.AspNet] Update CHANGELOG for 1.7.0-beta.1 release

- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
- Use `FrozenSet` and `FrozenDictionary` on .NET 8 target
When the keys are known beforehand, `FrozenSet` and `FrozenDictioanry` offer better performance than `HashSet` and `Dictionary`. Check this blog post for more details: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/#frozen-collections
I did some benchmarking for both Activity and Logs with seven tags/attributes and GenevaExporter configured to have three `CustomFields`. Every tag/attribute has to be looked up against a dictionary to find out if it matches a dedicated field or one of the user-provided custom fields. For Logs, there is also a lookup cost for prepopulated fields and Part A names.
The below benchmarks provide a **~20%** improvement in serialization performance for seven tags/attributes. The …
> [Exporter.Geneva] Perf improvement on .NET 8

- .github/ISSUE_TEMPLATE/comp_resourcedetectors_process.md
- .github/codecov.yml
- .github/component_owners.yml
- .github/workflows/ci.yml
- .github/workflows/package-ResourceDetectors.Process.yml
- build/Projects/OpenTelemetry.ResourceDetectors.Process.proj
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.ResourceDetectors.Process/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.ResourceDetectors.Process/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.ResourceDetectors.Process/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.ResourceDetectors.Process/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.ResourceDetectors.Process/AssemblyInfo.cs
- src/OpenTelemetry.ResourceDetectors.Process/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Process/OpenTelemetry.ResourceDetectors.Process.csproj
- src/OpenTelemetry.ResourceDetectors.Process/ProcessDetector.cs
- src/OpenTelemetry.ResourceDetectors.Process/ProcessSemanticConventions.cs
- src/OpenTelemetry.ResourceDetectors.Process/README.md
- src/OpenTelemetry.ResourceDetectors.ProcessRuntime/ProcessRuntimeDetector.cs
- src/OpenTelemetry.ResourceDetectors.ProcessRuntime/README.md
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
- test/OpenTelemetry.ResourceDetectors.Process.Tests/OpenTelemetry.ResourceDetectors.Process.Tests.csproj
- test/OpenTelemetry.ResourceDetectors.Process.Tests/ProcessDetectorTests.cs
Fixes N/A.
Initial implementation for `process.pid` detector from https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/process.md#process (this attribute is what I need for now).
The plan is to release shortly as alpha with reference to OTel 1.6.0.
Then create follow up `help-wanted` issue to extend it for another attributes and update OTel to 1.7.0.
Previous initial implementation of resource detector: #1449
You can expect one more similar, for https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/host.md, espiecially `host.name`.
> ResourceDetectors - Process

- .github/ISSUE_TEMPLATE/comp_resourcedetectors_host.md
- .github/codecov.yml
- .github/component_owners.yml
- .github/workflows/ci.yml
- .github/workflows/package-ResourceDetectors.Host.yml
- build/Projects/OpenTelemetry.ResourceDetectors.Host.proj
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.ResourceDetectors.Host/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.ResourceDetectors.Host/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.ResourceDetectors.Host/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.ResourceDetectors.Host/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.ResourceDetectors.Host/AssemblyInfo.cs
- src/OpenTelemetry.ResourceDetectors.Host/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Host/HostDetector.cs
- src/OpenTelemetry.ResourceDetectors.Host/HostSemanticConventions.cs
- src/OpenTelemetry.ResourceDetectors.Host/OpenTelemetry.ResourceDetectors.Host.csproj
- src/OpenTelemetry.ResourceDetectors.Host/README.md
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
- test/OpenTelemetry.ResourceDetectors.Host.Tests/HostDetectorTests.cs
- test/OpenTelemetry.ResourceDetectors.Host.Tests/OpenTelemetry.ResourceDetectors.Host.Tests.csproj
Fixes N/A
Initial implementation for `host.name` detector from https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/host.md (this attribute is what I need for now).
The plan is to release shortly as alpha with reference to OTel 1.6.0.
Then create follow up `help-wanted` issue to extend it for another attributes and update OTel to 1.7.0.
Similar pr for process: #1506
> ResourceDetectors - Host

- src/OpenTelemetry.ResourceDetectors.Host/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Host/OpenTelemetry.ResourceDetectors.Host.csproj
- src/OpenTelemetry.ResourceDetectors.Process/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Process/OpenTelemetry.ResourceDetectors.Process.csproj
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1507#discussion_r1433243308 and https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1506#discussion_r1433245459
Bump OTel to 1.7.0 for ResourceDetectors Host and Process
> Bump OTel to 1.7.0 for ResourceDetectors Host and Process

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Host/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Process/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.ProcessRuntime/CHANGELOG.md
Towards https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3204
Request releases with 1.7.0 for packages used by OTel Auto.
New versions based on the latest versioning. Only exception is for Quartz changed from alpha to beta.
> Releases with OTel 1.7.0

- src/OpenTelemetry.Exporter.Geneva/README.md
There is no need to explicitly install the latest version of Microsoft.Extensions.Logging since it is covered by the OpenTelemetry SDK https://github.com/open-telemetry/opentelemetry-dotnet/pull/4920.
> Minor docs improvement for Geneva Exporter

- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInMetricsListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationMetrics.cs
- src/OpenTelemetry.Instrumentation.Owin/README.md
Fixes #.
Update metric name for AspNet Instrumentation
> ASP.NET and OWIN Instrumentations - fix description for `http.server.request.duration` metric

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/OpenTelemetry.Instrumentation.AWS.Tests.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestRequest.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestRequestContext.cs
Bump AWS SDKs to 3.7.300 for native AoT support.
Without this change, there are two AoT warnings when building the project from the AWS.Core library.
```console
D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\Internal\_netstandard\TypeWrapper.netstandard.cs(184): Trim analysis error IL2080: Amazon.Util.Internal.TypeFactory.TypeInfoWrapper.GetMethod(String,ITypeInfo[]): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,Type[])'. The field 'Amazon.Util.Internal.TypeFactory.AbstractTypeInfo._type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. …
```
> [Instrumentation.AWS] Bump minimal AWS SDKs to 3.7.300

- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSMessagingUtils.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
- src/OpenTelemetry.Instrumentation.AWSLambda/SourceGenerationContext.cs
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
- Fixes #1523.
- Depends on #1545.
Make OpenTelemetry.Instrumentation.AWSLambda AoT compatible by:
- Using System.Text.Json to deserialize SNS messages
- Updating to Amazon.Lambda packages that support native AoT.
> [Instrumentation.AWSLambda] Fix AoT warnings

- src/OpenTelemetry.Instrumentation.AWS/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.AWS/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
Fixes #1543.
- Add `net6.0` TFM and fix nullability warnings.
- Resolve native AoT warning.
- Mark `AWSTracingPipelineHandler` as `sealed` (e.g. #1510).
- Fix `IDE0090` suggestions.
> [Instrumentation.AWS] Support .NET 6 and resolve AoT warning

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.AWS/CHANGELOG.md
Fixes #1523, #1543.
Release native AoT fixes for:
- OpenTelemetry.Instrumentation.AWS - #1542, #1547
- OpenTelemetry.Instrumentation.AWSLambda - #1545, #1544
- OpenTelemetry.ResourceDetectors.AWS - #1541
/cc @open-telemetry/dotnet-contrib-maintainers
> Release native AoT fixes for AWS packages

- .github/workflows/ci.yml
- .github/workflows/markdownlint.yml
* Bump AurorNZ/paths-filter (https://github.com/open-telemetry/opentelemetry-dotnet/pull/5288)
* markdownlint tweaks (https://github.com/open-telemetry/opentelemetry-dotnet/pull/5281)
* Include .targets & .props files in "build" filter and include .csproj files in "code" filter (don't recall exactly when those changes were made)
> [repo-ci] Sync-up with changes made in the main repo

- src/OpenTelemetry.ResourceDetectors.Host/HostDetector.cs
- src/OpenTelemetry.ResourceDetectors.Host/HostResourceEventSource.cs
- src/OpenTelemetry.ResourceDetectors.Host/OpenTelemetry.ResourceDetectors.Host.csproj
Fixes #1514.
[ResourceDetector.Host] Log exception when cannot detect host.name
* ~~[ ] Appropriate `CHANGELOG.md` updated for non-trivial changes~~ I would skip this in changelog.
> [ResourceDetector.Host] Log exception when cannot detect host.name

- src/OpenTelemetry.ResourceDetectors.AWS/AWSEC2ResourceDetector.cs
- src/OpenTelemetry.ResourceDetectors.AWS/AWSECSResourceDetector.cs
- src/OpenTelemetry.ResourceDetectors.AWS/AWSSemanticConventions.cs
- src/OpenTelemetry.ResourceDetectors.AWS/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.AWS/README.md
- test/OpenTelemetry.ResourceDetectors.AWS.Tests/AWSEC2ResourceDetectorTests.cs
- test/OpenTelemetry.ResourceDetectors.AWS.Tests/AWSECSResourceDetectorTests.cs
Implement support for the following resource attributes in the AWS ECS detector when using the metadata endpoint v4:
* cloud.account.id
* cloud.availability_zone
* cloud.region
Also, fix mispelling of the AWSSemanticConventions.AttributeCloudAvailableZone to AWSSemanticConventions.AttributeCloudAvailabilityZone
> [ResourceDetectors.AWS] Implement support for some cloud.* attributes in AWS ECS detector

- .github/workflows/Component.BuildTest.yml
- .github/workflows/ci.yml
Applying what was done [in the main repo](https://github.com/open-telemetry/opentelemetry-dotnet/pull/5294) to contrib.
> Bump codecov/codecov-action from 3.1.5 to 4.0.1

- .github/workflows/verifyaotcompat.yml
- build/test-aot-compatibility.ps1
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
- Support the AoT compatibility script being run locally on Windows.
- Fix AoT test script not failing for IL compiler errors, only warnings.
- Fix AoT test script not failing if `dotnet publish` fails.
- .NET 8 supports native AoT publishing on macOS, so remove condition.
Found while looking into an app of mine is getting trim warnings from OpenTelemetry.Instrumentation.AWS to see if they were easy to fix.
> Fix native AoT test scripts

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- src/Shared/SpanAttributeConstants.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
Similar changes to https://github.com/open-telemetry/opentelemetry-dotnet/pull/5301
[Instrumentation.EntityFrameworkCore] Stop emitting `db.statement_type` attribute
> [Instrumentation.EntityFrameworkCore] Stop emitting db.statement_type attribute

- .github/workflows/codeql-analysis.yml
- examples/wcf/server-aspnetframework/Web.Release.config
- opentelemetry-dotnet-contrib.proj
* Switches CodeQL workflow to build only the pack projects and in `Release` configuration.
This should clear these security issues:
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/8
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/9
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/12
> [repo] CodeQL workflow tweaks

- examples/AspNet/Views/Web.config
- examples/AspNet/Web.config
- examples/wcf/server-aspnetframework/Web.config
Follow-up to #1581
* Fix security warnings from web.configs in aspnet example apps.
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/10
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/4
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/7
* https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/11
> [aspnet-examples] Fix security warnings coming from config files

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
Fixes #1579.
Releases `OpenTelemetry.Exporter.Stackdriver` 1.0.0-beta.5
> [OpenTelemetry.Exporter.Stackdriver] Release 1.0.0-beta.5 (#1579)

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSPropagatorPipelineHandler.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSServiceHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSServiceType.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineCustomizer.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/SnsRequestContextHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/SqsRequestContextHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Implementation/RequestContextHelperTests.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Implementation/TestsHelper.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestRequest.cs
Fixes #1492 
A recent change to the AWS SDK implementation of SQS client changes wireline protocol from XML to Json.  This causes the SDK's internal request pipeline to behave differently, causing `AWSTracingPipelineHandler` to no longer be able to manipulate `SendMessageRequest.MessageAttributes` after the Marshalling step has been completed.  
This change moves `AWSTracingPipelineHandler` to run before Marshalling (ie Serialization) so that Open Telemetry headers can be correctly injected.
Injecting propagation context into outgoing requests have been moved to a new handler, `AWSPropagatorPipelineHandler`, which runs later in the SDK request pipeline.
Moving `AWSTracingPipelineHandler` ahead in the AWS SDK Pipeline made it necessary to also tweak `AWSServiceHelper` to use …
> bugfix: AWS SQS MD5 Hash Mismatch

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
- src/OpenTelemetry.Exporter.Instana/OpenTelemetry.Exporter.Instana.csproj
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
- src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/OpenTelemetry.Instrumentation.ElasticsearchClient.csproj
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/OpenTelemetry.Instrumentation.EntityFrameworkCore.csproj
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- src/OpenTelemetry.Instrumentation.Quartz/OpenTelemetry.Instrumentation.Quartz.csproj
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
- src/OpenTelemetry.PersistentStorage.Abstractions/OpenTelemetry.PersistentStorage.Abstractions.csproj
- src/OpenTelemetry.PersistentStorage.FileSystem/OpenTelemetry.PersistentStorage.FileSystem.csproj
- src/OpenTelemetry.ResourceDetectors.AWS/OpenTelemetry.ResourceDetectors.AWS.csproj
- src/OpenTelemetry.ResourceDetectors.Container/OpenTelemetry.ResourceDetectors.Container.csproj
- src/OpenTelemetry.ResourceDetectors.Host/OpenTelemetry.ResourceDetectors.Host.csproj
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/OpenTelemetry.Instrumentation.AWSLambda.Tests.csproj
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/OpenTelemetry.Instrumentation.EventCounters.Tests.csproj
- test/OpenTelemetry.Instrumentation.Quartz.Tests/OpenTelemetry.Instrumentation.Quartz.Tests.csproj
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1430#discussion_r1389874340
Drop most of the Shared properties.
The only exception if for `IncludeSharedSpanHelper`. There are two independent copies of similar files. I have a plan to solve it in follow up pr.
> Cleanup shared references

- .github/component_owners.yml
- Add @ppittle as a co-owner for AWS components.
> Add ppittle as AWS component co-owner

- src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
- src/OpenTelemetry.Instrumentation.Quartz/OpenTelemetry.Instrumentation.Quartz.csproj
- src/Shared/PropertyFetcher.AOT.cs
Towards #1416.
[Instrumentation.AspNet, Instrumentation.Quartz] Use new PropertyFetcher
Leftwovers: WCF and EFCore packages. New version does not contain Fetch method, only TryFetch.
> [Instrumentation.AspNet, Instrumentation.Quartz] Use new PropertyFetcher

- src/OpenTelemetry.Instrumentation.AspNet/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentation.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetTraceInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.AspNet/TracerProviderBuilderExtensions.cs
Propagate changes from https://github.com/open-telemetry/opentelemetry-dotnet/pull/5285
[Instrumentation.AspNet] Rename options class to AspNetTraceInstrumentationOptions
> [Instrumentation.AspNet] Rename options class to AspNetTraceInstrumentationOptions

- src/OpenTelemetry.ResourceDetectors.Process/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Process/ProcessDetector.cs
- src/OpenTelemetry.ResourceDetectors.Process/ProcessSemanticConventions.cs
- src/OpenTelemetry.ResourceDetectors.Process/README.md
- test/OpenTelemetry.ResourceDetectors.Process.Tests/ProcessDetectorTests.cs
Towards: #1515
[ResourceDetector.Process] support `process.owner` attribute
> [ResourceDetector.Process] support process.owner attribute

- src/OpenTelemetry.Instrumentation.Owin/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.Owin/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Owin/Implementation/DiagnosticsMiddleware.cs
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationActivitySource.cs
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- src/OpenTelemetry.Instrumentation.Owin/OwinInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Owin/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/Controllers/TestController.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/DiagnosticsMiddlewareTests.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/OpenTelemetry.Instrumentation.Owin.Tests.csproj
Towards #894
[Instrumentation.Owin] Nullable
> [Instrumentation.Owin] Nullable

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.PersistentStorage.Abstractions/AssemblyInfo.cs
- src/OpenTelemetry.PersistentStorage.FileSystem/CHANGELOG.md
- src/OpenTelemetry.PersistentStorage.FileSystem/PersistentStorageEventSource.cs
- test/OpenTelemetry.PersistentStorage.Abstractions.Tests/EventSourceTests.cs
- test/OpenTelemetry.PersistentStorage.Abstractions.Tests/OpenTelemetry.PersistentStorage.Abstractions.Tests.csproj
- test/OpenTelemetry.PersistentStorage.FileSystem.Tests/EventSourceTests.cs
Same as https://github.com/open-telemetry/opentelemetry-dotnet/pull/5451
This PR fixes a bug in the `PersistentStorageEventSource` class. 
```
System.FormatException
HResult=0x80131537
Message=Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Source=System.Private.CoreLib
StackTrace:
at System.ThrowHelper.ThrowFormatIndexOutOfRange()
at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
at System.String.Format(IFormatProvider provider, String format, Object[] args)
at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.OpenTelemetryEventListener.OnEventWritten(EventWrittenEventArgs …
```
> [PersistantStorage] fix event source throws `System.FormatException`

- examples/redis/Examples.StackExchangeRedis/Examples.StackExchangeRedis.csproj
- examples/redis/Examples.StackExchangeRedis/Program.cs
- examples/redis/Examples.StackExchangeRedis/README.md
Fixes #1530.
* Bugfix - d460d0c1c8e7532a119e0d0eee993cd81ac4509c - update Console exporter. There were a conflict with newer OTel referenced by Redis instrumentation package.
* Update .NET from 6 to 8
* Use top-level statement to reduce code [consider to review without white characters]
* Update output based on local execution
* EDIT: Console pinned to `$(OpenTelemetryCoreLatestVersion)` to avoid such issues in the future.
> [Instrumentation.Redis] Fix and modernize example

- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInMetricsListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/RequestDataHelper.cs
- src/Shared/SemanticConventions.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/RequestDataHelperTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/RouteTestHelper.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/TestHttpWorkerRequest.cs
Fixes N/A
Span attributes based on [HTTP semantic convention v1.24.0](https://github.com/open-telemetry/semantic-conventions/blob/v1.24.0/docs/http/http-spans.md) - Common and Server part sections.
Span names:
Common part
Server part:
Consider to review commits separately.
> [Instrumentation.AspNet] Spans - semantic convention v1.24.0

- build/Common.props
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/AWSLambdaWrapperTests.cs
Handles major release of https://github.com/adamralph/minver/blob/main/CHANGELOG.md#500
Bump MinVer to 5.0.0 - itnernal package.
Breaking changes seems to be no bad impact on OTel packages.~
Upgraded in AutoInstrumentaiton repo some time ago. No issues so far.
> Bump MinVer to 5.0.0

- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
Towards #1585
Support for Gauge instruments and refactoring to use common method for serializing datapoints.
> [Exporter.Geneva][otlp protobuf] Add support for Gauge

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.Instana/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Cassandra/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.PersistentStorage.Abstractions/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.AWS/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Host/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Process/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.ProcessRuntime/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/CHANGELOG.md
> Bump OpenTelemetry to 1.8.0

- src/OpenTelemetry.ResourceDetectors.Host/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Host/HostDetector.cs
- src/OpenTelemetry.ResourceDetectors.Host/HostSemanticConventions.cs
- src/OpenTelemetry.ResourceDetectors.Host/README.md
- test/OpenTelemetry.ResourceDetectors.Host.Tests/HostDetectorTests.cs
- test/OpenTelemetry.ResourceDetectors.Host.Tests/OpenTelemetry.ResourceDetectors.Host.Tests.csproj
- test/OpenTelemetry.ResourceDetectors.Host.Tests/Samples/etc_machineid
- test/OpenTelemetry.ResourceDetectors.Host.Tests/Samples/etc_var_dbus_machineid
Fixes #1630 
Adds support for setting `host.id` on Linux, MacOS, and Windows when running outside a container.
> [ResourceDetector.Host] Add host.id for non-containerized systems

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/ProcessMetrics.cs
- src/OpenTelemetry.Instrumentation.Process/README.md
- test/OpenTelemetry.Instrumentation.Process.Tests/ProcessMetricsTests.cs
Fixes #1638.
* Following changes related to [Semantic Convention v1.25.0](https://github.com/open-telemetry/semantic-conventions/blob/v1.25.0/docs/system/process-metrics.md)
* `process.cpu.time` metric attribute renamed from `state` to `process.cpu.state`,
* Metric descriptions fixed for `process.memory.usage` and `process.memory.virtual`,
* Metric `process.threads` renamed to `process.thread.count`
(its unit changed from `{threads}` to `{thread}`.
`process.cpu.count` is not part of the semantic convention (and it never was). It is still produced.
Also not all metrics defined by sem.conv. are covered.
> [Instrumentation.Process] Adjust metrics and attributes to Sem. Conv. 1.25.0

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.AspNet/AspNetTraceInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/AspNetInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/DiagnosticsMiddleware.cs
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- src/OpenTelemetry.Instrumentation.Owin/OwinInstrumentationOptions.cs
- src/Shared/RedactionHelper.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/DiagnosticsMiddlewareTests.cs
Fixes #.
Propagating changes from https://github.com/open-telemetry/opentelemetry-dotnet/pull/5532
> [Instrumentation.AspNet][Instrumentation.Owin] Redact query parameters

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ActivityExtensions.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/ActivityExtensionsTest.cs
Fixes #1622.
The fix also slightly minimizes allocations: avoids allocating a dictionary class instance.
> [Exporter.Stackdriver] Fixes the case when Activity/ActivityLink has several Tags with the same key

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationMetrics.cs
Fixes #1654.
Made both the Meter and Histogram singletons
> [Instrumentation.OWIN] Bugfix - make Meter and Histogram as a singletons

- src/OpenTelemetry.Exporter.Geneva/Internal/ConnectionStringBuilder.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
Towards #1585 
Renaming `PrivatePreviewOtlpProtobufMetricExporter` to `PrivatePreviewEnableOtlpProtobufEncoding`
> [Exporter.Geneva][Otlp protobuf] Rename private preview option

- src/Shared/ActivityInstrumentationHelper.cs
Towards https://github.com/open-telemetry/opentelemetry-dotnet/issues/5526
Sync Shared/ActivityInstrumentationHelper
based on https://github.com/open-telemetry/opentelemetry-dotnet/tree/89aa7a47ab070dda5a6eb470c352293cd366425c
Needed for SqlClient Instrumentation. Related to AOT compilation stuff.
> Sync Shared/ActivityInstrumentationHelper

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/Implementation/ElasticsearchRequestPipelineDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Quartz/Implementation/QuartzDiagnosticListener.cs
- src/Shared/DiagnosticSourceListener.cs
- src/Shared/DiagnosticSourceSubscriber.cs
- src/Shared/ListenerHandler.cs
Towards https://github.com/open-telemetry/opentelemetry-dotnet/issues/5526
Sync Shared listeners
based on based on https://github.com/open-telemetry/opentelemetry-dotnet/tree/89aa7a47ab070dda5a6eb470c352293cd366425c
Changes mostly related to https://github.com/open-telemetry/opentelemetry-dotnet/pull/3691
> Sync Shared listeners

- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/TlvMetricExporter.cs
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
Towards #1585 
Moving the disable logic to common place so that it can be used for both tlv and otlp protobuf format.
> Disable metric name validation for otlp format

- .github/workflows/ci.yml
- build/Common.props
- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/OneCollectorExporterEventSource.cs
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
Make OpenTelemetry.Exporter.OneCollector compatible with native AOT.
- Need to use the Microsoft.Extensions.Configuration.Binder source generator to solve 2 warnings. Need to reference the 8.0.1 version to get the latest updated to the source generator.
> [OneCollectorExporter] Resolve AOT warnings in OpenTelemetry.Exporter.OneCollector

- src/OpenTelemetry.Exporter.OneCollector/.publicApi/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.OneCollector/.publicApi/PublicAPI.Unshipped.txt
Relates to #1412
* Moves things shipped stable in `OneCollectorExporter` `1.6.0` release to shipped public api file
> [OneCollector] Update public api files for things released stable in 1.6.0

- src/OpenTelemetry.Sampler.AWS/AWSXRayRemoteSampler.cs
- src/OpenTelemetry.Sampler.AWS/Clock.cs
- src/OpenTelemetry.Sampler.AWS/RulesCache.cs
- src/OpenTelemetry.Sampler.AWS/SamplingRuleApplier.cs
- src/OpenTelemetry.Sampler.AWS/SystemClock.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestClock.cs
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1219
Changes Sampler.AWS to use `DateTimeOffset` instead of `DateTime` as it has better time zone support.
Do a second pass on change set to evaluate any breaking changes.
> [Sampler.AWS]  Use DateTimeOffset to beter handle timezones.

- src/OpenTelemetry.Extensions/CHANGELOG.md
Updates the Changelog for OpenTelemtry.Extensions so the next version of the package can be published.
cc @open-telemetry/dotnet-contrib-maintainers
> Release v1.0.0-beta.5 of OpenTelemetry.Extensions package

- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
Remove the reference to System.Net.Http to reduce noise in the NuGet dependency graph.
Including this reference requires restoring all these packages during builds. Most of them are stubs that don't contain binaries. They are not required on any of the supported .NET runtimes. (In fact, this project doesn't reference anything from the System.Net.Http namespace.)
```json
"System.Net.Http": {
"type": "Transitive",
"resolved": "4.3.4",
"contentHash": "aOa2d51SEbmM+H+Csw7yJOuNZoHkrP2XnAurye5HWYgGVVU54YZDvsLUYRv6h18X3sPnjNCANmN7ZhIPiqMcjA==",
"dependencies": {
"Microsoft.NETCore.Platforms": "1.1.1",
"System.Collections": "4.3.0",
"System.Diagnostics.Debug": "4.3.0",
"System.Diagnostics.DiagnosticSource": "4.3.0",
"System.Diagnostics.Tracing": "4.3.0",
"System.Globalization": "4.3.0", …
```
> [Extensions.AWS] Remove NuGet reference to System.Net.Http

- build/scripts/test-aot-compatibility.ps1
Minor fix up of the powershell script.
Porting change from https://github.com/open-telemetry/opentelemetry-dotnet/pull/5645.
> Fix variable usage in test-aot-compatibility script

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Common.GenevaExporter.props
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/TlvMetricExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
Fixes #.
Updates SDK version to `1.9.0-alpha.1` and removes `EXPOSE_EXPERIMENTAL_FEATURES` directives
> [Exporter.Geneva] 1.9.0-alpha.1 release prep

- .github/workflows/ci.yml
- build/Projects/OpenTelemetry.Exporter.InfluxDB.proj
- build/Projects/OpenTelemetry.Extensions.Enrichment.proj
- build/Projects/OpenTelemetry.Instrumentation.GrpcCore.proj
[repo] Use separate, standardized builds for all packages
Side effect - fixes #1513.
> [repo] Use separate, standardized builds for all packages

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisInstrumentationOptions.cs
> Fix StackExchangeRedisInstrumentationOptions xml docs

- .github/workflows/automation.yml
- .github/workflows/core-version-update.yml
- build/scripts/post-release.psm1
- opentelemetry-dotnet-contrib.sln
* Use a dedicated bot account for the `core-version-update.yml` workflow
Relates to https://github.com/open-telemetry/opentelemetry-dotnet/pull/5657
Previously we were using the `github-actions` bot with workflow permissions. However things done in that context (push, create pr, publish release, etc.) don't trigger other workflows. So the PRs which are opened won't have CI run for example. The recommendation (see: https://github.com/open-telemetry/community/issues/2127#issue-2308782705) was to use `OpenTelemetryBot` instead which is more or less a normal account.
Demo PR: https://github.com/CodeBlanchOrg/opentelemetry-dotnet-contrib/pull/3
Note: That demo shows `CodeBlanchBot` because it is my test org but when run here it will be `OpenTelemetryBot`.
> [repo] Switch core-version-update workflow to use a dedicated bot account

- .github/workflows/post-release.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-packages.yml
- build/scripts/post-release.psm1
- build/scripts/prepare-release.psm1
- opentelemetry-dotnet-contrib.sln
Relates to https://github.com/open-telemetry/opentelemetry-dotnet/pull/5657
* Sets up the release automation to use `OpenTelemetryBot`
* Refactors post-release PackageValidationBaselineVersion PR update job from package workflow into a new workflow triggered by the release publish
This PR syncs up contrib with the main repo such that the release automation uses `OpenTelemetryBot`.
Test runs:
* https://github.com/CodeBlanchOrg/opentelemetry-dotnet-contrib/pull/8
* https://github.com/CodeBlanchOrg/opentelemetry-dotnet-contrib/pull/9
> [repo] Release automation improvements

- build/Common.props
- examples/process-instrumentation/process-instrumentation.csproj
- examples/runtime-instrumentation/runtime-instrumentation.csproj
Fix the build failures from https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1869
> [repo] Separate pkg version for core-unstable packages

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSSemanticConventions.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs
Based on Opentelemetry Semantic Conventions for AWS SDK: https://opentelemetry.io/docs/specs/semconv/cloud-providers/aws-sdk, update Activity Tags for `rpc.service, rpc.system, rpc.method`.
Fixes #1857 
Currently AWS SDK instrumentation did not set RPC Activity Tags as mentioned in https://opentelemetry.io/docs/specs/semconv/cloud-providers/aws-sdk/, this change will add missing tags. Changes have been tested with OpenTelemetry.Instrumentation.AWS.Tests
> [Instrumentation.AWS] Update AWS SDK Activity Tags (#1857)

- src/OpenTelemetry.Resources.Azure/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Resources.Azure/AzureResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.Azure/CHANGELOG.md
- src/OpenTelemetry.Resources.Azure/README.md
> [Resources.Azure] Rename AddAppServiceDetector to AddAzureAppServiceDetector

- build/scripts/add-labels.psm1
* Retrieve up to 200 labels from the repo to use for tagging PRs based on the files changed. The default is 30.
> [repo] Auto-label PR workflow improvements

- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
Fixes build failures from https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1888. Use pre-release versions consistently for all packages.
ref: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/9521755414/job/26249939293?pr=1888
> [Exporter.Geneva] Fix test dependency conflict

- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs
Cleanup code after 1.9.0 release. Ref: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5614
Minor other cleanups while checking all usages of the constructor.
> [Tests] Simplify usage of SamplingResult constructor

- src/OpenTelemetry.Exporter.Instana/.publicApi/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpan.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpanSerializer.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpanTransformInfo.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/ActivityProcessorBase.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/DefaultActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/ErrorActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/EventsActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/IActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/TagsActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Transport.cs
- src/OpenTelemetry.Exporter.Instana/InstanaExporter.cs
- src/OpenTelemetry.Exporter.Instana/OpenTelemetry.Exporter.Instana.csproj
- test/OpenTelemetry.Exporter.Instana.Tests/Processors/EventsActivityProcessorTests.cs
Towards https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/894.
> [Exporter.Instana] nullable support

- src/OpenTelemetry.Instrumentation.Http/.publicApi/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentationTracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Http/HttpClientMetrics.cs
- src/OpenTelemetry.Instrumentation.Http/HttpClientTraceInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerMetricsDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs
- src/OpenTelemetry.Instrumentation.Http/OpenTelemetry.Instrumentation.Http.csproj
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcTests.client.cs
- test/OpenTelemetry.Instrumentation.Http.Benchmarks/Instrumentation/HttpClientInstrumentationBenchmarks.cs
- test/OpenTelemetry.Instrumentation.Http.Benchmarks/OpenTelemetry.Instrumentation.Http.Benchmarks.csproj
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.Basic.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpOutTestCase.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpTestData.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestActivitySourceTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestTests.Basic.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestTests.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/OpenTelemetry.Instrumentation.Http.Tests.csproj
- test/OpenTelemetry.Instrumentation.Http.Tests/RepeatHandler.cs
Towards #894
[Instrumentation.Http] Nullable except `HttpWebRequestActivitySource` and corresponding tests.
I think that this class deserves separate PR.
> [Instrumentation.Http] Nullable

- test/OpenTelemetry.Resources.Azure.Tests/AzureResourceDetectorTests.cs
- test/OpenTelemetry.Resources.Host.Tests/HostDetectorTests.cs
- test/OpenTelemetry.Resources.Process.Tests/ProcessDetectorTests.cs
- test/OpenTelemetry.Resources.ProcessRuntime.Tests/ProcessRuntimeDetectorTests.cs
[discussion](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1943#discussion_r1671348344)
Instead of instantiating objects via constructors, a static extension method is now used in tests to enhance code readability and maintainability
> [tests - resource packages] Use extension method instead of constructor in Tests

- build/scripts/add-labels.psm1
* Ports the path fix from the main repo see: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5751
> [infra] Sync up add-labels with changes from main repo

- .github/component_owners.yml
Volunteering myself as component owner for Redis instrumentation.
Adds @matt-hensley as owner of instrumentation and relevant tests.
> [Instrumentation.StackExchangeRedis] @matt-hensley as component owner

- build/Common.props
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
Fixes #1951
Updates `StackExchange.Redis` to `2.6.122` to resolve CVE warnings in a transitive dependency. See #1951 for additional details.
Starting with [version 2.6.80 of `StackExchange.Redis`](https://github.com/StackExchange/StackExchange.Redis/issues/2283#issuecomment-1292028155) the dependency causing the warning was dropped.
Upgrading to `2.6.122` as this is the earliest version with the dependency fix and [a correction to the type signature for `IConnectionMultiplexer.RegisterProfiler`](https://github.com/StackExchange/StackExchange.Redis/releases/tag/2.6.122).
Some tests have had the null-forgiving operator applied to variables. The test attributes look to cause those cases to be skipped if the variable wouldn't have been populated.
> [Instrumentation.StackExchangeRedis] Updates `StackExchange.Redis` to `2.6.122`

- src/OpenTelemetry.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcCore/ClientStreamWriterProxy.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/OpenTelemetry.Instrumentation.GrpcCore.csproj
- src/OpenTelemetry.Instrumentation.GrpcCore/ServerStreamWriterProxy.cs
Related to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1936#discussion_r1661915696
Update minimal supported version of `Grpc.Core.Api` to the latest (from 2.43.0 to 2.46.6).
~~* [] Unit tests added/updated~~
~~* [] Changes in public API reviewed (if applicable)~~
> [Instrumentation.GrpcCore] Update minimal supported version of Grpc.Core.Api to 2.46.6

- .github/workflows/Component.BuildTest.yml
- .github/workflows/ci.yml
- build/scripts/add-labels.psm1
- src/OpenTelemetry.Resources.OperatingSystem/CHANGELOG.md
- src/OpenTelemetry.Resources.OperatingSystem/OperatingSystemDetector.cs
- test/OpenTelemetry.Resources.OperatingSystem.Tests/OperatingSystemDetectorTests.cs
Fixes # Fix issue with detecting MacOS
Fix issue with detecting MacOS
> [Resources.OperatingSystem]  Fix issue with detecting MacOS

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- src/OpenTelemetry.Instrumentation.Owin/OwinInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Owin/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/DiagnosticsMiddlewareTests.cs
Relates to #1960
* Updates Owin to retrieve `OTEL_DOTNET_EXPERIMENTAL_OWIN_DISABLE_URL_QUERY_REDACTION` using `IConfiguration`
> [Instrumentation.Owin] Add IConfiguration support

- src/OpenTelemetry.Instrumentation.AspNet/AspNetTraceInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/AspNetInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.AspNet/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
- src/OpenTelemetry.Instrumentation.AspNet/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
Fixes #1960
* Updates AspNet to retrieve `OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION` using `IConfiguration`
> [Instrumentation.AspNet] Add IConfiguration support

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
* Switches Owin to depend on API instead of SDK
> [Instrumentation.Owin] Remove SDK dependency

- build/Common.nonprod.props
- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/OneCollectorExporterEventSource.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Transports/HttpJsonPostTransport.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/HttpJsonPostTransportTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/OpenTelemetry.Exporter.OneCollector.Tests.csproj
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcTests.client.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/Shared/InMemoryEventListener.cs
Relates to #1984
* Switch to using `IsSuccessStatusCode` instead of calling `EnsureSuccessStatusCode` to ensure that the response is not disposed on older runtimes.
Per https://learn.microsoft.com/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode
> The `EnsureSuccessStatusCode` method throws an exception if the HTTP response was unsuccessful. In .NET Framework and .NET Core 2.2 and earlier versions, if the `Content` is not null, this method will also call `Dispose` to free managed and unmanaged resources. Starting with .NET Core 3.0, the content will not be disposed."
> [OneCollector] Fix events not firing for failed responses on .NET Framework

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/Transports/HttpJsonPostTransport.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Transports/IHttpClient.cs
- test/OpenTelemetry.Exporter.OneCollector.Benchmarks/LogRecordCommonSchemaJsonHttpPostBenchmarks.cs
* Use `HttpClient.SendAsync` on mobile platforms to avoid `PlatformNotSupportedException`s thrown calling `HttpClient.Send`
> [onecollector] Use HttpClient.SendAsync on mobile platforms to avoid PlatformNotSupportedExceptions

- .github/workflows/integration.yml
Fixes https://github.com/actions/runner-images/issues/9692
Update Docker Compose in our CI
> [repo] Update Docker Compose to v2

- src/OpenTelemetry.Instrumentation.AWS/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSHistogram.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSMeter.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSMeterProvider.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSMonotonicCounter.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSUpDownCounter.cs
- src/OpenTelemetry.Instrumentation.AWS/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/OpenTelemetry.Instrumentation.AWS.Tests.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientMetricsInstrumentation.cs
* Integration of New Metrics APIs:
Implemented the new AWS SDK tracing APIs, starting with `AWSMeterProvider`.
* Added Instrumentation Method:
Introduced `MeterProviderBuilderExtensions.AddAWSInstrumentation` to enable metrics instrumentation.
* SDK Version Update:
Updated the SDK version to `3.7.400` to incorporate the new tracing APIs.
This update conflicts with the changes in PR [#1974](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1974). The last merged PR will rebase accordingly.
> [Instrumentation.AWS] Add AWS metrics instrumentation

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/OneCollectorExporterEventSource.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/BatchSerializationResult.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/BatchSerializationState.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializer.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/ISerializer.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Sinks/WriteDirectlyToTransportSink.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/LogRecordCommonSchemaJsonSerializerTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/WriteDirectlyToTransportSinkTests.cs
* Change `WriteDirectlyToTransportSink` logic so it sends multiple requests to OneCollector until the batch is drained
* Update `CommonSchemaJsonSerializer` logic to drop any individual item which cannot fit into the max payload size
OneCollector is strict about the amount of data it will process. Given a batch `OneCollectorExporter` will serialize items until it reaches the max payload size. The previous behavior was it would leave anything remaining in the batch expecting to process those records as part of the next batch. This leads to dropped telemetry though because [BatchExportProcessor disposes\drains the batch after calling the exporter](https://github.com/open-telemetry/opentelemetry-dotnet/blob/32c64d04defb5c92d056fd8817638151168b10da/src/OpenTelemetry/BatchExportProcessor.cs#L26 …
> [onecollector] Serialization fixes

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/README.md
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
Added the "url.path" tag to the tags for newly created activities in StartAspNetActivity.
To ignore a path like a healthcheck it is best to use a sampler to ensure that the activity and all child activities are dropped in a sampler. To do this the sampler needs to be able to provide enough information for the sampler author to detect the path. This is only currently possible by using HttpContext.Current or other method of injecting the request into the sampler. This is unsatisfying because the caller of the sampler has information about the current request it just doesn't have a way to pass that information to the sampler. 
This PR changes the way StartAspNetActivity works by adding the request.Unvalidated.Path of the request to the tags that are used to construct the activity. The tags …
> [aspnet] Add url.path to sampler tags

- src/OpenTelemetry.Instrumentation.AWSLambda/AWSLambdaWrapper.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaSemanticConventions.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaUtils.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/AWSLambdaWrapperTests.cs
> [Instrumentation.AWSLambda] Incoming FaaS Span attributes: detect and set attribute for cold start

- build/Common.nonprod.props
- examples/AspNet/Examples.AspNet.csproj
- examples/InfluxDB/Examples.InfluxDB/Examples.InfluxDB.csproj
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/OpenTelemetry.Instrumentation.AspNetCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/OpenTelemetry.Instrumentation.GrpcNetClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
- test/TestApp.AspNetCore/TestApp.AspNetCore.csproj
Fixes #
Drop dotnet-xunit (ref https://xunit.net/docs/nuget-packages#retired) + bump test dependencies
> [repo] Drop dotnet-xunit + bump test dependencies

- build/OpenTelemetryContrib.prod.ruleset
- src/OpenTelemetry.Exporter.Geneva/EventNameExportMode.cs
- src/OpenTelemetry.Exporter.Geneva/ExceptionStackExportMode.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaBaseExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaExporterHelperExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLoggingExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporterExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
* Enable CS1591 in GenevaExporter and add missing XML docs for public APIs.
> [geneva] Add missing XML docs for public APIs

- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/LogSerializationTests.cs
Follow-up to #2052
* Fix up tests using reflection which broke due to renames
> [geneva] Remove reflection from tests to fix failures due to renames

- .github/component_owners.yml
- src/OpenTelemetry.Exporter.Geneva/README.md
- src/OpenTelemetry.PersistentStorage.Abstractions/README.md
- src/OpenTelemetry.PersistentStorage.FileSystem/README.md
- src/OpenTelemetry.Resources.Azure/README.md
Vishwesh has transitioned out of OpenTelemetry (see [#2041](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2041)). This PR updates the `component_owners.yml` file to replace Vishwesh’s GitHub handle with either Raj's or Mothra’s for below components. 
* `OpenTelemetry.PersistentStorage.Abstractions`
* `OpenTelemetry.PersistentStorage.FileSystem`
* `OpenTelemetry.Resources.Azure`
* `OpenTelemetry.PersistentStorage.FileSystem.Tests`
* `OpenTelemetry.Resources.Azure.Tests`
Additionally, this PR replaces Yun-Ting with Raj as the owner for the `OpenTelemetry.Exporter.Geneva` component.
> Update Component Ownership for Components

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
``` 
<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
```
Changelog based on https://github.com/open-telemetry/opentelemetry-dotnet/blob/37535a5607ee7e4056c0e274ec01d1e0111a64be/src/OpenTelemetry.Exporter.Console/CHANGELOG.md#L112-L114
> [Instrumentation.Hangfire] NugetAudit - fix dependencies with known vulnerabilities

- src/OpenTelemetry.Instrumentation.Cassandra/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Cassandra/OpenTelemetry.Instrumentation.Cassandra.csproj
- test/OpenTelemetry.Instrumentation.Cassandra.Tests/OpenTelemetry.Instrumentation.Cassandra.Tests.csproj
``` 
<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
```
Changelog based on https://github.com/open-telemetry/opentelemetry-dotnet/blob/37535a5607ee7e4056c0e274ec01d1e0111a64be/src/OpenTelemetry.Exporter.Console/CHANGELOG.md#L112-L114
> [Instrumentation.Cassandra] NugetAudit - fix dependencies with known vulnerabilities

- src/OpenTelemetry.Exporter.Geneva/GenevaExporterHelperExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLoggingExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantExportProcessor.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporterExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/TlvMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/MetricEtwDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/EtwDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/UnixDomainSocketEndPoint.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/JsonSerializer.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
* Remove the remaining project-level warning suppressions and update code to be compliant with repo rules
> [geneva] Remove remaining project-level warning suppressions and update code to be compliant

- src/OpenTelemetry.Resources.Gcp/OpenTelemetry.Resources.Gcp.csproj
``` 
<PackageReference Include="System.Text.Encodings.Web" Version="4.7.2" />
```
* ~~[ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes~~ not needed, package was not released yet.
> [Resources.Gcp] NugetAudit - fix dependencies with known vulnerabilities

- src/OpenTelemetry.Resources.Azure/CHANGELOG.md
- src/OpenTelemetry.Resources.Azure/OpenTelemetry.Resources.Azure.csproj
``` 
<PackageReference Include="System.Text.Encodings.Web" Version="4.7.2" />
```
Changelog based on https://github.com/open-telemetry/opentelemetry-dotnet/blob/37535a5607ee7e4056c0e274ec01d1e0111a64be/src/OpenTelemetry.Exporter.Console/CHANGELOG.md#L112-L114
> [Resources.Azure] NugetAudit - fix dependencies with known vulnerabilities

- src/OpenTelemetry.Exporter.Geneva/.publicApi/PublicAPI.Shipped.txt
* Enable nullable in GenevaExporter public APIs files to get it ready for proper annotation
> [geneva] Enable nullable in GenevaExporter public API files

- .github/workflows/ci.yml
Always execute build-tests step. It is used to determine if all steps passed.
Before changes there were possibility to merge changes even if previous steps were failing.
> [repo] Always execute build-test step

- src/OpenTelemetry.Exporter.Geneva/EventNameExportMode.cs
- src/OpenTelemetry.Exporter.Geneva/ExceptionStackExportMode.cs
- src/OpenTelemetry.Exporter.Geneva/External/TraceLoggingDynamic.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ConnectionStringBuilder.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ExporterEventSource.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantActivityExportProcessor.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantExportProcessor.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/Schema.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/TableNameSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
* Nullable annotations for the internal folder (and a couple other misc things) in GenevaExporter
> [geneva] Nullable annotations for the internal folder

- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
Bump InfluixDB.Client to 4.18.0 to mitigate CVEs in transitive dependencies.
> [Exporter.InfluxDB] NugetAudit - fix dependencies with known vulnerabilities

- build/Common.nonprod.props
- examples/InfluxDB/Examples.InfluxDB/Examples.InfluxDB.csproj
- examples/enrichment/Examples.Enrichment/Examples.Enrichment.csproj
- examples/event-counters/Examples.EventCounters/Examples.EventCounters.csproj
- examples/grpc.core/Examples.GrpcCore.AspNetCore/Examples.GrpcCore.AspNetCore.csproj
- examples/kafka/Examples.ConfluentKafka.csproj
- examples/owin/Examples.Owin.csproj
- examples/process-instrumentation/process-instrumentation.csproj
- examples/redis/Examples.StackExchangeRedis/Examples.StackExchangeRedis.csproj
- examples/runtime-instrumentation/runtime-instrumentation.csproj
- examples/wcf/client-core/Examples.Wcf.Client.DotNet.csproj
- examples/wcf/client-netframework/Examples.Wcf.Client.NetFramework.csproj
- examples/wcf/server-aspnetframework/Examples.Wcf.Server.AspNetFramework.csproj
- examples/wcf/server-netframework/Examples.Wcf.Server.NetFramework.csproj
- examples/wcf/shared/Examples.Wcf.Shared.csproj
As per the discussion in #2087, this PR centralizes versions for example projects.
> [examples] Centralize TFMs for easier management

- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/TlvMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/MetricUnixDomainSocketDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/MetricWindowsEventTracingDataTransport.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
[Split off from #2113]
* Rename the metric transports in GenevaExporter to prepare for addition of `MetricUnixUserEventsDataTransport`
> [geneva] Rename metric transports

- test/OpenTelemetry.Exporter.InfluxDB.Tests/OpenTelemetry.Exporter.InfluxDB.Tests.csproj
#2123 introduced a new MSBuild prop SupportedNetTargetsWithoutNet6 used in test projects. This PR uses it in InfluxDB test project.
> [Exporter.InfluxDB] Replace hardcoded TFM in test project

- test/OpenTelemetry.Exporter.Geneva.Benchmarks/OpenTelemetry.Exporter.Geneva.Benchmarks.csproj
- test/OpenTelemetry.Exporter.Geneva.Stress/OpenTelemetry.Exporter.Geneva.Stress.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
#2123 introduced a new MSBuild prop SupportedNetTargetsWithoutNet6 used in test projects. This PR uses it in Geneva test projects.
> [Exporter.Geneva] Replace hardcoded TFM in test projects

- build/Common.prod.props
- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- src/OpenTelemetry.Extensions/Trace/AutoFlushActivityProcessor.cs
- test/OpenTelemetry.Extensions.Tests/OpenTelemetry.Extensions.Tests.csproj
> [Extensions] Replace .NET 6 target with .NET 8

- src/OpenTelemetry.Extensions.Enrichment/CHANGELOG.md
- src/OpenTelemetry.Extensions.Enrichment/OpenTelemetry.Extensions.Enrichment.csproj
- test/OpenTelemetry.Extensions.Enrichment.Tests/OpenTelemetry.Extensions.Enrichment.Tests.csproj
> [Extensions.Enrichment] Remove .NET 6 target

- src/OpenTelemetry.Instrumentation.Cassandra/OpenTelemetry.Instrumentation.Cassandra.csproj
- test/OpenTelemetry.Instrumentation.Cassandra.Tests/OpenTelemetry.Instrumentation.Cassandra.Tests.csproj
> [Instrumentation.Cassandra] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
- src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
- src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNetCore/OpenTelemetry.Instrumentation.AspNetCore.csproj
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNet.Tests/OpenTelemetry.Instrumentation.AspNet.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNetCore.Benchmarks/OpenTelemetry.Instrumentation.AspNetCore.Benchmarks.csproj
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/OpenTelemetry.Instrumentation.AspNetCore.Tests.csproj
> [Instrumentation.AspNetCore] Remove .NET 6 target

- src/OpenTelemetry.Instrumentation.GrpcNetClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcNetClient/OpenTelemetry.Instrumentation.GrpcNetClient.csproj
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/OpenTelemetry.Instrumentation.GrpcNetClient.Tests.csproj
> [Instrumentation.GrpcNetClient] Remove .NET 6 target

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/OpenTelemetry.Instrumentation.AWS.Tests.csproj
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/HttpResponseMessageBody.cs
> [Instrumentation.AWS] Replace .NET 6 target with .NET 8

- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSMessagingUtils.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/OpenTelemetry.Instrumentation.AWSLambda.Tests.csproj
> [Instrumentation.AWSLambda] Replace .NET 6 target with .NET 8 and add .NET Standard 2.0

- .github/workflows/integration.yml
- src/OpenTelemetry.Instrumentation.ConfluentKafka/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetry.Instrumentation.ConfluentKafka.csproj
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetryConsumeResultExtensions.cs
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetryConsumerBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetryProducerBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/OpenTelemetry.Instrumentation.ConfluentKafka.Tests.csproj
Remove .NET 6 target which will be very soon out of support and add support for .NET Standard 2.0.
> [Instrumentation.ConfluentKafka] Remove .NET 6 target and add .NET Standard 2.0

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/OpenTelemetry.Instrumentation.ElasticsearchClient.csproj
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests.csproj
> [Instrumentation.ElasticsearchClient] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.Instrumentation.GrpcCore/OpenTelemetry.Instrumentation.GrpcCore.csproj
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/OpenTelemetry.Instrumentation.GrpcCore.Tests.csproj
> [Instrumentation.GrpcCore] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.Instrumentation.Http/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Http/OpenTelemetry.Instrumentation.Http.csproj
- test/OpenTelemetry.Instrumentation.Http.Benchmarks/OpenTelemetry.Instrumentation.Http.Benchmarks.csproj
- test/OpenTelemetry.Instrumentation.Http.Tests/OpenTelemetry.Instrumentation.Http.Tests.csproj
> [Instrumentation.Http] Remove .NET 6 target

- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/OpenTelemetry.Instrumentation.Hangfire.Tests.csproj
> [Instrumentation.Hangfire] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.Instrumentation.Process/OpenTelemetry.Instrumentation.Process.csproj
- test/OpenTelemetry.Instrumentation.Process.Tests/OpenTelemetry.Instrumentation.Process.Tests.csproj
> [Instrumentation.Process] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- test/OpenTelemetry.Instrumentation.Runtime.Tests/OpenTelemetry.Instrumentation.Runtime.Tests.csproj
> [Instrumentation.Runtime] Replace .NET 6 target with .NET 8

- src/OpenTelemetry.Instrumentation.Quartz/OpenTelemetry.Instrumentation.Quartz.csproj
- test/OpenTelemetry.Instrumentation.Quartz.Tests/OpenTelemetry.Instrumentation.Quartz.Tests.csproj
> [Instrumentation.Quartz] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/OpenTelemetry.Instrumentation.SqlClient.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTestsFixture.cs
> [Instrumentation.SqlClient] Remove .NET 6 target

- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
- test/OpenTelemetry.Instrumentation.Wcf.Tests/OpenTelemetry.Instrumentation.Wcf.Tests.csproj
> [Instrumentation.Wcf] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.PersistentStorage.FileSystem/OpenTelemetry.PersistentStorage.FileSystem.csproj
- test/OpenTelemetry.PersistentStorage.FileSystem.Tests/OpenTelemetry.PersistentStorage.FileSystem.Tests.csproj
> [PersistentStorage.FileSystem] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.PersistentStorage.Abstractions/OpenTelemetry.PersistentStorage.Abstractions.csproj
- test/OpenTelemetry.PersistentStorage.Abstractions.Tests/OpenTelemetry.PersistentStorage.Abstractions.Tests.csproj
> [PersistentStorage.Abstractions] Replace .NET 6 target with .NET 8 for test project

- src/OpenTelemetry.Resources.Azure/CHANGELOG.md
- src/OpenTelemetry.Resources.Azure/OpenTelemetry.Resources.Azure.csproj
- test/OpenTelemetry.Resources.Azure.Tests/OpenTelemetry.Resources.Azure.Tests.csproj
> [Resources.Azure] Replace .NET 6 target with .NET 8

- src/OpenTelemetry.Resources.Host/CHANGELOG.md
- src/OpenTelemetry.Resources.Host/HostDetector.cs
- src/OpenTelemetry.Resources.Host/OpenTelemetry.Resources.Host.csproj
- test/OpenTelemetry.Resources.Host.Tests/OpenTelemetry.Resources.Host.Tests.csproj
> [Resources.Host] Replace .NET 6 target with .NET 8 and add .NET Standard 2.0 target

- src/OpenTelemetry.Resources.ProcessRuntime/CHANGELOG.md
- src/OpenTelemetry.Resources.ProcessRuntime/OpenTelemetry.Resources.ProcessRuntime.csproj
- test/OpenTelemetry.Resources.ProcessRuntime.Tests/OpenTelemetry.Resources.ProcessRuntime.Tests.csproj
> [Resources.ProcessRuntime] Replace .NET 6 target with .NET 8 and add .NET Standard 2.0 target

- src/OpenTelemetry.Resources.OperatingSystem/CHANGELOG.md
- src/OpenTelemetry.Resources.OperatingSystem/OpenTelemetry.Resources.OperatingSystem.csproj
- src/OpenTelemetry.Resources.OperatingSystem/OperatingSystemDetector.cs
- test/OpenTelemetry.Resources.OperatingSystem.Tests/OpenTelemetry.Resources.OperatingSystem.Tests.csproj
> [Resources.OperatingSystem] Replace .NET 6 target with .NET 8 and add .NET Standard 2.0 target

- build/Common.props
- src/OpenTelemetry.Resources.Container/CHANGELOG.md
- src/OpenTelemetry.Resources.Container/ContainerDetector.cs
- src/OpenTelemetry.Resources.Container/OpenTelemetry.Resources.Container.csproj
- test/OpenTelemetry.Resources.Container.Tests/OpenTelemetry.Resources.Container.Tests.csproj
> [Resources.Container] Replace .NET 6 target with .NET 8 and add .NET Standard 2.0 target

- src/OpenTelemetry.Resources.Gcp/CHANGELOG.md
- src/OpenTelemetry.Resources.Gcp/OpenTelemetry.Resources.Gcp.csproj
- test/OpenTelemetry.Resources.Gcp.Tests/OpenTelemetry.Resources.Gcp.Tests.csproj
> [Resources.Gcp] Replace .NET 6 target with .NET 8

- src/OpenTelemetry.Sampler.AWS/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/OpenTelemetry.Sampler.AWS.csproj
- test/OpenTelemetry.Sampler.AWS.Tests/OpenTelemetry.Sampler.AWS.Tests.csproj
> [Sampler.AWS] Replace .NET 6 target with .NET 8

- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetry.Instrumentation.ConfluentKafka.csproj
This setting is already enabled globally in this repo
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/98a36c86cc313657175c0ecc85d787c0e180d8f3/build/Common.props#L14
> [Instrumentation.ConfluentKafka] Remove ImplicitUsings property

- src/Shared/RequestDataHelper.cs
- test/OpenTelemetry.Contrib.Shared.Tests/OpenTelemetry.Contrib.Shared.Tests.csproj
> [Shared.Tests] Replace .NET 6 target with .NET 8

- test/TestApp.AspNetCore/TestApp.AspNetCore.csproj
> [TestApp.AspNetCore] Replace .NET 6 target with .NET 8

- src/OpenTelemetry.Exporter.OneCollector/Internal/Transports/TransportSendRequest.cs
- src/OpenTelemetry.Exporter.OneCollector/OneCollectorExporterValidationException.cs
- src/OpenTelemetry.Extensions.AWS/AWSXRayIdGenerator.net.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreInstrumentationMeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreMetrics.cs
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetryConsumerBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetryProducerBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentationMeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs
- src/Shared/Configuration/OpenTelemetryConfigurationExtensions.cs
- src/Shared/RequestDataHelper.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/CommonSchemaJsonSerializationHelperTests.cs
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/MetricTests.cs
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/RouteTests/TestApplication/RouteInfo.cs
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/RouteTests/TestApplication/TestApplicationFactory.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.cs
Remove versions from preprocessor directives where possible.
> [repo] Simplify preprocessor directives after dropping support for .NET 6

- src/OpenTelemetry.Exporter.Instana/OpenTelemetry.Exporter.Instana.csproj
- test/OpenTelemetry.Exporter.Instana.Tests/OpenTelemetry.Exporter.Instana.Tests.csproj
> [Exporter.Instana] Replace .NET 6 target with .NET 8 for test project

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/Component.BuildTest.yml
- .github/workflows/ci-Exporter.OneCollector-Integration.yml
- .github/workflows/ci.yml
- build/docker-compose.net6.0.yml
- opentelemetry-dotnet-contrib.sln
- test/OpenTelemetry.Exporter.Geneva.Tests/LogSerializationTests.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/OpenTelemetry.Exporter.InfluxDB.Tests.csproj
This PR removes some occurrences of `net6.0` through the repo.
> [repo] Some cleanup after dropping support for .NET 6

- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/OpenTelemetry.Instrumentation.EntityFrameworkCore.csproj
- src/OpenTelemetry.Instrumentation.GrpcNetClient/OpenTelemetry.Instrumentation.GrpcNetClient.csproj
- src/OpenTelemetry.Instrumentation.Owin/OpenTelemetry.Instrumentation.Owin.csproj
- src/OpenTelemetry.Instrumentation.Quartz/OpenTelemetry.Instrumentation.Quartz.csproj
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
- test/OpenTelemetry.Exporter.Instana.Tests/OpenTelemetry.Exporter.Instana.Tests.csproj
- test/OpenTelemetry.Exporter.OneCollector.Benchmarks/OpenTelemetry.Exporter.OneCollector.Benchmarks.csproj
- test/OpenTelemetry.Exporter.OneCollector.Tests/OpenTelemetry.Exporter.OneCollector.Tests.csproj
- test/OpenTelemetry.Instrumentation.Cassandra.Tests/OpenTelemetry.Instrumentation.Cassandra.Tests.csproj
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/OpenTelemetry.Instrumentation.ConfluentKafka.Tests.csproj
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.Owin.Tests/OpenTelemetry.Instrumentation.Owin.Tests.csproj
Replace some hardcoded TFMs that were forgotten when removing support for .NET 6.
> [repo] Replace some hardcoded TFM

- src/OpenTelemetry.Sampler.AWS/OpenTelemetry.Sampler.AWS.csproj
- test/OpenTelemetry.Extensions.AWS.Tests/OpenTelemetry.Extensions.AWS.Tests.csproj
Simplify a couple of MSBuild conditions.
> [repo] Simplify a couple of MSBuild conditions

- examples/kafka/Examples.ConfluentKafka.csproj
- examples/wcf/client-core/Examples.Wcf.Client.DotNet.csproj
* Bump packages bringing in vulnerable System.Text.Json in example apps to safe versions.
> [examples] Bump packages dependent on vulnerable System.Text.Json versions

- build/Common.nonprod.props
- examples/kafka/Examples.ConfluentKafka.csproj
- examples/wcf/client-core/Examples.Wcf.Client.DotNet.csproj
- test/OpenTelemetry.Extensions.Enrichment.Tests/OpenTelemetry.Extensions.Enrichment.Tests.csproj
- test/OpenTelemetry.Instrumentation.Cassandra.Tests/OpenTelemetry.Instrumentation.Cassandra.Tests.csproj
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/OpenTelemetry.Instrumentation.ConfluentKafka.Tests.csproj
- test/OpenTelemetry.Instrumentation.Http.Tests/OpenTelemetry.Instrumentation.Http.Tests.csproj
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests.csproj
* Bump packages bringing in vulnerable System.Text.Json in tests to safe versions.
* Switched some of the example apps to use versions from props for M.E.* packages.
> [tests] Bump packages dependent on vulnerable System.Text.Json versions

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.Resources.AWS/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/OpenTelemetry.Sampler.AWS.csproj
- test/OpenTelemetry.Instrumentation.Http.Tests/OpenTelemetry.Instrumentation.Http.Tests.csproj
* Mitigate security vulnerabilities in more projects which are today targeting `System.Text.Json` v6.0.0.
* In `OpenTelemetry.Sampler.AWS` reference `System.Net.Http` directly on `net462` and drop package reference. Not related to vulnerability just making it consistent with the rest of the repo.
Before
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|6.0.0|Yes|
|net8.0|No|8.0.0 - 8.0.5|Depends on installed runtime patch level|
|netstandard2.0|Yes|6.0.0|Yes|
After
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|6.0.10|No|
|net8.0|Yes|8.0.5|No|
|netstandard2.0|Yes|6.0.10|No|
Before
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|6.0.0|Yes|
|net8.0|No|8.0.0 - 8.0.5|Depends on installed runtime patch level| …
> [extensions.aws & sampler.aws] Mitigate STJ vulnerabilities

- build/Common.targets
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/OpenTelemetry.Instrumentation.ElasticsearchClient.csproj
- src/OpenTelemetry.Resources.Azure/CHANGELOG.md
- src/OpenTelemetry.Resources.Azure/OpenTelemetry.Resources.Azure.csproj
- src/OpenTelemetry.Resources.Gcp/CHANGELOG.md
- src/OpenTelemetry.Resources.Gcp/OpenTelemetry.Resources.Gcp.csproj
* Mitigate security vulnerabilities in more remaining projects with a direct reference to STJ.
Before
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|6.0.4|Yes|
|netstandard2.0|Yes|6.0.4|Yes|
After
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|4.7.2|No|
|netstandard2.0|Yes|4.7.2|No|
Before
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|4.7.2|No|
|net8.0|Yes|4.7.2|No|
|netstandard2.0|Yes|4.7.2|No|
After
|Target|Direct reference|Version|Vulnerable|Notes|
|---|---|---|---|---|
|net462|Yes|4.7.2|No||
|net8.0|Yes|8.0.5|No|Wasn't vulnerable before, but also wasn't standard with everything else. Decided to make this standard.|
|netstandard2.0|Yes|4.7.2|No||
Before
|Target|Direct reference|Version|Vulnerable| …
> [elastic. azure, gcp] Mitigate STJ vulnerabilities

- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/OpenTelemetry.Instrumentation.AspNetCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
* Bump packages and add references to mitigate vulnerability warnings in AspNetCore, EntityFramework, & SqlClient test projects.
> [tests] Bump packages and add references to mitigate vulnerability warnings

- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
- test/OpenTelemetry.Exporter.InfluxDB.Tests/OpenTelemetry.Exporter.InfluxDB.Tests.csproj
* Add a direct reference to STJ at `8.0.5` in InfluxDB project for `netstandard2.0` target.
Only `netstandard2.0` because that is pulled in by RestSharp but not for `net8.0` (for whatever reason).
```
[netstandard2.0]
│
└─ InfluxDB.Client (v4.18.0)
└─ InfluxDB.Client.Core (v4.18.0)
└─ RestSharp (v112.0.0)
└─ System.Text.Json (v8.0.4)
[net8.0]
│
└─ No dependency graph(s) found for this target framework.
```
> [influxdb] Mitigate STJ vulnerabilities

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Resources.AWS/CHANGELOG.md
- src/OpenTelemetry.Resources.Azure/CHANGELOG.md
- src/OpenTelemetry.Resources.Gcp/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/OpenTelemetry.Sampler.AWS.csproj
* Lower STJ in AWS extensions and sampler projects for `net462` & `netstandard2.0` because they aren't using anything in the newer bits.
* Fix STJ mitigation CHANGELOG links pointing to main repo.
Before
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|6.0.10|No|
|net8.0|Yes|8.0.5|No|
|netstandard2.0|Yes|6.0.10|No|
After
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|4.7.2|No|
|net8.0|Yes|8.0.5|No|
|netstandard2.0|Yes|4.7.2|No|
Before
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|6.0.10|No|
|net8.0|Yes|8.0.5|No|
|netstandard2.0|Yes|6.0.10|No|
After
|Target|Direct reference|Version|Vulnerable|
|---|---|---|---|
|net462|Yes|4.7.2|No|
|net8.0|Yes|8.0.5|No|
|netstandard2.0|Yes|4.7.2|No|
> [extensions.aws + sampler.aws] Lower STJ version

- examples/AspNet/Examples.AspNet.csproj
* Use `OpenTelemetryCoreUnstableLatestVersion` for `OpenTelemetry.Exporter.Prometheus.HttpListener` reference in AspNet example app.
> [examples] Use the OpenTelemetryCoreUnstableLatestVersion prop in AspNet example

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializationState.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializer.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/LogRecordCommonSchemaJsonSerializerTests.cs
* Reset the extension field serialization state for each item being serialized to fix a bug causing extension fields from earlier records to be applied to later records in a batch.
> [onecollector] Fix duplicate extension field bug

- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
* Use the same tag prefix (`MinVerTagPrefix`) for `OpenTelemetry.Extensions.AWS`, `OpenTelemetry.Instrumentation.AWS`, & `OpenTelemetry.Instrumentation.AWSLambda`.
* Add STJ reference at `6.0.10` / `8.0.5` for `OpenTelemetry.Instrumentation.AWSLambda` since it uses the source generator.
@srprash @ppittle @Oberon00 @rypdal
My goal here is to resolve the last build breaks due to vulnerable STJ package versions:
```
OpenTelemetry.Instrumentation.AWSLambda.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 6.0.0 has a known high severity vulnerability
OpenTelemetry.Instrumentation.AWS.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 6.0.0 has a known high severity vulnerability
```
The reason this is happening is `OpenTelemetry.Instrumentation.AWS` and …
> [aws] Combine Extensions.AWS, Instrumentation.AWS, & Instrumentation.AWSLambda into a single tag

- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.Sampler.AWS/CHANGELOG.md
- src/OpenTelemetry.Sampler.AWS/OpenTelemetry.Sampler.AWS.csproj
[This PR effectively reverts #2199]
* Remove STJ from `OpenTelemetry.Extensions.AWS` completely as it isn't used by any of the code.
* Put STJ back to `6.0.10` for `net462` and `netstandard2.0` targets in `OpenTelemetry.Sampler.AWS` because it relies on some of its behaviors (being able to deserialize to classes which do not have a public parameterless ctor).
> [extensions.aws & sampler.aws] STJ tweaks

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializationState.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializer.cs
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- test/OpenTelemetry.Exporter.OneCollector.Tests/CommonSchemaJsonSerializationStateTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/LogRecordCommonSchemaJsonSerializerTests.cs
[Note: This PR is going into the `main-onecollector-1.9.2` branch which was created off of the `Exporter.OneCollector-1.9.2` tag.]
* Prepare hot-fix for OneCollectorExporter `1.9.2` which includes #2205.
* Bump STJ from `6.0.0` to `6.0.10` for `net462`, `netstandard2.0`, and `netstandard2.1` targets to mitigate CVEs.
> [onecollector-1.9.2] Patch extension data fix

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- test/OpenTelemetry.Exporter.OneCollector.Tests/CommonSchemaJsonSerializationStateTests.cs
* Updates OneCollectorExporter project in main branch for `1.9.3` patch (#2208, #2211).
> [onecollector] Updates for 1.9.3 patch

- .github/codecov.yml
- .github/workflows/ci.yml
- build/Projects/OpenTelemetry.Instrumentation.AWS.proj
- opentelemetry-dotnet-contrib.sln
Follow-up to #2203
* Updates CI for the AWS projects now sharing a tag.
* Adds missing codcov definitions for AWS projects.
* Fixes the sampler leg to run on the correct key.
> [repo] Update CI for AWS projects sharing a tag

- .github/codecov.yml
- .github/workflows/Component.BuildTest.yml
- .github/workflows/ci.yml
* Add missing definitions in `codecov.yml`.
* Update CI to allow skipping of tests.
* Skip tests for some "components" which do not produce valid code coverage reports.
> [repo] Clean up codecov

- src/OpenTelemetry.Exporter.Geneva/Internal/ConnectionStringBuilder.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/MetricSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/FieldNumberConstants.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/ProtobufSerializerHelper.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/TimestampHelpers.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/WireType.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/TlvMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/IMetricDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/MetricUnixDomainSocketDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/MetricWindowsEventTracingDataTransport.cs
* Nullable annotations for the metrics folder in GenevaExporter project.
> [geneva] Nullable annotations for the metrics folder

- .github/component_owners.yml
* Add @muhammad-othman as a co-owner for Instrumentation.AWS component.
> Add muhammad-othman as Instrumentation.AWS component co-owner

- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
Following up on https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2220#issuecomment-2422887815
* Bump MessagePack version in Geneva test project to fix vulnerability warning
> [geneva] Bump MessagePack version in test project to fix vulnerability warning

- .github/workflows/Component.BuildTest.yml
- .github/workflows/ci.yml
- build/Common.prod.props
- test/OpenTelemetry.Exporter.Geneva.Tests/UnixUserEventsDataTransportTests.cs
Relates to #2113
* Adds a CI leg for running geneva linux user_events tests when the code is changed.
> [repo] Add geneva integration test leg to CI

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
- src/OpenTelemetry.Instrumentation.SqlClient/OpenTelemetry.Instrumentation.SqlClient.csproj
- src/OpenTelemetry.Instrumentation.SqlClient/README.md
- src/OpenTelemetry.Instrumentation.SqlClient/SqlClientTraceInstrumentationOptions.cs
- src/Shared/SemanticConventions.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTraceInstrumentationOptionsTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs
Fixes #2225
This PR is the first in a series of PRs. It introduces support for the `OTEL_SEMCONV_STABILITY_OPT_IN` environment variable to gate using the old or new conventions. It does not aim to fully adopt the new database conventions. It only updates conventions for the attributes currently reported by the instrumentation.
The documentation in the readme still only refers to the old attributes. I will update the readme in a different PR.
> [Instrumentation.SqlClient] Update to follow new DB span conventions

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlConnectionDetails.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
- src/OpenTelemetry.Instrumentation.SqlClient/SqlClientTraceInstrumentationOptions.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTraceInstrumentationOptionsTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlConnectionDetailsTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs
This is a refactor that extracts `SqlConnectionDetails` from the `SqlClientTraceInstrumentationOptions` class. Evaluating connection details is not specific to spans - it will also be used for DB metrics.
This PR is similar to what is done in #2026. I will deal with the merge conflicts on #2026.
There's a whole bunch that I don't like about the tests for this instrumentation. A lot of copy and paste for .NET vs. .NET Framework tests and inconsistent test cases covering them. This PR does not attempt to address improving tests. I'll do this in a follow on PR before stabilization.
There's also a small bug fix where `server.port` was captured as a string instead of an int.
> [SqlClient] Refactor SqlConnectionDetails

- build/Common.nonprod.props
- build/Common.props
- examples/wcf/shared/Examples.Wcf.Shared.csproj
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
- src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
- src/OpenTelemetry.Extensions.Enrichment/OpenTelemetry.Extensions.Enrichment.csproj
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
- src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
- src/OpenTelemetry.Instrumentation.AspNetCore/OpenTelemetry.Instrumentation.AspNetCore.csproj
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetry.Instrumentation.ConfluentKafka.csproj
- src/OpenTelemetry.Instrumentation.GrpcNetClient/OpenTelemetry.Instrumentation.GrpcNetClient.csproj
- src/OpenTelemetry.Instrumentation.Http/OpenTelemetry.Instrumentation.Http.csproj
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- src/OpenTelemetry.Instrumentation.SqlClient/OpenTelemetry.Instrumentation.SqlClient.csproj
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
- src/OpenTelemetry.Resources.AWS/OpenTelemetry.Resources.AWS.csproj
- src/OpenTelemetry.Resources.Azure/OpenTelemetry.Resources.Azure.csproj
- src/OpenTelemetry.Resources.Container/OpenTelemetry.Resources.Container.csproj
- src/OpenTelemetry.Resources.Gcp/OpenTelemetry.Resources.Gcp.csproj
- src/OpenTelemetry.Resources.Host/OpenTelemetry.Resources.Host.csproj
- src/OpenTelemetry.Resources.OperatingSystem/OpenTelemetry.Resources.OperatingSystem.csproj
- src/OpenTelemetry.Resources.Process/OpenTelemetry.Resources.Process.csproj
- src/OpenTelemetry.Resources.ProcessRuntime/OpenTelemetry.Resources.ProcessRuntime.csproj
- src/OpenTelemetry.Sampler.AWS/OpenTelemetry.Sampler.AWS.csproj
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
Brings back `NetMinimumSupportedVersion`
> [repo] Use NetMinimumSupportedVersion

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisConnectionInstrumentation.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisInstrumentation.cs
- src/Shared/PropertyFetcher.AOT.cs
> [redis] Prepare to .NET9

- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufMetricExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/Exporter/TLDTraceExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/Exporter/TraceExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/OpenTelemetry.Exporter.Geneva.Benchmarks.csproj
Towards #894
[Exporter.Geneva] benchmarks nullable
With fully nullable repository, it will be easier to accomplish #2251. Unneeded `#nullable enable` are treated as warnings -> errors in .NET9.
> [Exporter.Geneva] benchmarks nullable

- test/OpenTelemetry.Exporter.Geneva.Stress/DummyServer.cs
- test/OpenTelemetry.Exporter.Geneva.Stress/OpenTelemetry.Exporter.Geneva.Stress.csproj
- test/OpenTelemetry.Exporter.Geneva.Stress/Program.cs
Towards #894
[Exporter.Geneva] stress tests nullable
With fully nullable repository, it will be easier to accomplish #2251. Unneeded `#nullable enable` are treated as warnings -> errors in .NET9.
> [Exporter.Geneva] stress nullable

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/AsyncResultWithTelemetryState.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/ClientChannelInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/HttpRequestMessagePropertyWrapper.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/InstrumentedDuplexChannel.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/InstrumentedRequestChannel.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/RequestTelemetryStateTracker.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/TelemetryPropagationWriter.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/WcfInstrumentationActivitySource.cs
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
- test/OpenTelemetry.Instrumentation.Wcf.Tests/OpenTelemetry.Instrumentation.Wcf.Tests.csproj
Fixes scenario when you referencing Instrumentation.Wcf package from .NET6+ with enabled NuGet Audit like for .NET9.
Without changes it was leading to the issues:
Workaround:
Manual referencing safe version of System.Drawing.Common, but it is not user friendly.
* Added .NET6 target (temporary, just to make a release and be able to use new version in .NET AutoInstrumnetation, just after I will bring here .NET8).
* Nullability fixes after add .net6 as a target framework
> [Instrumentation.Wcf] Add .NET6 as target framework

- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBExporterExtensions.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBMetricsExporter.cs
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV1.cs
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV2.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/InfluxDBMetricsExporterTests.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/AssertUtils.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/InfluxDBFakeServer.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/InfluxDBMetricsExporterOptionsTestExtensions.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/LineProtocolParser.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/MeterProviderBuilderTestExtensions.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/PointData.cs
> [repo/InfluxDB] Prepare to .NET9

- src/OpenTelemetry.PersistentStorage.Abstractions/PersistentBlobProvider.cs
- src/OpenTelemetry.PersistentStorage.FileSystem/DirectorySizeTracker.cs
- src/OpenTelemetry.PersistentStorage.FileSystem/FileBlob.cs
- src/OpenTelemetry.PersistentStorage.FileSystem/FileBlobProvider.cs
- src/OpenTelemetry.PersistentStorage.FileSystem/PersistentStorageHelper.cs
- test/Shared/EventSourceTestHelper.cs
- test/Shared/TestEventListener.cs
> [repo/PersistentStorage] Prepare to .NET9

- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ActivityExtensions.cs
- src/OpenTelemetry.Exporter.Stackdriver/StackdriverTraceExporter.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/ActivityExtensionsTest.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/StackdriverExporterTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/TestActivityProcessor.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/TestTraceServiceClient.cs
> [repo/StackDriver] Prepare to .NET9

- src/OpenTelemetry.Extensions.AWS/AWSXRayIdGenerator.cs
- src/OpenTelemetry.Extensions.AWS/Trace/AWSXRayPropagator.cs
- src/OpenTelemetry.Extensions.Enrichment/Internal/TraceEnrichmentActions.cs
- test/OpenTelemetry.Extensions.AWS.Tests/Trace/AWSXRayPropagatorTests.cs
- test/OpenTelemetry.Extensions.Tests/Trace/BaggageActivityProcessorTests.cs
- test/OpenTelemetry.Extensions.Tests/Trace/RateLimitingSamplerTests.cs
> [repo/Extensions] Prepare to .NET9

- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpan.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpanFactory.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpanSerializer.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/ActivityProcessorBase.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/DefaultActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/EventsActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/TagsActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/SpanSender.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Transport.cs
- src/OpenTelemetry.Exporter.Instana/InstanaExporter.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaExporterTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanFactoryTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanSerializerTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanTest.cs
- test/OpenTelemetry.Exporter.Instana.Tests/Processors/DefaultActivityProcessorTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/Processors/ErrorActivityProcessorTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/Processors/EventsActivityProcessorTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/Processors/TagsActivityProcessorTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/TestInstanaExporterHelper.cs
> [repo/Instana] Prepare to .NET9

- src/OpenTelemetry.Sampler.AWS/AWSXRayRemoteSampler.cs
- src/OpenTelemetry.Sampler.AWS/AWSXRaySamplerClient.cs
- src/OpenTelemetry.Sampler.AWS/FallbackSampler.cs
- src/OpenTelemetry.Sampler.AWS/Matcher.cs
- src/OpenTelemetry.Sampler.AWS/RateLimiter.cs
- src/OpenTelemetry.Sampler.AWS/RulesCache.cs
- src/OpenTelemetry.Sampler.AWS/SamplingRule.cs
- src/OpenTelemetry.Sampler.AWS/SamplingRuleApplier.cs
- src/OpenTelemetry.Sampler.AWS/SystemClock.cs
- src/Shared/Guard.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestAWSXRayRemoteSampler.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestAWSXRaySamplerClient.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestClock.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestMatcher.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestRateLimiter.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestRateLimitingSampler.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestRulesCache.cs
- test/OpenTelemetry.Sampler.AWS.Tests/TestSamplingRuleApplier.cs
- test/OpenTelemetry.Sampler.AWS.Tests/Utils.cs
> [repo/AWS.Sampler] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
Follow up to #2243
[Instrumentation.WCF] Switch .NET6 to .NET8
> [Instrumentation.WCF] Switch .NET6 to .NET8

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModule.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/AspNetParentSpanCorrector.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/ClientChannelInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/HttpRequestMessagePropertyWrapper.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/RequestTelemetryStateTracker.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/TelemetryDispatchMessageInspector.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/WcfInstrumentationEventSource.cs
- src/Shared/PropertyFetcher.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/AspNetParentSpanCorrectorTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryBindingElementForHttpTests.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryBindingElementForTcpTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryDispatchMessageInspectorForOneWayOperationsTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryDispatchMessageInspectorTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryPropagationTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/DownstreamInstrumentationBindingElement.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/DownstreamInstrumentationChannel.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/DownstreamInstrumentationChannelFactory.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/DownstreamInstrumentationEndpointBehavior.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/DownstreamInstrumentationExtensions.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/ErrorHandlerServiceBehavior.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/IServiceContract.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/ServiceClient.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/ServiceRequest.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/ServiceResponse.cs
> [repo/WCF] Prepare to .NET9

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/MetricUnixDomainSocketDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/README.md
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterWithPrefixTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterWithoutPrefixTests.cs
* Adds support for sending metrics in OTLP format over Unix domain sockets.
> [geneva] Add support for sending metrics in OTLP format over UDS

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTestCase.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs
Fixes #2236 
Towards #2224 
Towards #2237 
Per the [MSSQL conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/mssql.md):
> [3]: When connected to a default instance, db.namespace SHOULD be set to the name of the database. When connected to a [named instance](https://learn.microsoft.com/sql/connect/jdbc/building-the-connection-url#named-and-multiple-sql-server-instances), db.namespace SHOULD be set to the combination of instance and database name following the {instance_name}.{database_name} pattern.
In addition to including the instance name in the `db.namespace` attribute, this PR begins to address conforming the activity name to the conventions and starting the activity with required tags.
1. It includes `db.namespace` and …
> [SqlClient] Include instance in `db.namespace` and activity name, start activity with required tags

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
Towards #2222
`db.operation.name` and `db.collection.name` are required attributes when readily available. For stored procedures, they are readily available.
There is some unsettled conversation about whether the attribute name `db.collection.name` makes sense in the context of stored procedure, so the attribute name may change. For now let's just use `db.collection.name`.
In a follow on PR, I plan to propose removing the `SetDbStatementForStoredProcedure` option.
> [SqlClient] For `CommandType.StoredProcedure` set `db.operation.name` and `db.collection.name`

- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSServiceHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSHistogram.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSMeterProvider.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSMonotonicCounter.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Metrics/AWSUpDownCounter.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/SnsRequestContextHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/SqsRequestContextHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Tracing/AWSTraceSpan.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Tracing/AWSTracer.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Tracing/AWSTracerProvider.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Utils.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaHttpUtils.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaUtils.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSMessagingUtils.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Implementation/RequestContextHelperTests.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Implementation/TestsHelper.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientMetricsInstrumentation.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestRequest.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/CustomResponses.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/CustomWebResponse.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/MockHttpRequest.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/MockWebResponse.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/Utils.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/AWSLambdaWrapperTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/Implementation/AWSLambdaHttpUtilsTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/Implementation/AWSMessagingUtilsTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/SampleHandlers.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/SampleLambdaContext.cs
> [repo/AwsInstrumentations] Prepare to .NET9

- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/ActivityHelperTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/HttpContextHelper.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/WebConfigWithLocationTagTransformTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs
> [repo/AspNet] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
- src/Shared/SemanticConventions.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTests.cs
> [SqlClient] Add error.type and db.response.status_code attributes

- src/OpenTelemetry.Instrumentation.GrpcCore/ServerTracingInterceptor.cs
- src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Quartz/QuartzInstrumentationOptions.cs
- src/Shared/DiagnosticSourceSubscriber.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/FoobarService.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreClientInterceptorTests.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreServerInterceptorTests.cs
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcServer.cs
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcTestHelpers/ClientTestHelpers.cs
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcTestHelpers/TestHttpMessageHandler.cs
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcTestHelpers/TrailingHeadersHelpers.cs
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcTests.client.cs
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/GrpcTests.server.cs
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/Services/GreeterService.cs
- test/Shared/TestActivityExportProcessor.cs
> [repo/Grpc*] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.SqlClient/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/README.md
- src/OpenTelemetry.Instrumentation.SqlClient/SqlClientTraceInstrumentationOptions.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
Removes the `SetDbStatementForStoredProcedure` configuration option.
The [database semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/v1.28.0/docs/database/database-spans.md) are nearing stability, there are number of attributes which are required when they are readily available (i.e. no complex parsing or sanitization of query text is necessary). This includes `db.query.text`, `db.operation.name`, and `db.collection.name`.
In the case of stored procedures, no parsing or sanitization is necessary, so the instrumentation needs to capture these attributes.
Note that the readme has not yet been updated with documentation of the new conventions, so it currently only refers to the old `db.statement` attribute.
> [sqlclient] Remove SetDbStatementForStoredProcedure option

- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeInstrumentationOptionsTests.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
> [repo/Runtime] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.Quartz/Implementation/QuartzDiagnosticListener.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/QuartzDiagnosticListenerTests.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/TestJob.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/TestJobExecutionExceptionJob.cs
> [repo/Quartz] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/Implementation/ElasticsearchRequestPipelineDiagnosticListener.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/Customer.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/DependencyInjectionConfigTests.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/InMemoryConnectionWithDownstreamActivity.cs
> [repo/ElasticsearchClient] Prepare to .NET9

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Common.GenevaExporter.props
- src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantExportProcessor.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/Exporter/TLDTraceExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmarks/Exporter/TraceExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
Fixes #1814
* Bump GenevaExporter to `1.10.0-rc.1` SDK
* Utilize the new `Batch(T item)` ctor to remove the need for reflection/dynamic code in `ReentrantExportProcessor`
* Update tests for new obsoletions
> [geneva] Updates for 1.10.0-rc.1

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
* Bump OneCollectorExporter to `1.10.0-rc.1` SDK
> [OneCollector] Bump SDK to 1.10.0-rc.1

- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentationJobFilterAttribute.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/HangfireFixture.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/HangfireInstrumentationJobFilterAttributeTests.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/ProcessorMock.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/TestJob.cs
> [repo/Hangfire] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Http/HttpClientMetrics.cs
- src/OpenTelemetry.Instrumentation.Http/HttpClientTraceInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerMetricsDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/TelemetryHelper.cs
- test/OpenTelemetry.Instrumentation.Http.Benchmarks/Instrumentation/HttpClientInstrumentationBenchmarks.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.Basic.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpOutTestCase.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpTestData.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestActivitySourceTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestTests.Basic.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestTests.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/RepeatHandler.cs
> [repo/Http] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
- src/OpenTelemetry.Instrumentation.SqlClient/SqlClientInstrumentation.cs
- src/OpenTelemetry.Instrumentation.SqlClient/TracerProviderBuilderExtensions.cs
In an upcoming PR we will be adding metric instrumentation. That instrumentation will need to leverage the same `DiagnosticSourceListener` that is used for traces. This PR makes `SqlClientInstrumentation` a singleton because multiple instances of the instrumentation would create duplicate activities.
> [sqlclient] Make SqlClientInstrumentation a singleton

- .github/component_owners.yml
- src/OpenTelemetry.Exporter.Geneva/README.md
- src/OpenTelemetry.Exporter.OneCollector/README.md
Related to https://github.com/open-telemetry/opentelemetry-dotnet/pull/5959.
> Remove Reiley Yang 🐇 from the component owners list👋

- src/OpenTelemetry.Exporter.Geneva/README.md
The default interval, named metricExporterIntervalMilliseconds, is set to 60 seconds in the code, which contrasts with the documentation.
Fixes #
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporterOptions.cs#L15
After PR:
> Correct default MetricExporterIntervalMilliseconds from 20000 to 60000 in documentation

- .github/workflows/ci.yml
- .github/workflows/integration.yml
- .github/workflows/verifyaotcompat.yml
- build/Common.nonprod.props
- build/Common.props
- build/docker-compose.net9.0.yml
- build/scripts/test-aot-compatibility.ps1
- global.json
- opentelemetry-dotnet-contrib.sln
- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/UnixUserEventsDataTransportTests.cs
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/Dockerfile
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/Dockerfile
Towards #2319.
* Added .NET 9 SDK in CI for building projects while minimizing changes: target frameworks are not updated for any projects except for AOT compatibility test. Individual component owners can add support for .NET 9 SDK at their own pace.
* Added support for .NET 9 in AOT compatibility test.
* Updated docker compose to run integration tests for Kafka and StackExchangeRedis to build with .NET 9 SDK in Docker.
* Set [`AnalysisLevel`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-9#latest-updates) to `8.0` to minimize changes in this PR.
* ~[ ] Unit tests added/updated~
* ~[ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes~: components are not upgraded. Only building with new SDK version.
* ~[ ] Changes in public API …
> [repo] Bump SDK to 9.0.100

- README.md
Due to focus on other OpenTelemetry areas, I am unable to spend much time here, and hence moving to Emeritus. Once this is merged, I'll explicitly add my name of some individual component(s) as owner.
> [repo] Move Cijo to Emeritus

- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
* Fix a few spots in GenevaExporter where `MetricPoint` wasn't being accessed/passed by ref
> [geneva] Tweak OtlpProtobufSerializer to access MetricPoint by ref

- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/Implementation/RedisProfilerEntryToActivityConverterTests.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests.csproj
Fixes #2324
[Instrumentation.StackExchangeRedis] Fix tests on .NET9
> [Instrumentation.StackExchangeRedis] Fix tests on .NET9

- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpRequestRouteHelper.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/RouteTestHelper.cs
ASP.NET instrumentation fails to extract route for attribute-based routing, if multiple HTTP methods use the same route template--a common scenario for RESTful APIs. For example:
```csharp
public class WidgetsController : ApiController
{
[Route("api/widgets/{id}")]
public string Get(int id) {...}
[Route("api/widgets/{id}")]
public void Put(int id, [FromBody]string value) {...}
[Route("api/widgets/{id}")]
public void Delete(int id) {...}
}
```
In this case, the `MS_Subroutes` array will have multiple elements, each corresponding to a different HTTP method.
The original code only extracts the route template if there's only one element in the array. The correct thing to do is to just extract the template from the first subroute, since all subroutes have the same template.
It's not possible …
> [Instrumentation.AspNet] Fix multiple routes of same template in attribute-based routing

- build/Common.nonprod.props
- test/OpenTelemetry.Resources.AWS.Tests/Http/ServerCertificateValidationProviderTests.cs
- test/OpenTelemetry.Resources.AWS.Tests/OpenTelemetry.Resources.AWS.Tests.csproj
Fixes #2323
[Resources.AWS] Execute tests against .NET9
Drops unused `SupportedNetTargetsWithoutNet9`
> [Resources.AWS] Execute tests against .NET9

- src/OpenTelemetry.Exporter.OneCollector/Internal/CallbackManager.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/ConnectionStringParser.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/EventFullName.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/EventNameManager.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializationHelper.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializationState.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializer.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/LogRecordCommonSchemaJsonSerializer.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Sinks/WriteDirectlyToTransportSink.cs
- src/OpenTelemetry.Exporter.OneCollector/Internal/Transports/HttpJsonPostTransport.cs
- src/OpenTelemetry.Exporter.OneCollector/Logs/OneCollectorLogExporterOptions.cs
- src/OpenTelemetry.Exporter.OneCollector/OneCollectorExporterTransportOptions.cs
- test/OpenTelemetry.Exporter.OneCollector.Benchmarks/LogRecordCommonSchemaJsonHttpPostBenchmarks.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/CommonSchemaJsonSerializationHelperTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/CommonSchemaJsonSerializationStateTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/EventNameManagerTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/ExtensionFieldInformationManagerTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/HttpJsonPostTransportTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/LogRecordCommonSchemaJsonSerializerTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/OneCollectorLogExporterOptionsTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/OneCollectorLoggerProviderBuilderExtensionsTests.cs
- test/OpenTelemetry.Exporter.OneCollector.Tests/WriteDirectlyToTransportSinkTests.cs
> [repo/OneCollector] Prepare to .NET9

- build/Common.nonprod.props
- build/Common.props
- examples/AspNet/Examples.AspNet.csproj
- examples/grpc.core/Examples.GrpcCore.AspNetCore/Examples.GrpcCore.AspNetCore.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/OpenTelemetry.Instrumentation.GrpcCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.GrpcNetClient.Tests/OpenTelemetry.Instrumentation.GrpcNetClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.Basic.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpClientTests.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestTests.Basic.cs
- test/OpenTelemetry.Instrumentation.Http.Tests/HttpWebRequestTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
Bump internal packages.
Fixes: [xUnit2030](https://xunit.net/xunit.analyzers/rules/xUnit2030) and [xUnit2031](https://xunit.net/xunit.analyzers/rules/xUnit2031)
> [repo] Bump internal packages

- src/OpenTelemetry.Resources.AWS/AWSEBSDetector.cs
- src/OpenTelemetry.Resources.AWS/AWSEC2Detector.cs
- src/OpenTelemetry.Resources.AWS/AWSECSDetector.cs
- src/OpenTelemetry.Resources.AWS/AWSEKSDetector.cs
- src/OpenTelemetry.Resources.AWS/AWSSemanticConventions.cs
Move string literals to be constants in the AWS Semantic Conventions class.  This is in preparation of a larger overhaul in how the AWS libraries will handle Semantic Conventions.
> [Resources.AWS] Move string literals to AWS Semantic Conventions class

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/Implementation/Tracing/AWSTraceSpan.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/AWSLambdaWrapper.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ConfluentKafka/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetryConsumeResultExtensions.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/DiagnosticsMiddleware.cs
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/Implementation/QuartzDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/ClientChannelInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/TelemetryDispatchMessageInspector.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/AWSLambdaWrapperTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/QuartzDiagnosticListenerTests.cs
Fixes #2321
Replace ActivityExtensions.SetStatus by Activity.SetStatus
Following tags will be not added to spans when the exception is recorder:
`otel.status_code` and `otel.status_description`. Both values are handled natively.
Changes affects only pre-released instrumentation packages. It should be safe to merge as is.
> Replace ActivityExtensions.SetStatus by Activity.SetStatus

- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreInstrumentationMeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreMetrics.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/README.md
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/MetricTests.cs
#2360 needs further discussion. It removes metric functionality from a supported target, so it is a breaking change that warrants a major version bump. That said, I don't see any reason to have removed this functionality at all.
This change needs to be reverted. Also, it appears this was released as 1.10.0. A version 1.10.1 will need to be released to fix this breaking change.
Lastly, I noted that #2360 was merged without the approval of an approver or maintainer.
@Kielek @CodeBlanch
> [aspnetcore] Restore metrics instrumentation in netstandard builds

- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.SqlClient/README.md
Follow up #2309 and @#2311
I need a link to put in AutoInstrumentation doc with available list of metrics.
[Instrumentation.SqlClient] Metrics documentation
Some minor fix in AspNet documentation (I think that we are lack of url check in CI)
> [Instrumentation.SqlClient] Metrics documentation

- src/OpenTelemetry.Instrumentation.MySqlData/README.md
- src/OpenTelemetry.Instrumentation.SqlClient/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.SqlClient/README.md
- src/OpenTelemetry.Instrumentation.SqlClient/SqlClientTraceInstrumentationOptions.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs
The attributes gated by `EnableConnectionLevelAttributes` are required. No other language has offered an option to disable these attributes. Removing `EnableConnectionLevelAttributes` to simplify things.
> Remove EnableConnectionLevelAttributes option

- build/scripts/build.psm1
Related to #2410
[repo] Fix FindComponentOwners for latest project in component_owners
Before changes it was not able to detect component owners for the latest record in `component_owners.yml`.
Changes tested locally.
```yml
src/OpenTelemetry.Resources.Gcp/:
- matt-hensley
- pyohannes
src/OpenTelemetry.Sampler.AWS/:
- srprash
- ppittle
test/OpenTelemetry.Exporter.Geneva.Benchmarks/:
- cijothomas
- codeblanch
- rajkumar-rangaraj
```
> [repo] Fix FindComponentOwners for latest project in component_owners

- test/OpenTelemetry.Exporter.Geneva.Tests/Proto/opentelemetry/proto/metrics/v1/metrics.proto
Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.
> [geneva] Update links to openmetrics to reference the v1.0.0 release in proto files

- CONTRIBUTING.md
- README.md
- src/OpenTelemetry.Exporter.InfluxDB/README.md
- src/OpenTelemetry.Extensions.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.AspNetCore/README.md
- src/OpenTelemetry.Instrumentation.Cassandra/README.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/README.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/README.md
- src/OpenTelemetry.Instrumentation.GrpcCore/README.md
- src/OpenTelemetry.Instrumentation.GrpcNetClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.GrpcNetClient/README.md
- src/OpenTelemetry.Instrumentation.Http/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Http/README.md
- src/OpenTelemetry.Instrumentation.MassTransit/README.md
- src/OpenTelemetry.Instrumentation.MySqlData/README.md
- src/OpenTelemetry.Instrumentation.Owin/README.md
- src/OpenTelemetry.Instrumentation.Process/README.md
- src/OpenTelemetry.Instrumentation.Quartz/README.md
- src/OpenTelemetry.Instrumentation.SqlClient/README.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md
- src/OpenTelemetry.PersistentStorage.FileSystem/CHANGELOG.md
Rason: I wanted to fix one of the problematic link, but also considered CI for this.
[Links checker](https://github.com/lycheeverse/lychee-action).
It takes a lot of time for each run. We can consider adding it as a cron. IMO no need to include in every md modification.
Failing only on non-published packages: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/12351829730/job/34467628274
> [documentation] Fix links

- .github/workflows/Component.BuildTest.yml
- .github/workflows/add-labels.yml
- .github/workflows/assign-reviewers.yml
- .github/workflows/automation.yml
- .github/workflows/ci-Exporter.OneCollector-Integration.yml
- .github/workflows/ci.yml
- .github/workflows/core-version-update.yml
- .github/workflows/integration.yml
- .github/workflows/markdownlint.yml
- .github/workflows/post-release.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-packages.yml
- .github/workflows/sanitycheck.yml
- .github/workflows/stale.yml
- .github/workflows/verifyaotcompat.yml
- .github/workflows/yamllint.yml
Workoaround for https://github.com/actions/runner-images/issues/10636#issuecomment-2546225257
[repo] Pin Ubuntu to 22.04
> [repo] Pin Ubuntu to 22.04

- .github/dependabot.yml
- opentelemetry-dotnet-contrib.sln
* Configure dependabot to bump SDK version to latest patch following: https://devblogs.microsoft.com/dotnet/using-dependabot-to-manage-dotnet-sdk-updates/.
> [repo] Allow dependabot to bump SDK patch version

- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInMetricsListener.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNetCore/Implementation/HttpInMetricsListener.cs
- src/OpenTelemetry.Instrumentation.ConfluentKafka/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ConfluentKafka/ConfluentKafkaCommon.cs
- src/OpenTelemetry.Instrumentation.Http/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerMetricsDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Http/Implementation/HttpWebRequestActivitySource.netfx.cs
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationMetrics.cs
- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
Fixes #
[repo] Metrics instrumentations - utilize advice API for histogram boundaries
Values taken from semantic conventions.
Kafka also adds units and descriptions.
> [repo] Metrics instrumentations - utilize advice API for histogram boundaries

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/OpenTelemetry.Instrumentation.SqlClient.csproj
- src/OpenTelemetry.Instrumentation.SqlClient/README.md
- src/Shared/SqlProcessor.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
Fixes #2221 
Performs [sanitization of SQL text](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md#sanitization-of-dbquerytext). First 1000 results are cached. This number is arbitrary. I do not wish to make it configurable yet in this PR though I'm open to choosing a different arbitrary number.
> [SqlClient] Sanitize SQL query text

- src/OpenTelemetry.Instrumentation.AWS/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Resources.AWS/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Resources.AWS/CHANGELOG.md
- src/Shared/AWS/AWSSemanticConventions.Legacy.cs
- src/Shared/AWS/AWSSemanticConventions.cs
- src/Shared/AWS/SemanticConventionVersion.cs
Fixes #
Design discussion issue #  Continuation of #2367
Update the OpenTelemetry.*.AWS libraries to to use Semantic Convention 1.28 and remove the option `SemanticConventionVerisons.Legacy`
We determined that #2367, should not change Semantic Conventions by default, allowing users a non-breaking way to test opting in-to 1.28.
This is a fast follow up PR that removes `SemanticConventionVersions.Legacy` and changes the default to SemanticConventionVersions.V1_28_0. This PR is to be released as a Release Candidate.
This follows the release strategy for other contrib packages that have made similar breaking changes around Semantic Convention stabilization.
> [aws] default to use Semantic Convention 1.28 and remove option Legacy

- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaUtils.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/AWSLambdaWrapperTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/SampleLambdaContext.cs
Fixes #2445
Handle the case is InvokedFunctionArn is null in LambdaContext.
> [OpenTelemetry.Instrumentation.AWSLambda] Do not crash on empty LambdaContext

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs
Fixes #2345
Move code that adds context propagation data to requests into a dedicated method `AddPropagationDataToRequest`, and always run that regardless of sampling decision.
> [Instrumentation.AWS]: always add context propagation data to requests

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
Fixes #2462
Added case when `providerName` has value `"Devart.Data.Oracle.Entity.EFCore"`
> [Instrumentation.EntityFrameworkCore] Add case for providerName when Devart Oracle is used

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
- src/Shared/SemanticConventions.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/Implementation/RedisProfilerEntryToActivityConverterTests.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
Adopt v1.23 database span network attributes. This does not update any other attributes that may be out of date.
> [Instrumentation.StackExchangeRedis] Adopt v1.23 database span network attributes

- build/Common.nonprod.props
- test/OpenTelemetry.Sampler.AWS.Tests/OpenTelemetry.Sampler.AWS.Tests.csproj
Fixes https://github.com/advisories/GHSA-4cv2-4hjh-77rx
It was transitive dependency to WireMock.NET < 1.7.0
[[Sampler.AWS] Bump WireMock.Net to 1.7.0](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/commit/7d16e789cdc2c74cbafc57b0ee739d99abea7c6d)
[Bump xunit to 2.9.3](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/commit/34a6ffc61b5226da1291ef65dcf3be51f7b19f31)
> [Sampler.AWS] Tests - Bump WireMock.Net to 1.7.0

- src/OpenTelemetry.Extensions.AWS/README.md
List OpenTelemetry.Extensions.AWS as Stable in the README.md
> List OpenTelemetry.Extensions.AWS as Stable

- src/OpenTelemetry.Resources.AWS/README.md
List OpenTelemetry.Resources.AWS as Stable in the README.md
> List OpenTelemetry.Resources.AWS as Stable

- src/OpenTelemetry.Instrumentation.AWS/README.md
List OpenTelemetry.Instrumentation.AWS as Stable in the README.md
> List OpenTelemetry.Instrumentation.AWS as Stable

- .github/component_owners.yml
- src/OpenTelemetry.Extensions.Enrichment/README.md
Fixes # n/a
Design discussion issue # n/a
Updates ownership of the OpenTelemetry.Extensions.Enrichment component. @xakep139 left Microsoft last year and I am supposed to work on this component from now on.
> Update code ownership for OpenTelemetry.Extensions.Enrichment

- .github/component_owners.yml
- src/OpenTelemetry.Exporter.Geneva/README.md
Moving on from owning this component, to focus on other languages.
> Remove Cijo Thomas from GenevaExporter codeowners

- src/OpenTelemetry.PersistentStorage.Abstractions/CHANGELOG.md
- src/OpenTelemetry.PersistentStorage.FileSystem/CHANGELOG.md
Preparing for a release which will be built with the [deterministic flag](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#deterministic).
Amended CHANGELOG to call out a previous change.
When the packages were released last time, the `dotnet pack` command ignored the existing build with `Deterministic` flag due to the `--no-build` being commented out.
Release tag for OpenTelemetry.PersistentStorage.Abstractions 1.0.0 is [PersistentStorage.Abstractions-1.0.0](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases/tag/PersistentStorage.Abstractions-1.0.0).
* Relevant code for building is at https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/PersistentStorage.Abstractions-1.0.0/.github/workflows/package-Pers …
> [Persistent Storage] Amend change log to include the deterministic flag enablement

- README.md
* Add Rajkumar Rangaraj as maintainer.
Raj is working as a component owner of couple of the packages. What is more, he is the maintainer and main author of the latest SDK and the maintainer of the auto-instrumentation package. New responsibilities should streamline releasing process whole of the ecosystem.
@rajkumar-rangaraj, thanks for what you are doing now. Looking for more :- )
> [repo] Add Rajkumar Rangaraj as maintainer

- src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md
Follow up #2539
[Instrumentation.AspNetCore] Missing PR link in CHANGELOG
> [Instrumentation.AspNetCore] Missing PR link in CHANGELOG

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
[Instrumentation.StackExchangeRedis] only netstandard2.0 references System.Reflection.Emit.Lightweight
It is available both for .NET8+ and .NET Framework without additional packages.
https://github.com/dotnet/linker/issues/2715 is already fixed - pragma can be removed
> [Instrumentation.StackExchangeRedis] only netstandard2.0 references System.Reflection.Emit.Lightweight

- .github/workflows/Component.BuildTest.yml
- .github/workflows/add-labels.yml
- .github/workflows/assign-reviewers.yml
- .github/workflows/ci-Exporter.OneCollector-Integration.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/core-version-update.yml
- .github/workflows/dotnet-format.yml
- .github/workflows/integration.yml
- .github/workflows/markdownlint.yml
- .github/workflows/post-release.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-packages.yml
- .github/workflows/sanitycheck.yml
- .github/workflows/stale.yml
- .github/workflows/verifyaotcompat.yml
- .github/workflows/yamllint.yml
Preventing problems similar to https://www.cisa.gov/news-events/alerts/2025/03/18/supply-chain-compromise-third-party-tj-actionschanged-files-cve-2025-30066-and-reviewdogaction
In the auto-instrumentation repository we have such configuration for a while.
Scripts doing most of the job https://github.com/mheap/pin-github-action
> [repo] GitHub Actions hardening

- .github/workflows/ci.yml
Disable pack for project that do not produce any NuGet packages.
Relates to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2658#issuecomment-2742476285.
> [repo] Disable pack for Shared.Tests

- .github/component_owners.yml
- README.md
- src/OpenTelemetry.Exporter.Geneva/README.md
- src/OpenTelemetry.Exporter.OneCollector/README.md
- src/OpenTelemetry.Extensions/README.md
- src/OpenTelemetry.Instrumentation.Owin/README.md
- src/OpenTelemetry.Instrumentation.Wcf/README.md
Stepping down as a maintainer to free up time to work on new things. We're in good hands with @alanwest, 
@Kielek, and @rajkumar-rangaraj!
For components where I was the owner I gave them to maintainers. The exception being OneCollectorExporter where I added @rajkumar-rangaraj (we will co-own that for now).
> [repo] Move Blanch to approver

- .github/component_owners.yml
- src/OpenTelemetry.Resources.Gcp/README.md
Remove Johannes Tax (pyohannes) from Resources.Gcp component owners. Johannes is no longer available to maintain this package.
> [chore] Update Resources.Gcp component owners

- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlTestData.cs
The SqlClient unit tests need to be improved. There's a lot of holes in coverage and the existing tests make it difficult to surmise what we do and do not cover.
This is the first PR of a few more to come which simply aims to refactor the existing tests making them more readable and making coverage more apparent.
Currently, we have this mega test. It's like a one test to rule them all kind of test which, in my opinion, needlessly tests a bazillion config combinations. This test has become exceedingly difficult to debug.
In this first PR, I'm extracting the testing of the `Enrich` configuration into its own test. I'll do the same for the .NET Framework tests in a different PR.
> [SqlClient] Refactor Enrich test

- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlTestData.cs
Similar to #2714 simplifying SqlClient tests
This PR extracts the testing of enabling trace vs. metric instrumentation into its own test.
> [SqlClient] Refactor tests enabling trace/metric instrumentation

- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlTestData.cs
Similar to #2714 simplifying SqlClient tests
This PR extracts the testing of the configuration enabling capture of `db.query.text` and `db.statement` (old conventions).
> Refactor tests validating configuration for capture of db.query.text

- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlTestData.cs
Similar to #2714 simplifying SqlClient tests
This PR refactors the `RecordException` test removing the `MemberData`. The primary purpose of the test is to validate the recording of exception span events, so I also removed the metric validation.
> [SqlClient] Refactor tests validating RecordException

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj
Set max support AWS SDK version to V3
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2719
> Set max support AWS SDK version to V3

- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
- src/Shared/SemanticConventions.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlEventSourceTests.netfx.cs
Introduces the new `db.system.name` attribute when the new conventions are enabled.
We're still lacking great test coverage, and this PR does not seek to improve upon that. Coming soon, though!
> [SqlClient] Support new DB convention: `db.system.name`

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- src/Shared/SemanticConventions.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTests.cs
Implementing the new [`db.stored_procedure.name` attribute](https://github.com/open-telemetry/semantic-conventions/pull/2037).
The `db.operation.name`, `db.collection.name`, and `db.query.text` attributes have been removed when `CommandType` = `StoredProcedure` because they are no longer applicable.
Side note, we have an odd scenario for .NET Framework users. `CommandType` is not known, so `db.query.text` will still be used even for stored procedures. This requires documentation, but is beyond the scope of this PR.
> [sql] Implement updates to new semantic conventions for stored procedures

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/AspNetParentSpanCorrector.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/AspNetParentSpanCorrectorTests.netfx.cs
Fixes
- AspNetParentSpanCorrector always sets the request headers to read-only, even if it was originally writable. This breaks any existing application code that makes further changes to the request headers.
AspNetParentSpanCorrector.OnRequestStarted now records the original state of `HttpContext.Request.Headers.IsReadOnly`, and always restores the original value to the property when done writing the headers.
> [Instrumentation.Wcf] Restore aspnet headers read-only state

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/DiagnosticsMiddleware.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/DiagnosticsMiddlewareTests.cs
Fixes #2731
Fixes incorrect `url.query` attribute due to usage of IOwinRequest Query property which returns a collection. 
This was introduced with https://github.com/open-telemetry/opentelemetry-dotnet-contrib/commit/d5a630fe62c72be42f49309709f6a77c2058df22.
In addition this fixes the query string redaction.
> [Instrumentation.Owin] fix incorrect url.query attribute

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/Shared/SqlProcessor.cs
- test/OpenTelemetry.Contrib.Shared.Tests/SqlProcessorTestCases.json
Fixes an issue that throws `IndexOutOfRangeException` in `SqlProcessor` when the SQL statement ends with the beginning of a keyword such as `UPDATE`.
Example of SQL statement: `SELECT U.Id from Users U`
> [SqlClient] fix IndexOutOfRangeException in SqlProcessor

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientTestCases.json
I originally removed the `db.operation.name` attribute in #2693, but forgot to add it back after the final result of this discussion https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2693#discussion_r2069225825.
> Add db.operation.name attribute

- src/OpenTelemetry.Instrumentation.AWS/Implementation/SnsRequestContextHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/SqsRequestContextHelper.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Implementation/RequestContextHelperTests.cs
Fixes #2808 
Check if SNS/SQS `MessageAttributes` is null and initialize as needed so that trace context can be injected.
> Initialize SNS/SQS MessageAttributes if needed to inject trace context

- test/OpenTelemetry.Instrumentation.AWS.Tests/Implementation/RequestContextHelperTests.cs
The following two unit tests looked like they were missing assertions based on my understanding (which could be wrong, please let me know) of the intent of the tests:
- `SQS_AddAttributes_MessageAttributesWithTraceParent_TraceStateNotInjected`
- `SNS_AddAttributes_MessageAttributesWithTraceParent_TraceStateNotInjected`
> `public void ..._MessageAttributesWithTraceParent_...()`
> // if at least one attribute is already present...
My understand of the above is that `originalRequest.MessageAttributes` should have the `traceparent` attribute rather than be empty.
> `public void ..._TraceStateNotInjected()`
> // ... the whole injection is skipped.
My understanding of the above is that the `originalRequest.MessageAttributes` after `AddAttributes` is called should not have the `tracestate` …
> Fix AWS SQS/SNS TraceStateNotInjected unit tests

- global.json
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisInstrumentationOptions.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
Fixes #2803
- Added a `Filter` option (in line with conventions that most libraries in this repo follow) to `StackExchangeRedisInstrumentationOptions`.
> Add `Filter` option to `StackExchangeRedisInstrumentationOptions`

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Internal/MsgPack/MsgPackTraceExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/MsgPackTraceExporterTests.cs
Fixes #
[HTTP semconv](https://github.com/open-telemetry/semantic-conventions/blob/v1.28.0/docs/http/http-spans.md#http-server-semantic-conventions): Combination of `url.scheme`, `server.address`, `server.port`, `url.path` and `url.query` attributes for HTTP server spans.
> [Exporter.Geneva] Add httpUrl for HTTP server spans

- test/OpenTelemetry.Resources.ProcessRuntime.Tests/ProcessRuntimeDetectorTests.cs
Update assertion to not fail if a preview or release candidate version of .NET is being used.
See #2822.
> [Resources.ProcessRuntime] Allow preview versions

- test/OpenTelemetry.Instrumentation.Wcf.Tests/RunAsAdminTheoryAttribute.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryPropagationTests.netfx.cs
- Skip `TelemetryContextPropagatesTest` if the tests are run as a non-elevated user.
- Move `ServiceHost` setup to its own class and use per-test so that the operation is deferred until after the skip check has determined that the test should run.
> [WCF] Skip ServiceHost tests if non-elevated

- test/OpenTelemetry.Instrumentation.Hangfire.Tests/HangfireInstrumentationJobFilterAttributeTests.cs
- Avoid `InvalidOperationException` by copying collection before passing to `Any()`.
- Refactor `while` loop to improve readability.
Have also created this PR to avoid the problem in the library the tests use: https://github.com/perrich/Hangfire.MemoryStorage/pull/47
> [Hangfire] Fix flaky test

- build/Common.props
- src/OpenTelemetry.Instrumentation.Cassandra/CHANGELOG.md
In the 3.1.16 version of Cassandra the upper bound limit on [System.Threading.Tasks.Dataflow](https://www.nuget.org/packages/System.Threading.Tasks.Dataflow/) has been known to cause conflicts on newer TFM so package has been bumped 1 minor to address that
> [Instrumentation.Cassandra] Bump min Cassandra package to 3.17.0

- .github/component_owners.yml
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/README.md
Fixes #888.
@matt-hensley and I are happy to take on the component ownership for the OpenTelemetry.Instrumentation.EntityFrameworkCore as part of our OpenTelemetry work at Grafana.
Add component owners for OpenTelemetry.Instrumentation.EntityFrameworkCore.
> [Instrumentation.EntityFrameworkCore] Add component owners

- .github/dependabot.yml
Update dependabot configuration to keep the SDK versions in the Dockerfiles up-to-date on a weekly basis to match the .NET SDK in `global.json`.
> [Infra] Update Dockerfiles with dependabot

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/OpenTelemetry.Instrumentation.EntityFrameworkCore.csproj
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkIntegrationTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/Item.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/ItemsContext.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
Fixes #1764
Takes over from #2280 which went stale. ~~Just need to add tests.~~
> [Instrumentation.EFCore] Support use with SqlClient Instrumentation

- src/OpenTelemetry.Instrumentation.ConfluentKafka/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ConfluentKafka/OpenTelemetryConsumeResultExtensions.cs
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/TracingTests.cs
Fixes #2843 
Rethrow exception on ConsumeAndProcessMessageAsync extension message
> [Instrumentation.ConfluentKafka] rethrow exception on consume and process

- test/OpenTelemetry.Instrumentation.AWS.Tests/AWSClientInstrumentationOptionsTests.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/AssemblyInfo.cs
Fix flaky AWS instrumentation tests ([example](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/15870949396/job/44747162596)).
```text
[xUnit.net 00:00:00.73]       Assert.Equal() Failure: Values differ
[xUnit.net 00:00:00.73]     OpenTelemetry.Instrumentation.AWS.Tests.TestAWSClientInstrumentation.TestBedrockRuntimeInvokeModelSuccessful [FAIL]
[xUnit.net 00:00:00.73]       Expected: amazon.titan-text-express-v1
[xUnit.net 00:00:00.73]       Actual:   null
[xUnit.net 00:00:00.73]       Stack Trace:
[xUnit.net 00:00:00.73]         /home/runner/work/opentelemetry-dotnet-contrib/opentelemetry-dotnet-contrib/test/OpenTelemetry.Instrumentation.AWS.Tests/TestAWSClientInstrumentation.cs([64](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/158 …
```
> [Infra] Fix flaky test

- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/FoobarService.cs
Attempt to fix [test failure](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/15895059614/job/44824744896?pr=2866#step:8:35) if an async unary call completes before the call can be disposed.
```text
[xUnit.net 00:00:00.95]     OpenTelemetry.Instrumentation.GrpcCore.Tests.GrpcCoreClientInterceptorTests.AsyncUnaryDisposed [FAIL]
[xUnit.net 00:00:00.95]       Assert.Contains() Failure: Filter not matched in collection
[xUnit.net 00:00:00.95]       Collection: [["activityidentifier"] = a9f98[36](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/15895059614/job/44824744896?pr=2866#step:8:37)5-03c2-4222-a7fe-591c6a85ac06, ["rpc.system"] = "grpc", ["rpc.service"] = "OpenTelemetry.Instrumentation.GrpcCore.Tests.Fooba"···, ["rpc.method"] = …
```
> [Grpc] Fix flaky test

- build/Common.prod.props
Add package README files.
Fixes #2228
Adapted from open-telemetry/opentelemetry-dotnet#5885.
> [Infra] Add package READMEs

- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTestsFixture.cs
Update tests to latest CU of SQL Server 2022.
> [SqlClient] Update test container

- README.md
Martin has been actively contributing in [not only the main repo](https://github.com/open-telemetry/opentelemetry-dotnet/pull/6383), but also the contrib repo. I wish to propose Martin as an approver in this repo as well.
Thank you, Martin, for your contributions in improving this project, reviewing PRs, and responding to issues. Your expertise is valued, and as such, I ask that you join us as an approver.
> Add Martin Costello as Approver

- build/docker-compose.net8.0.yml
- build/docker-compose.net9.0.yml
- test/OpenTelemetry.Instrumentation.Cassandra.Tests/docker-compose.yml
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/docker-compose.yml
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/docker-compose.yml
Avoid obsolete warning from Docker Compose by removing the `version` properties.
> [Infra] Remove version from compose files

- .github/workflows/stale.yml
See https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2923#pullrequestreview-3054330365.
Exclude issues and pull requests labelled with `keep-open` from the stale automation.
> [Infra] Exclude keep-open label from stale

- CONTRIBUTING.md
Propagates changes from https://github.com/open-telemetry/opentelemetry-dotnet/pull/6414
Needed for OpenSSF Best Practices
> [docs] Contributing - reporting bug/feature requests

- .github/workflows/codeql-analysis.yml
Mirror of https://github.com/open-telemetry/opentelemetry-dotnet/pull/6415.
- Scan pushes to main to resolve https://github.com/open-telemetry/opentelemetry-dotnet-contrib/security/code-scanning/40.
- Scan PRs to avoid introducing new issues.
- Use `build-mode: none` to avoid need to compile the code for C#.
- Enable analysis for GitHub Actions.
- Add job that allows only one status to be required for PRs so new languages can be added without reconfiguration.
> [Infra] Improve CodeQL analysis

- .github/workflows/add-labels.yml
- build/scripts/add-labels.psm1
- If a blank issue is opened (which has no tags) (e.g. #2960), avoid the labelling workflow [failing](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/16629013955).
- Use environment variables instead of interpolation.
> [Infra] Fix labelling for blank issues

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/OpenTelemetry.Instrumentation.EntityFrameworkCore.csproj
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.SqlClient/OpenTelemetry.Instrumentation.SqlClient.csproj
- src/Shared/SqlConnectionDetails.cs
- test/OpenTelemetry.Contrib.Shared.Tests/OpenTelemetry.Contrib.Shared.Tests.csproj
- test/OpenTelemetry.Contrib.Shared.Tests/SqlConnectionDetailsTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkIntegrationTests.cs
Fixes #3010
- Make `SqlConnectionDetails` shared for reuse for EFCore.
- Use pattern matching to avoid call through `Nullable<T>.Value`.
- Use `SqlConnectionDetails` to set the `server.port` resource attribute for EFCore.
- Extend the EFCore integration tests to cover old and new database semantic conventions.
> [EFCore] Set server.port attribute 

- .github/component_owners.yml
- src/OpenTelemetry.Extensions.AWS/README.md
- src/OpenTelemetry.Instrumentation.AWS/README.md
- src/OpenTelemetry.Instrumentation.AWSLambda/README.md
- src/OpenTelemetry.Resources.AWS/README.md
- src/OpenTelemetry.Sampler.AWS/README.md
Handles https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2969#issuecomment-3201738596
Transfer AWS component ownership from @ppittle to @normj.
> [AWS] Norm Johanson - component owner

- src/OpenTelemetry.Instrumentation.AspNetCore/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreInstrumentationMeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreInstrumentationTracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreTraceInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/CHANGELOG.md
- test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/3014
Add ASP.NET Core telemetry metrics and traces for .NET 10
> Add ASP.NET Core telemetry metrics and traces for .NET 10

- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkIntegrationTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTests.cs
- test/Shared/DockerHelper.cs
- test/Shared/DockerPlatform.cs
- test/Shared/EnabledOnDockerPlatformFactAttribute.cs
Split out the implementation in `[EnabledOnDockerPlatformTheory]` to allow for a `[EnabledOnDockerPlatformFact]`.
Cherry-picked from #3015.
> [Infra] Add EnabledOnDockerPlatformFact

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaResourceDetector.cs
- src/OpenTelemetry.Instrumentation.AWSLambda/Implementation/AWSLambdaUtils.cs
- src/Shared/AWS/AWSSemanticConventions.Base.cs
- src/Shared/AWS/AWSSemanticConventions.Legacy.cs
- src/Shared/AWS/AWSSemanticConventions.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/AWSLambdaWrapperTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/SampleLambdaContext.cs
Set the [`faas.instance`](https://github.com/open-telemetry/semantic-conventions/blob/v1.28.0/docs/faas/faas-spans.md) and [`faas.max_memory`](https://github.com/open-telemetry/semantic-conventions/blob/v1.28.0/model/faas/registry.yaml#L54) attributes for AWS Lambda functions, which are both recommended.
> [AWSLambda] Add faas.instance and faas.max_memory

- src/OpenTelemetry.Instrumentation.SqlClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlEventSourceListener.netfx.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTests.cs
Fixes #3033
Ensure any current activity is stopped if only metrics is enabled but a global activity listener is registered.
I've manually verified the original issue is resolved and that .NET isn't affected by the same issue.
> [SqlClient] Stop Activity.Current if present

- src/OpenTelemetry.Instrumentation.GrpcNetClient/README.md
- src/OpenTelemetry.Instrumentation.SqlClient/README.md
- src/OpenTelemetry.Instrumentation.Wcf/README.md
Follow-up to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2986#issuecomment-3164209206.
- Add a note to the WCF readme that the RPC conventions are in development.
- Update gRPC and SqlClient notes to use "in Development" not "Experimental".
> [WCF] Add development note to README

- .github/workflows/publish-packages.yml
Follow up to #2816
It should fix Publish to MyGet step as
```log
dotnet nuget push "./artifacts/package/release/*.nupkg" --api-key ${env:API_KEY} --skip-duplicate --source ${env:SOURCE}
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
env:
PROJECT_PATH: opentelemetry-dotnet-contrib.proj
BUILD_COMPONENT: 
DOTNET_ROOT: C:\Program Files\dotnet
MYGET_TOKEN_EXISTS: true
API_KEY: ***
SOURCE: https://www.myget.org/F/opentelemetry/api/v2/package
error: File does not exist (./artifacts/package/release/*.nupkg).
Error: Process completed with exit code 1.
```
> [infra] Fix Use Artifacts Output layout

- .github/workflows/publish-packages.yml
The ZIP artifact is now flattened, so the `Packages` subdirectory no longer exists.
> [Infra] Fix release workflow

- .github/workflows/ci.yml
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkIntegrationTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTests.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTestsFixture.cs
- test/Shared/DockerHelper.cs
- Update to the latest release of Testcontainers.
- Update to the latest SQL Server container image.
- Remove SQL Edge as it is out of support.
- Fix tests not being skipped if Docker is not installed and failing instead.
Have manually checked that the Ubuntu jobs are running the Docker tests. Windows still skips as the Linux engine is not available, and macOS ARM64 images do not have Docker installed at all.
> [Infra] Update Testcontainers

- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/OpenTelemetry.Instrumentation.SqlClient.Tests.csproj
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/SqlClientIntegrationTestsFixture.cs
- test/OpenTelemetry.Instrumentation.SqlClient.Tests/sqlserver.Dockerfile
Follow-up to https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/3063#discussion_r2319182153.
- Get the SQL Server container image to use via a Dockerfile so dependabot/renovate can keep it up-to-date.
- Remove redundant comment.
> [Infra] Use Dockerfile for SQL container version

- src/OpenTelemetry.Instrumentation.AspNet/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AspNet/AspNetMetricsInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs
Towards #2909
Change Enrich options to make it consistent with other Enrich methods.
> [Instrumentation.AspNet] Rename Enrich metrics options

- src/OpenTelemetry.OpAmp.Client/CHANGELOG.md
- src/OpenTelemetry.OpAmp.Client/Internal/FrameProcessor.cs
- src/OpenTelemetry.OpAmp.Client/Internal/OpAmpClient.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Transport/WebSocket/WsReceiver.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Transport/WebSocket/WsTransmitter.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Transport/WebSocket/WsTransport.cs
- test/OpenTelemetry.OpAmp.Client.Tests/WsTransportTest.cs
* Fixes namespace errors
* Adds net framework support for WebSocket transport
> [OpAMP.Client] WebSocket Transport for NetFx

- test/OpenTelemetry.Resources.AWS.Tests/AWSECSDetectorTests.cs
Replace usage of `IWebHost` with `IHost`, which is marked as obsolete in .NET 10.
Cherry-picked from #2822.
Documentation: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/10/webhostbuilder-deprecated
> [Resources.AWS] Replace IWebHost with IHost in tests

- src/OpenTelemetry.OpAmp.Client/CHANGELOG.md
- src/OpenTelemetry.OpAmp.Client/Internal/FrameBuilder.cs
- src/OpenTelemetry.OpAmp.Client/Internal/FrameDispatcher.cs
- src/OpenTelemetry.OpAmp.Client/Internal/IFrameBuilder.cs
- src/OpenTelemetry.OpAmp.Client/Internal/OpAmpClient.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Services/Heartbeat/ComponentHealthStatus.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Services/Heartbeat/HealthReport.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Services/Heartbeat/HeartbeatService.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Services/IBackgroundService.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Settings/ConnectionType.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Settings/HeartbeatSettings.cs
- src/OpenTelemetry.OpAmp.Client/Internal/Settings/OpAmpClientSettings.cs
- src/OpenTelemetry.OpAmp.Client/OpenTelemetry.OpAmp.Client.csproj
- test/OpenTelemetry.OpAmp.Client.Tests/FrameDispatcherTests.cs
- test/OpenTelemetry.OpAmp.Client.Tests/HeartbeatServiceTests.cs
- test/OpenTelemetry.OpAmp.Client.Tests/Mocks/MockListener.cs
- test/OpenTelemetry.OpAmp.Client.Tests/Mocks/MockTransport.cs
Adds heartbeats to support http transport scenario.
There is no client side api yet to provide info about components etc. Only reports static heartbeats.
> [OpAMP.Client] Add heartbeats

- .github/workflows/publish-packages.yml
Use double quotes so that environment variables are expanded.
Otherwise the files are downloaded to the literal path `${GITHUB_WORKSPACE}/artifacts/${GITHUB_REF_NAME}-packages.zip`.
> [Infra] Fix quotes in curl command for artifact download

- .github/workflows/automation.yml
- .github/workflows/core-version-update.yml
- .github/workflows/post-release.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-packages.yml
- .github/workflows/sync-sql-tests.yml
- build/scripts/post-release.psm1
- build/scripts/prepare-release.psm1
Towards https://github.com/open-telemetry/community/issues/2863
Importantly for this repo, it will allow you to remove write permissions for the shared opentelemetrybot user and instead limit the access only via fine-grained "otelbot dotnet contrib" app (which I've just created).
`vars.AUTOMATION_USERNAME` will need to be updated to `otelbot`
`vars.AUTOMATION_EMAIL` will need to be updated to `197425009+otelbot@users.noreply.github.com`
Note: the basic `otelbot` app (not `otelbot dotnet contrib` app) is still used for commit username/email since that app has been registered to pass EasyCLA
> [infra] Migrate to otelbot

- src/OpenTelemetry.OpAmp.Client/Internal/FrameProcessor.cs
- src/OpenTelemetry.OpAmp.Client/Internal/OpAmpClientEventSource.cs
* Adds invalid WebSocket frame logging.
> [OpAMP.Client] Invalid WebSocket frame logging

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/.publicApi/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModuleOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentation.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentationTracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/AspNetParentSpanCorrector.cs
- src/Shared/RequestDataHelper.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/ActivityHelperTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
Towards #2909
Goal - make following attributes available on startup:
* `http.request.method`,
* `server.address`,
* `server.port`,
* `url.scheme`,
* `url.path`,
* `user_agent.original`,
* `url.query`.
Side effect: breaking changes in IIS module.
It is not responsible for creating activity. It delegates it to the instrumentation package.
2 reasons for this design:
- keep separation of managing activity context in IIS module and OpenTelemetry deatails in instrumentation package
- Instrumentation package allows to configure DisableRedactionUrlQuery through IConfiguration. I do not found good way to set it on the IIS module side.
While reviewing you can check commit-by-commit towards this implementation. The last one is the big commit only.
> [Instrumentation.AspNet] Include some attributes in sampling process

- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
[AspNet] HttpInListener.CalculateDurationFromTimestamp - remove optional parameter
> [AspNet] HttpInListener.CalculateDurationFromTimestamp - remove optional parameter

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityDateTimeHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
Fixes #3166
[AspNet.Telemetry] Fix end of time by utilizing implementation from https://github.com/dotnet/runtime/blob/75662173e3918f2176b74e467dc8e41d4f01d4d4/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.DateTime.netfx.cs
Alternative approach - use some reflection/delegates to call internally visible methods.
> [AspNet.Telemetry] Fix end of time
