open-telemetry/opentelemetry-dotnet-contrib

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Instrumentation.Azure/AzureClientsInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Azure/AzurePipelineInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Azure/Class1.cs
- src/OpenTelemetry.Instrumentation.Azure/Implementation/AzureSdkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Azure/Implementation/PropertyFetcher.cs
- src/OpenTelemetry.Instrumentation.Azure/OpenTelemetry.Instrumentation.Azure.csproj
- src/OpenTelemetry.Instrumentation.Azure/OpenTelemetryBuilderExtensions.cs
No tests existed in main repo, none added here as well.
(will followup with Azure folks if this is required and can be moved into Microsoft owned repo,. Parking it here for temporary)
> Lift and shift Azure instrumentation from main repo

- .github/workflows/dotnet-core-linux.yml
- .github/workflows/dotnet-core-win.yml
- .github/workflows/dotnet-core.yml
- build/Common.prod.props
- build/Common.test.props
- build/OpenTelemetryContrib.prod.ruleset
- build/OpenTelemetryContrib.test.ruleset
- build/stylecop.json
- opentelemetry-dotnet-contrib.proj
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Exporter.Stackdriver/AssemblyInfo.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/Constants.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ExporterStackdriverEventSource.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/GoogleCloudResourceUtils.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/SpanExtensions.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/StackdriverStatsConfiguration.cs
- src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Exporter.Stackdriver/StackdriverTraceExporter.cs
- src/OpenTelemetry.Exporter.Stackdriver/Utils/CommonUtils.cs
- src/OpenTelemetry.Instrumentation.Azure/AzureClientsInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Azure/AzurePipelineInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Azure/Class1.cs
- src/OpenTelemetry.Instrumentation.Azure/Implementation/AzureSdkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Azure/OpenTelemetry.Instrumentation.Azure.csproj
- test/OpenTelemetry.Exporter.Stackdriver.Tests/Impl/StackdriverStatsConfigurationTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/OpenTelemetry.Exporter.Stackdriver.Tests.csproj
- Adding same stylecop that we have in OT .NET
- Adding tests for netcoreapp2.1
- Updating workflows to accept that
- Updating nugets
- Clean up classes / namespaces
> Adding StyleCop

- src/OpenTelemetry.Exporter.Stackdriver/TracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Azure/AzureClientsInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Azure/AzurePipelineInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Azure/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/Impl/StackdriverStatsConfigurationTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/StackdriverExporterTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/TestActivityProcessor.cs
- Adding missing extensions to Exporter/Instrumentation projects
> adding missing extensions

- README.md
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Exporter.Stackdriver/README.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/EntityFrameworkInstrumentation.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/EntityFrameworkInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/PropertyFetcher.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/OpenTelemetry.Instrumentation.EntityFrameworkCore.csproj
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Properties/AssemblyInfo.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/README.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCoreT/EntityFrameworkDiagnosticListenerTests.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCoreT/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- Adding EFCore instrumentation from https://github.com/open-telemetry/opentelemetry-dotnet/pull/929
> Adding EFCore Instrumentation

- src/OpenTelemetry.Contrib.Exporter.Stackdriver/StackdriverTraceExporter.cs
- test/OpenTelemetry.Contrib.Exporter.Stackdriver.Tests/Implementation/StackdriverStatsConfigurationTests.cs
- test/OpenTelemetry.Contrib.Exporter.Stackdriver.Tests/Shared/TestExporter.cs
- test/OpenTelemetry.Contrib.Exporter.Stackdriver.Tests/StackdriverExporterTests.cs
Hopefully fixes #53 
- Test StackdriverExporter error handling.
> Add StackDriver test for RpcException

- build/Common.props
- src/Directory.Build.targets
- src/OpenTelemetry.Contrib.Exporter.Stackdriver/OpenTelemetry.Contrib.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/OpenTelemetry.Contrib.Extensions.AWSXRay.csproj
- src/OpenTelemetry.Contrib.Instrumentation.Azure/OpenTelemetry.Contrib.Instrumentation.Azure.csproj
- src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch/OpenTelemetry.Contrib.Instrumentation.ElasticsearchClient.csproj
- src/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore.csproj
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/OpenTelemetry.Contrib.Instrumentation.MassTransit.csproj
- Removing shared dependency on OpenTelemetry
- Adding individual dependency on OpenTelemetry to each project
> Splitting OpenTelemetry dependency to individual projects

- src/OpenTelemetry.Contrib.Extensions.AWSXRay/OpenTelemetry.Contrib.Extensions.AWSXRay.csproj
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/Trace/AWSXRayPropagator.cs
- Upgraded the OpenTelemetry version to 1.0.0-rc2.
- Changed from using IPropagator to TextMapPropagator
> Upgraded to OTel 1.0.0-rc2 for AWSXRay

- CONTRIBUTING.md
- README.md
* Added guidance for contributing a new project based on the recent changes.
* Added list of approvers and maintainers
* Added the badge for contributors to the repo.
> Updating contribution guidance

- src/OpenTelemetry.Contrib.Extensions.AWSXRay/README.md
Updated `README.md` file for AWS XRay extension package
> Updated README.md

- .github/workflows/package-Instrumentation.GrpcCore.yml
Missed .Tests on the end of the dotnet test step.
> [instrumentation Grpc.Core] Trying to fix the github workflow

- .github/workflows/package-Instrumentation.EntityFrameworkCore.yml
- Fix the step to run unit tests for EntityFrameworkCore instrumentation
> Fix the test step for EntityFrameworkCore Instrumentation

- src/OpenTelemetry.Contrib.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.GrpcCore/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/CHANGELOG.md
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/CHANGELOG.md
- Added empty CHANGELOG.md to instrumentation libraries
> Add CHANGELOG.md to instrumentation libraries

- CODEOWNERS
@CodeBlanch I know you are already covered by approvers list, but listing explicitly
@SergeyKanzhelev please confirm your approval
> Add code owner to WCF and Stackdriver

- src/OpenTelemetry.Contrib.Exporter.Stackdriver/OpenTelemetry.Contrib.Exporter.Stackdriver.csproj
- src/OpenTelemetry.Contrib.Exporter.Stackdriver/TracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Contrib.Extensions.AWSXRay/OpenTelemetry.Contrib.Extensions.AWSXRay.csproj
- src/OpenTelemetry.Contrib.Instrumentation.Elasticsearch/OpenTelemetry.Contrib.Instrumentation.ElasticsearchClient.csproj
- src/OpenTelemetry.Contrib.Instrumentation.GrpcCore/OpenTelemetry.Contrib.Instrumentation.GrpcCore.csproj
- src/OpenTelemetry.Contrib.Instrumentation.MassTransit/OpenTelemetry.Contrib.Instrumentation.MassTransit.csproj
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/OpenTelemetry.Contrib.Instrumentation.Wcf.csproj
- src/OpenTelemetry.Contrib.Shared/OpenTelemetry.Contrib.Shared.csproj
- test/OpenTelemetry.Contrib.Exporter.Stackdriver.Tests/StackdriverExporterTests.cs
- test/OpenTelemetry.Contrib.Instrumentation.Wcf.Tests/OpenTelemetry.Contrib.Instrumentation.Wcf.Tests.csproj
- Updated OTel SDK and core components version to latest prerelease `1.1.0-beta1`
- Updated non-core components version to `1.0.0-rc3`
> Update the OTel Sdk version

- src/OpenTelemetry.Contrib.Instrumentation.AWSLambda/CHANGELOG.md
- Added CHANGELOG for AWSLambda repo for release `v1.0.1`
> Added CHANGELOG for AWSLambda repo

- src/OpenTelemetry.Contrib.Instrumentation.AWSLambda/CHANGELOG.md
- Update AWSLambda Release to v1.1.0-beta1
> Update AWSLambda Release to v1.1.0-beta1

- src/OpenTelemetry.Contrib.Extensions.AWSXRay/CHANGELOG.md
- Update `CHANGELOG` for AWS Extension Repo
> Update CHANGELOG for AWS Extension Repo

- src/OpenTelemetry.Contrib.PersistentStorage/FileBlob.cs
- src/OpenTelemetry.Contrib.PersistentStorage/FileStorage.cs
- test/OpenTelemetry.Contrib.PersistentStorage.Tests/FileBlobTests.cs
- test/OpenTelemetry.Contrib.PersistentStorage.Tests/FileStorageTests.cs
Updating as per PR review
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/171#discussion_r782586822
> Rename LocalFileStorage to FileStorage, LocalFileBlob to FileBlob

- CONTRIBUTING.md
Add prompt to add onesself to CODEOWNERS when contributing new work
> CODEOWNERS Prompt

- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetrics.cs
- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetricsOptions.cs
- test/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests/RuntimeMetricsOptionsTests.cs
- test/OpenTelemetry.Contrib.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Add metric for `process.cpu.time`.
> Add cpu time

- src/OpenTelemetry.Contrib.Instrumentation.Runtime/RuntimeMetrics.cs
Change the unit names to follow UCUM https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units
> Change unit to UCUM

- .github/workflows/linux-ci.yml
- .github/workflows/windows-ci.yml
- Add separate workflows for Windows and Linux
**Note**: We can remove `pr_build` workflow after we merge this.
> Add separate workflows for Windows and Linux

- .github/workflows/dotnet-format.yml
- .github/workflows/markdownlint.yml
- .github/workflows/sanitycheck.yml
> Update GitHub workflows

- .github/workflows/package-Instrumentation.Quartz.yml
- CODEOWNERS
- src/OpenTelemetry.Instrumentation.Quartz/README.md
- Rename Quartz Instrumentation related files to remove the word Contrib
> Rename Quartz Instrumentation related files to remove the word Contrib

- src/OpenTelemetry.Instrumentation.Quartz/README.md
- Add link to the Nuget package
- Update the installation command to include `--prerelease`
> Update Quartz Instrumentation README

- .markdownlint.yaml
- src/OpenTelemetry.Contrib.Instrumentation.Wcf/README.md
Propagate changes from https://github.com/open-telemetry/opentelemetry-dotnet/pull/3049
> Documentation - allow long lines for tables and code blocks

- src/OpenTelemetry.Contrib.Exporter.Stackdriver/CHANGELOG.md
- Update CHANGELOG for 1.0.0-beta.2 release
> Update CHANGELOG for 1.0.0-beta.2 release

- build/Common.prod.props
- src/OpenTelemetry.Contrib.Instrumentation.AWSLambda/OpenTelemetry.Contrib.Instrumentation.AWSLambda.csproj
- src/OpenTelemetry.Contrib.Instrumentation.GrpcCore/OpenTelemetry.Contrib.Instrumentation.GrpcCore.csproj
- src/OpenTelemetry.Contrib.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
> Add common package tags

- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- Update CHANGELOG for Quartz Instrumentation
> Update CHANGELOG for Quartz Instrumentation

- .github/component_owners.yml
> Update component owners file

- .github/workflows/package-Extensions.PersistentStorage.yml
- opentelemetry-dotnet-contrib.sln
- Add release workflow for PersistentStorage extension
> Add release workflow for PersistentStorage extension

- .github/dependabot.yml
Same as https://github.com/open-telemetry/opentelemetry-dotnet/pull/3170.
Stealing from https://github.com/open-telemetry/opentelemetry-cpp/pull/1246.
> GitHub action update bot

- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/301
> Use `EnableAnalysis` in Geneva Exporter

- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/ConnectionStringBuilder.cs
- src/OpenTelemetry.Exporter.Geneva/EtwDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/ExporterEventSource.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaBaseExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaExporterHelperExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLoggingExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaMetricExporterExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaMetricExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/IDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/IMetricDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/MessagePackSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/MetricEtwDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/MetricSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/MetricUnixDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/ReentrantExportProcessor.cs
- src/OpenTelemetry.Exporter.Geneva/Schema.cs
- src/OpenTelemetry.Exporter.Geneva/ServiceProviderExtensions.cs
- src/OpenTelemetry.Exporter.Geneva/UnixDomainSocketDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/UnixDomainSocketEndPoint.cs
Towards #276 
To get opinions and perform a smaller scale change before deciding to do this for other projects in the repo.
> File scope namespaces for Geneva Exporter

- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests.csproj
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/OpenTelemetry.Contrib.Instrumentation.AWS.Tests.csproj
- test/OpenTelemetry.Contrib.Instrumentation.AWSLambda.Tests/OpenTelemetry.Contrib.Instrumentation.AWSLambda.Tests.csproj
- test/OpenTelemetry.Exporter.Geneva.Benchmark/OpenTelemetry.Exporter.Geneva.Benchmark.csproj
- test/OpenTelemetry.Exporter.Geneva.Stress/OpenTelemetry.Exporter.Geneva.Stress.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- test/OpenTelemetry.Extensions.PersistentStorage.Tests/OpenTelemetry.Extensions.PersistentStorage.Tests.csproj
- test/OpenTelemetry.Instrumentation.Quartz.Tests/OpenTelemetry.Instrumentation.Quartz.Tests.csproj
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/282
> Cleanup versions and paths in csproj

- opentelemetry-dotnet-contrib.sln
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/304#issuecomment-1099855331
> Add geneva packaging workflow to opentelemetry-dotnet-contrib.sln

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
Please review @open-telemetry/dotnet-maintainers :)
> Geneva Exporter Release v1.2.4

- .github/ISSUE_TEMPLATE/comp_contrib_extensions_awsxray.md
- .github/ISSUE_TEMPLATE/comp_contrib_instrumentation_aws.md
- .github/ISSUE_TEMPLATE/comp_contrib_instrumentation_awslambda.md
- .github/ISSUE_TEMPLATE/comp_exporter_stackdriver.md
- .github/ISSUE_TEMPLATE/comp_extensions.md
- .github/ISSUE_TEMPLATE/comp_extensions_azuremonitor.md
- .github/ISSUE_TEMPLATE/comp_extensions_persistentstorage.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_elasticsearchclient.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_entityframeworkcore.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_grpccore.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_hangfire.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_masstransit.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_mysqldata.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_owin.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_quartz.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_runtime.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_wcf.md
- CONTRIBUTING.md
* Added the issue templates for all packages in this repo
* Updated the contributing.md doc with instructions (also with some minor fixes)
> Add more issue templates and update contributing.md

- .github/component_owners.yml
I'm going to start working on getting this component to Stable.
> Add OpenTelemetry.Instrumentation.Runtime component

- .github/codecov.yml
Stealing from https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.github/codecov.yml.
> Tweak codecov.yml

- README.md
Fixing several obvious doc issues.
> Editorial changes to the README.md

- src/OpenTelemetry.Exporter.Geneva/README.md
Towards https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/287
Add readme to Geneva Exporter
> exporter/geneva - Add README.md

- .github/workflows/dotnet-format-md.yml
Forgot to include the hyphen and the GitHub action would hang on waiting for the status.
> Fix dotnet-format-md.yml

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/OpenTelemetry.Instrumentation.ElasticsearchClient.csproj
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests.csproj
* Updated OTel SDK package version to 1.2.0
* Update minimum full framework support to net462
* Run tests on net5.0, and net6.0
> Upgrade ElasticsearchClient support to Otel 1.2.0

- .github/ISSUE_TEMPLATE/comp_instrumentation_stackexchangeredis.md
- .github/workflows/package-Instrumentation.StackExchangeRedis.yml
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
Follow-up to #366 
- Add package release workflow
- Add ISSUE_TEMPLATE
> Add workflow and issue template for RedisInstrumentation

- src/OpenTelemetry.Contrib.Shared/Api/SpanHelper.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/ElasticsearchClientInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/Implementation/ElasticsearchRequestPipelineDiagnosticListener.cs
> Add MaxDbStatementLength option with default of 4096

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.3.0-beta.1 release
> [Exporter.Geneva] Update CHANGELOG for 1.3.0-beta.1 release

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- Update CHANGELOG for 1.0.0-beta.1 release
> Update CHANGELOG for 1.0.0-beta.1 release

- .github/workflows/package-Instrumentation.Hangfire.yml
- opentelemetry-dotnet-contrib.sln
- Add workflow for Hangfire instrumentation
> Add workflow for Hangfire instrumentation

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.3.0-beta.2
> [Exporter.Geneva] Update CHANGELOG for 1.3.0-beta.2

- examples/redis/Examples.StackExchangeRedis/Examples.StackExchangeRedis.csproj
- examples/redis/Examples.StackExchangeRedis/Program.cs
- examples/redis/Examples.StackExchangeRedis/README.md
- opentelemetry-dotnet-contrib.sln
- Add example for StackExchangeRedis instrumentation
> [Instrumentation.StackExchangeRedis] Add example for StackExchangeRedis instrumentation

- .github/workflows/linux-ci.yml
- .github/workflows/windows-ci.yml
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/Resources/Http/TestHandler.cs
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/Resources/Http/TestServerCertificateValidationProvider.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/ConnectionStringBuilderTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/MessagePackSerializerTests.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/UnixDomainSocketDataTransportTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanSerializerTests.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs
This PR demonstrates one of the ways to fix CI.
- Create an additional testing step which would only run the tests which have the trait `Platform`
> [Solution] Fix build CI

- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanSerializerTests.cs
> [Exporter.Instana] Fix broken unit test 

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Release a new alpha version 0.2.0-alpha.1 for #335.
Update CHANGELOG.md
> Release Runtime instrumentation version 0.2.0-alpha.1

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/Implementation/ElasticsearchRequestPipelineDiagnosticListener.cs
Fixes #.
Fix Elasticsearch MaxDbStatementLength option
> fix Elasticsearch MaxDbStatementLength option

- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- Remove unnecessary preprocessor directives
> [Exporter.Geneva] Remove unnecessary preprocessor directives

- src/OpenTelemetry.Extensions.PersistentStorage.Abstractions/OpenTelemetry.Extensions.PersistentStorage.Abstractions.csproj
- src/OpenTelemetry.Extensions.PersistentStorage/OpenTelemetry.Extensions.PersistentStorage.csproj
> Target net462 on windows only [PersistentStorage.Extensions]

- src/OpenTelemetry.Extensions.PersistentStorage.Abstractions/CHANGELOG.md
- src/OpenTelemetry.Extensions.PersistentStorage/CHANGELOG.md
Fixes #.
Updating changelog for release.
> Update changelog [PersistentStorage.Extensions]

- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
This covers the remaining instruments after #454.
> Improve the runtime instrumentation naming and description

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Extensions.PersistentStorage.Abstractions/CHANGELOG.md
- Add stale workflow to the .sln file
> Add stale workflow to the solution file

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Release Runtime instrumentation version 1.0.0-rc.1
Updated `README.md`.
> [Instrumentation.Runtime] Release Runtime instrumentation version 1.0.0-rc.1

- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
Update the CHANGELOG to add a new version.
> [Instrumentation.MySql] update CHANGELOG.md

- src/OpenTelemetry.Contrib.Extensions.AWSXRay/CHANGELOG.md
> Minor edit to CHANGELOG

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
> Instrumentation-Runtime minor tweaks to description

- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
> [Exporter.Geneva] Remove TCP and UDP related options

- src/OpenTelemetry.Exporter.Stackdriver/README.md
- Fix labels
- Remove text containing `stackdriver-sample` as there was no link for it in the doc
> [Exporter.Stackdriver] Fix markdown

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Release Runtime instrumentation version 1.0.0-rc.2
> [Instrumentation.Runtime] Release Runtime instrumentation version 1.0.0-rc.2

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/OpenTelemetry.Instrumentation.StackExchangeRedis.csproj
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests.csproj
Fixes: N/A.
This package is the next candidate to utilize in AutoIntrumentation. I have go through the code to understand how it is working. Please check following improvements:
1. Reference Otel Api by `OpenTelemetryApiPkgVer`
1. Typo fix
1. Cleanup code
* simplify if condition
* remove unused default parameter in private method
* remove unused variable
1. Tests - bump `OpenTelemetry.Extensions.Hosting` to 1.0.0-rc9.4
> [Instrumentation.StackExchangeRedis] Code cleanup

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/OpenTelemetry.Instrumentation.Hangfire.Tests.csproj
- Updated OTel SDK package version to 1.3.0
> Updated OTel SDK package version to 1.3.0

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
#475 included some breaking changes in metrics names and descriptions. There should have been an entry for this in the CHANGELOG.md.
> [Instrumentation.Runtime] Amend `CHANGELOG.md` for 1.0.0-rc.2

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
-  Update CHANGELOG for 1.0.0-beta.3 release
> [Exporter.Stackdriver] Update CHANGELOG for 1.0.0-beta.3 release

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Release Runtime instrumentation version `1.0.0-rc.3`.
> [Instrumentation.Runtime] Release Runtime instrumentation version 1.0.0-rc.3

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- Update release date for `1.0.0-rc.3`
> [Instrumentation.Runtime] Update release date for 1.0.0-rc.3

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [Exporter.Geneva] Update CHANGELOG

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.3.0 release
> [Exporter.Geneva] Update CHANGELOG for 1.3.0 release

- src/OpenTelemetry.Extensions.Docker/CHANGELOG.md
* Update CHANGELOG for 1.0.0-beta.1 release
> [Extensions.Docker] Update CHANGELOG for 1.0.0-beta.1 release

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentation.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/StackExchangeRedisCallsInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/Implementation/RedisProfilerEntryToActivityConverterTests.cs
- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/StackExchangeRedisCallsInstrumentationTests.cs
Towards #276
File scoped namespace for StackExchangeRedis
Consider to use ignore whitespace feature while reviewing this PR.
> File scoped namespace for StackExchangeRedis

- src/OpenTelemetry.Instrumentation.Wcf/Implementation/ActionMetadata.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/WcfInstrumentationActivitySource.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/WcfInstrumentationConstants.cs
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/WcfInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryClientMessageInspector.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryContractBehaviorAttribute.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryDispatchMessageInspector.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryEndpointBehavior.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryEndpointBehaviorExtensionElement.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryServiceBehavior.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryServiceBehaviorExtensionElement.cs
- src/OpenTelemetry.Instrumentation.Wcf/TracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Wcf/WcfEnrichEventNames.cs
- src/OpenTelemetry.Instrumentation.Wcf/WcfInstrumentationOptions.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryClientMessageInspectorTests.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryDispatchMessageInspectorForOneWayOperationsTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/TelemetryDispatchMessageInspectorTests.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/ErrorHandler.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/Tools/ErrorHandlerServiceBehavior.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/IServiceContract.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/Service.netfx.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/ServiceClient.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/ServiceRequest.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/WCF/ServiceResponse.cs
Towards  #276.
[WCF.Intrumentation] Filescoped namespace
> [WCF.Intrumentation] Filescoped namespace

- src/OpenTelemetry.Instrumentation.Quartz/Implementation/QuartzDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.Quartz/Implementation/QuartzInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.Quartz/Implementation/TagName.cs
- src/OpenTelemetry.Instrumentation.Quartz/OperationName.cs
- src/OpenTelemetry.Instrumentation.Quartz/QuartzInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Quartz/QuartzJobInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Quartz/TraceProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/QuartzDiagnosticListenerTests.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/TestJob.cs
- test/OpenTelemetry.Instrumentation.Quartz.Tests/TestJobExecutionExceptionJob.cs
Towards #276.
[Instrumenation.Quartz] File scoped namespace
> [Instrumenation.Quartz] File scoped namespace

- src/OpenTelemetry.Instrumentation.Owin/AppBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Owin/Implementation/DiagnosticsMiddleware.cs
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationActivitySource.cs
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.Owin/OwinEnrichEventType.cs
- src/OpenTelemetry.Instrumentation.Owin/OwinInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Owin/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/Controllers/TestController.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/DiagnosticsMiddlewareTests.cs
Towards #276.
[Instrumenation.Owin] File scoped namespace
> [Instrumenation.Owin] File scoped namespace

- src/OpenTelemetry.Instrumentation.MySqlData/MySqlActivitySourceHelper.cs
- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentation.cs
- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataTraceCommand.cs
- src/OpenTelemetry.Instrumentation.MySqlData/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/MySqlDataTests.cs
Towards #276.
[Instrumenation.MySqlData] File scoped namespace
> [Instrumenation.MySqlData] File scoped namespace

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/Implementation/WcfInstrumentationActivitySource.cs
Towards #484
[Instrumenation.WCF] Adjust activity source name to common pattern.
> [Instrumenation.WCF] Adjust activity source name

- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentationConstants.cs
- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentationJobFilterAttribute.cs
- src/OpenTelemetry.Instrumentation.Hangfire/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/HangfireFixture.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/HangfireInstrumentationJobFilterAttributeTests.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/TestJob.cs
Towards #276.
[Instrumenation.Hangfire] File scoped namespace
> [Instrumenation.Hangfire] File scoped namespace

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/Implementation/OwinInstrumentationActivitySource.cs
Towards #484
[Instrumenation.OWIN] Adjust activity source name to common pattern.
> [Instrumenation.OWIN] Adjust activity source name

- src/OpenTelemetry.Instrumentation.MassTransit/Implementation/DisplayNameHelper.cs
- src/OpenTelemetry.Instrumentation.MassTransit/Implementation/MassTransitDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.MassTransit/Implementation/MassTransitInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.MassTransit/Implementation/MassTransitSemanticConventions.cs
- src/OpenTelemetry.Instrumentation.MassTransit/Implementation/TagName.cs
- src/OpenTelemetry.Instrumentation.MassTransit/MassTransitInstrumentation.cs
- src/OpenTelemetry.Instrumentation.MassTransit/MassTransitInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.MassTransit/OperationName.cs
- test/OpenTelemetry.Instrumentation.MassTransit.Tests/MassTransitInstrumentationTests.cs
- test/OpenTelemetry.Instrumentation.MassTransit.Tests/TestConsumer.cs
- test/OpenTelemetry.Instrumentation.MassTransit.Tests/TestMessage.cs
Towards #276.
[Instrumenation.MassTransit] File scoped namespace
> [Instrumenation.MassTransit] File scoped namespace

- src/OpenTelemetry.Instrumentation.GrpcCore/AsyncStreamReaderProxy.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ClientStreamWriterProxy.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ClientTracingInterceptor.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ClientTracingInterceptorOptions.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/Extensions.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/GrpcCoreInstrumentation.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/RpcScope.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/SemanticConventions.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ServerStreamWriterProxy.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ServerTracingInterceptor.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/ServerTracingInterceptorOptions.cs
- src/OpenTelemetry.Instrumentation.GrpcCore/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/FoobarService.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreClientInterceptorTests.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/GrpcCoreServerInterceptorTests.cs
- test/OpenTelemetry.Instrumentation.GrpcCore.Tests/InterceptorActivityListener.cs
Towards #276.
[Instrumenation.GrpcCore] File scoped namespace
> [Instrumenation.GrpcCore] File scoped namespace

- src/OpenTelemetry.Instrumentation.EventCounters/EventCounterListener.cs
- src/OpenTelemetry.Instrumentation.EventCounters/EventCounterMetricsOptions.cs
- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.EventCounters/MeterProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCounterListenerTests.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/MeterProviderBuilderExtensionsTests.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/TestEventCounter.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/TestIncrementingEventCounter.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/TestIncrementingPollingCounter.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/TestPollingEventCounter.cs
Towards #276.
[Instrumenation.EventCounters] File scoped namespace
> [Instrumenation.EventCounters] File scoped namespace

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/EntityFrameworkInstrumentation.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/EntityFrameworkInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/EntityFrameworkDiagnosticListenerTests.cs
Towards #276.
[Instrumenation.EntityFrameworkCore] File scoped namespace
> [Instrumenation.EntityFrameworkCore] File scoped namespace

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/AspNetTelemetryEventSource.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModule.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModuleOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentation.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetMetrics.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/AspNetInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInMetricsListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNet/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/ActivityHelperTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/HttpContextHelper.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/WebConfigTransformTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/WebConfigWithLocationTagTransformTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/BasicTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/EventSourceTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs
Towards #276.
[Instrumenation.AspNet] File scoped namespace
> [Instrumenation.AspNet] File scoped namespace

- src/OpenTelemetry.Extensions.PersistentStorage.Abstractions/NotNullWhenAttribute.cs
- src/OpenTelemetry.Extensions.PersistentStorage.Abstractions/PersistentBlob.cs
- src/OpenTelemetry.Extensions.PersistentStorage.Abstractions/PersistentBlobProvider.cs
- src/OpenTelemetry.Extensions.PersistentStorage.Abstractions/PersistentStorageAbstractionsEventSource.cs
- src/OpenTelemetry.Extensions.PersistentStorage/FileBlob.cs
- src/OpenTelemetry.Extensions.PersistentStorage/FileBlobProvider.cs
- src/OpenTelemetry.Extensions.PersistentStorage/PersistentStorageEventSource.cs
- src/OpenTelemetry.Extensions.PersistentStorage/PersistentStorageHelper.cs
- test/OpenTelemetry.Extensions.PersistentStorage.Tests/FileBlobProviderTests.cs
- test/OpenTelemetry.Extensions.PersistentStorage.Tests/FileBlobTests.cs
Towards #276.
[Extensions.PersistentStorage] File scoped namespace
> [Extensions.PersistentStorage] File scoped namespace

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/ElasticsearchClientInstrumentation.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/ElasticsearchClientInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/Implementation/ElasticsearchInstrumentationEventSource.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/Implementation/ElasticsearchRequestPipelineDiagnosticListener.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/Customer.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/ElasticsearchClientTests.cs
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/InMemoryConnectionWithDownstreamActivity.cs
Towards #276.
[Instrumenation.Elasticsearch] File scoped namespace
> [Instrumenation.Elasticsearch] File scoped namespace

- src/OpenTelemetry.Instrumentation.Runtime/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeInstrumentationOptionsTests.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Towards #276.
[Instrumenation.Runtime] File scoped namespace
> [Instrumenation.Runtime] File scoped namespace

- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ActivityExtensions.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/Constants.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ExporterStackdriverEventSource.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/GoogleCloudResourceUtils.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/StackdriverStatsConfiguration.cs
- src/OpenTelemetry.Exporter.Stackdriver/StackdriverTraceExporter.cs
- src/OpenTelemetry.Exporter.Stackdriver/TracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Exporter.Stackdriver/Utils/CommonUtils.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/Implementation/StackdriverStatsConfigurationTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/StackdriverExporterTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/TestActivityProcessor.cs
Towards #276.
[Exporter.Stackdriver] File scoped namespace
> [Exporter.Stackdriver] File scoped namespace

- src/OpenTelemetry.Instrumentation.Runtime/README.md
The current title reads very mouthful.
> nit: rewording

- src/OpenTelemetry.Extensions.AzureMonitor/ApplicationInsightsSampler.cs
- test/OpenTelemetry.Extensions.AzureMonitor.Tests/ApplicationInsightsSamplerTests.cs
Towards #276.
[Extensions.AzureMonitor] File scoped namespace
> [Extensions.AzureMonitor] File scoped namespace

- .github/workflows/dotnet-format.yml
Fixes N/A
nit: fix name for action in dotnet format workflow
> nit: fix name for action in dotnet format workflow

- .github/workflows/dotnet-core-cov.yml
- .github/workflows/package-Exporter.Geneva.yml
- Remove unnecessary test filters
> Remove unnecessary test filters

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
PR for the new release of WCF instrumentation.
* [ x] Appropriate `CHANGELOG.md` updated for non-trivial changes
~~* [ ] Design discussion issue #~~
> WCF instrumentation release

- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/LogExporterBenchmarks.cs
- Update GenevaLogExporter Benchmarks
> Update GenevaLogExporter Benchmarks

- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
> [Exporter.Geneva] Add dedicated test for Exception and EventId serialization

- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
Making the code simpler + easier to search, no change to the actual logic.
> Simplify the code

- .github/workflows/package-Extensions.AzureMonitor.yml
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.Process/ProcessMetrics.cs
- Add package release workflow for `OpenTelemetry.Extensions.AzureMonitor`
> [Extensions.AzureMonitor] Add package release workflow for OpenTelemetry.Extensions.AzureMonitor

- src/OpenTelemetry.Extensions.AzureMonitor/OpenTelemetry.Extensions.AzureMonitor.csproj
- src/OpenTelemetry.Extensions.AzureMonitor/README.md
- Add Minver config
- Update README
> [Extensions.AzureMonitor] Update .csproj and README

- src/OpenTelemetry.Extensions.AzureMonitor/CHANGELOG.md
Fixes #.
OpenTelemetry.Extensions.AzureMonitor - Add PR link to changelog
> OpenTelemetry.Extensions.AzureMonitor - Add PR link to changelog

- src/OpenTelemetry.Extensions.AzureMonitor/CHANGELOG.md
Follow up #633 
Add 462 TargetFramework to changelog.
> Add 462 TargetFramework to changelog.

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
Follow up to #631
Added info about update of OTel SDK.
Minor fixes.
> Changelog for update to 1.3.1 OTel SDK release

- src/OpenTelemetry.Instrumentation.MassTransit/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MassTransit/OpenTelemetry.Instrumentation.MassTransit.csproj
- test/OpenTelemetry.Instrumentation.MassTransit.Tests/MassTransitInstrumentationTests.cs
- test/OpenTelemetry.Instrumentation.MassTransit.Tests/OpenTelemetry.Instrumentation.MassTransit.Tests.csproj
First step to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1215
> [Instrumentation.MassTransit] Bump OTel, .NET frameworks, cleanup

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
> Bump to 1.3.1 -fix changelog

- src/OpenTelemetry.Instrumentation.MassTransit/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.MassTransit/OpenTelemetry.Instrumentation.MassTransit.csproj
Fixes N/A.
Enable Public API for MassTransit.
> [Instrumentation.MassTransit] PublicApi verification

- src/OpenTelemetry.Extensions.AzureMonitor/ApplicationInsightsSampler.cs
- src/OpenTelemetry.Extensions.AzureMonitor/README.md
Updating the documentation with examples of how to use the `ApplicationInsightsSampler`
- added example in xml doc.
- added example to Readme
> [Extensions.AzureMonitor] update documenation

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
Updating Owin project CHANGELOG for release.
/cc @utpilla
> [Owin] 1.0.0-rc.3 release update

- build/Common.nonprod.props
- build/Common.props
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanTest.cs
- Update versions of common packages
> Update package versions

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- Update CHANGELOG for Exporter.Stackdriver
> Update CHANGELOG for Exporter.Stackdriver

- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
> [ASPNET] Update changelog for release

- test/OpenTelemetry.Extensions.PersistentStorage.Tests/FileBlobProviderTests.cs
follow up https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/601#issuecomment-1224193358
> [Extensions.PersistentStorage] Stabilize tests

- .github/workflows/windows-ci-md.yml
- Fix Windows workflow for markdown file changes
> Fix Windows workflow for markdown file changes

- examples/runtime-instrumentation/Program.cs
- examples/runtime-instrumentation/runtime-instrumentation.csproj
> [examples-instrumentation-runtime] -- Switch to new Prometheus exporter in runtime example

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/README.md
(Dependency: finishing of this PR: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/687)
Release Process instrumentation version 0.1.0-alpha.1
> [Instrumentation.Process] Release Process instrumentation version 0.1.0-alpha.1

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- Add publish workflow
- Add release date to the CHANGELOG
> [Instrumentation.Process] Add publish workflow

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaMetricExporterTests.cs
- Add support for exporting Histogram Min and Max
> [Exporter.Geneva] Update GenevaMetricExporter to export Histogram Min Max

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update GenevaExporter CHANGELOG for 1.4.0-beta.2 release
> [Exporter.Geneva] Update GenevaExporter CHANGELOG for 1.4.0-beta.2 release

- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
Fixes N/A.
Request release mainly due to #692.
> [Instrumentation.MySqlData] Release 1.0.0-beta.4

- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
@open-telemetry/dotnet-contrib-maintainers 🙂
> [Instrumentation.EventCounters] Release 1.0.0-alpha.1

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
Flaky, and affecting CI stability.
> Ignore event counter test

- .github/workflows/integration-md.yml
> Add md file only workflow for integrationtest

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.4.0-beta.3 release
> [Exporter.Geneva] Update CHANGELOG for 1.4.0-beta.3 release

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
> Disable more flaky tests

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/OpenTelemetry.Instrumentation.Runtime.csproj
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- src/OpenTelemetry.Instrumentation.Runtime/RuntimeMetrics.cs
- test/OpenTelemetry.Instrumentation.Runtime.Tests/OpenTelemetry.Instrumentation.Runtime.Tests.csproj
Also adjusted changelog to better reflect the change.
> Remove netcoreapp3.1 from Runtime instrumentation

- test/OpenTelemetry.Instrumentation.Runtime.Tests/RuntimeMetricsTests.cs
> Nit fixes to tests

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
> disable eventcounter tests

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.4.0-beta.4
> [Exporter.Geneva] Update CHANGELOG for 1.4.0-beta.4

- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- Update MinVer tag prefix
- Update CHANGELOG
> [OpenTelemetry.Extensions] Update MinVer tag prefix

- src/OpenTelemetry.Instrumentation.EventCounters/CHANGELOG.md
- Update CHANGELOG for 1.0.0-alpha.2 release
> [Instrumentation.EventCounters] Update CHANGELOG for 1.0.0-alpha.2 release

- .github/workflows/ci-md.yml
> Update ci-md.yml - Add back `strategy`

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
Release Process instrumentation version 1.0.0-alpha.1
> [Instrumentation.Process] Release Process instrumentation version 1.0.0-alpha.1

- README.md
- Fix build badge to use the new workflow
> Fix build badge to use the new workflow

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [Exporter.Geneva] Release 1.4.0-beta.5

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes N/A.
Release 1.1.0-beta.1 for `Instrumentation.Runtime`.
> [Instrumentation.Runtime] Release 1.1.0-beta.1

- CONTRIBUTING.md
- build/RELEASING.md
Fixes #775/
Document PublicApi Analyzer
> Document PublicApi Analyzer

- .github/workflows/package-Instrumentation.Runtime.yml
- Only restore the required project
> Update package workflow for instrumentation runtime

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
> Fix changelog for OpenTelemetry.Instrumentation.EntityFrameworkCore

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
> [Exporter.Stackdriver] Release 1.0.0-beta.4

- .github/workflows/ci-md.yml
- .github/workflows/ci.yml
- .github/workflows/dotnet-core-cov.yml
- .github/workflows/dotnet-format-md.yml
- .github/workflows/dotnet-format.yml
- .github/workflows/integration-md.yml
- .github/workflows/integration.yml
- .github/workflows/markdownlint.yml
- .github/workflows/sanitycheck.yml
To make it easier in the future to create branches for hotfixes or feature development. Similar to https://github.com/open-telemetry/opentelemetry-dotnet/pull/3708.
> [repo] Run workflows for any branch starting with "main"

- .github/workflows/ci-md.yml
- .github/workflows/ci.yml
- .github/workflows/dotnet-core-cov.yml
- .github/workflows/dotnet-format-md.yml
- .github/workflows/dotnet-format.yml
- .github/workflows/integration-md.yml
- .github/workflows/integration.yml
- .github/workflows/markdownlint.yml
- .github/workflows/sanitycheck.yml
- Rename `extension*` to `extensions*`
> Update workflows to rename branch to extensions

- test/OpenTelemetry.Extensions.Tests/Trace/AutoFlushActivityProcessorTests.cs
- Use a unique `ActivitySource` for each unit test
> [OpenTelemetry.Extensions] Update unit tests

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update GenevaExporter CHANGELOG for 1.4.0-beta.6
> [Exporter.Geneva] Update GenevaExporter CHANGELOG for 1.4.0-beta.6

- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaLogExporterTests.cs
- Update unit tests for scopes to cover the CustomeFields scenario as mentioned in this PR: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/736
> [Exporter.Geneva] Update unit tests for scopes

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
… 1.4.0-rc.1
Fixes N/A
Releases with OTel 1.4.0-rc.1
> [Instrumentation.Process, Instrumentation.Runtime] Releases with OTel 1.4.0-rc.1

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
> [Instrumentation.Runtime] - relese request typo fix

- .github/workflows/package-Exporter.Instana.yml
- .github/workflows/package-Extensions.AWSXRay.yml
- .github/workflows/package-Extensions.PersistentStorage.Abstractions.yml
- .github/workflows/package-Instrumentation.AWS.yml
- .github/workflows/package-Instrumentation.AWSLambda.yml
- .github/workflows/package-Instrumentation.AspNet.TelemetryHttpModule.yml
- .github/workflows/package-Instrumentation.AspNet.yml
- .github/workflows/package-Instrumentation.GrpcCore.yml
- .github/workflows/package-Instrumentation.Hangfire.yml
- .github/workflows/package-Instrumentation.MySqlData.yml
- .github/workflows/package-Instrumentation.Owin.yml
- .github/workflows/package-Instrumentation.Quartz.yml
- Update package publish workflows to setup .NET 7
> Update package publish workflows to setup .NET 7

- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
Addressing https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/826#discussion_r1052565369
> Update param modifier for `SerializeHistogramBucket`

- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs
- src/OpenTelemetry.Instrumentation.EventCounters/MeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.EventCounters/OpenTelemetry.Instrumentation.EventCounters.csproj
- Enable Code Analysis for EventCounters instrumentation
- Add a Dispose method implementation
> [Instrumentation.EventCounters] Enable Code Analysis for EventCounters Instrumentation

- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- Remove unnecessary code analysis warning exceptions
> [Exporter.Geneva] Remove unnecessary code analysis warning exceptions

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
- Fix unit tests by disposing EventSources, EventCounters, and MeterProvider
> [Instrumentation.EventCounters] Update EventCounter unit tests

- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/LogExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/MetricExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/TraceExporterBenchmarks.cs
- test/OpenTelemetry.Exporter.Geneva.Benchmark/OpenTelemetry.Exporter.Geneva.Benchmark.csproj
- test/OpenTelemetry.Exporter.Geneva.Benchmark/README.md
- Update GenevaExporter benchmarks
> [Exporter.Geneva] Update GenevaExporter benchmarks

- build/Common.nonprod.props
- examples/AspNet/Examples.AspNet.csproj
- examples/grpc.core/Examples.GrpcCore.AspNetCore/Examples.GrpcCore.AspNetCore.csproj
- examples/owin/Examples.Owin.csproj
- examples/wcf/README.md
- examples/wcf/client-core/Examples.Wcf.Client.Core.csproj
- examples/wcf/client-core/Examples.Wcf.Client.DotNet.csproj
- examples/wcf/client-netframework/Examples.Wcf.Client.NetFramework.csproj
- examples/wcf/server-netframework/Examples.Wcf.Server.NetFramework.csproj
- opentelemetry-dotnet-contrib.sln
- test/OpenTelemetry.Contrib.Extensions.AWSXRay.Tests/AssemblyInfo.cs
- test/OpenTelemetry.Exporter.Geneva.Stress/OpenTelemetry.Exporter.Geneva.Stress.csproj
- test/OpenTelemetry.Exporter.Geneva.Tests/OpenTelemetry.Exporter.Geneva.Tests.csproj
- test/OpenTelemetry.Extensions.AzureMonitor.Tests/OpenTelemetry.Extensions.AzureMonitor.Tests.csproj
- test/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests/OpenTelemetry.Instrumentation.EntityFrameworkCore.Tests.csproj
- test/OpenTelemetry.Instrumentation.Owin.Tests/DiagnosticsMiddlewareTests.cs
- test/OpenTelemetry.Instrumentation.Wcf.Tests/OpenTelemetry.Instrumentation.Wcf.Tests.csproj
- Update versions of common packages used in tests and examples
- Update Wcf example project
> Update versions of common packages used in tests and examples

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/README.md
Related to #865 
Update readme about new elasticsearch client library.
> [Instrumentation.Elasticsearch] Update readme - new library

- src/OpenTelemetry.Instrumentation.Wcf/README.md
Documentation for #478
Add known issues section in WCF documentation.
> Add known issues to wcf documentation

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes N/A.
Release request with Releases with OTel 1.4.0-rc.2.
No other changes in packages.
> [Instrumentation.Process, Instrumentation.Runtime] Releases with OTel 1.4.0-rc.2

- test/OpenTelemetry.Exporter.Geneva.Tests/JsonSerializerTests.cs
No functional changes, just organizing the JsonSerializer tests into a more lean structure.
> Single Theory+MemberData JsonSerializer.Tests

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [Exporter.Geneva] Release 1.4.0-rc.2

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes #.
Needed by OTel AutoInstrumentation.
> [Instrumentation.Runtime] Release with OTel 1.4.0-rc.3

- src/OpenTelemetry.Instrumentation.Owin/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Owin/TracerProviderBuilderExtensions.cs
Propagate recommendations from https://github.com/open-telemetry/opentelemetry-dotnet/pull/3653/files#r970049254
Remove `AddOwinInstrumentation`  with default parameter
> [Instrumentation.Owin] Remove AddOwinInstrumentation with default parameter

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/ElasticsearchClientInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.ElasticsearchClient/Implementation/ElasticsearchRequestPipelineDiagnosticListener.cs
Fix/suppress code analysis warnings in OpenTelemetry.Instrumentation.ElasticsearchClient.
> [Instrumentation.ElasticsearchClient] Fix analysis warnings

- src/OpenTelemetry.Instrumentation.Wcf/TelemetryClientMessageInspector.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryContractBehaviorAttribute.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryDispatchMessageInspector.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryEndpointBehavior.cs
- src/OpenTelemetry.Instrumentation.Wcf/TelemetryServiceBehavior.cs
Fix/suppress code analysis warnings in OpenTelemetry.Instrumentation.Wcf.
> [Instrumentation.Wcf] Fix analysis warnings

- .github/PULL_REQUEST_TEMPLATE.md
> Update pr template to include api review check

- src/OpenTelemetry.Exporter.Instana/Implementation/InstanaSpanSerializer.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/ActivityProcessorBase.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/DefaultActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/ErrorActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/EventsActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Processors/TagsActivityProcessor.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/SpanSender.cs
- src/OpenTelemetry.Exporter.Instana/Implementation/Transport.cs
- src/OpenTelemetry.Exporter.Instana/InstanaExporter.cs
- src/OpenTelemetry.Exporter.Instana/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaExporterTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanFactoryTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanSerializerTests.cs
Fix/suppress code analysis warnings in OpenTelemetry.Contrib.Exporter.Instana.
> [Exporter.Instana] Fix analysis warnings

- .github/component_owners.yml
- .github/workflows/package-ResourceDetectors.Azure.yml
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.ResourceDetectors.Azure/.publicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/OpenTelemetry.ResourceDetectors.Azure.csproj
- src/OpenTelemetry.ResourceDetectors.Azure/README.md
> Add new project  `OpenTelemetry.ResourceDetectors.Azure`

- src/OpenTelemetry.Extensions.Docker/Resources/DockerResourceDetector.cs
- test/OpenTelemetry.Extensions.Docker.Tests/Resources/DockerResourceDetectorTests.cs
Fix/suppress code analysis warnings in OpenTelemetry.Contrib.Extensions.Docker.
> [Extensions.Docker] Fix analysis warnings

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
Fixes N/A
Release request
[Instrumentation.Process, Instrumentation.Runtime] Release wtih OTel 1.4.0-rc.4
> [Instrumentation.Process, Instrumentation.Runtime] Release wtih OTel 1.4.0-rc.4

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> Update changelog for Exporter.Geneva release

- CONTRIBUTING.md
- examples/wcf/README.md
- src/OpenTelemetry.Exporter.Geneva/README.md
- src/OpenTelemetry.Extensions.AzureMonitor/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/README.md
- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.MySqlData/README.md
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md
Use note style
https://github.com/community/community/discussions/16925
and some nits related to note.
> [docs] Update "note" styling

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
> [OneCollector] CHANGELOG update for 0.1.0-alpha.1 release

- src/OpenTelemetry.Instrumentation.Process/README.md
> [Instrumentation.Process] Doc update: added opentelemetry spec link

- src/OpenTelemetry.Exporter.OneCollector/README.md
To address https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1003#issuecomment-1433651050
> [OneCollector] Added some text to README to explain the project

- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
Release Process instrumentation version 0.5.0
> [Instrumentation.Process] Release Process instrumentation version 0.5.0

- src/OpenTelemetry.Instrumentation.Process/README.md
> [Instrumentation.Process] fixed a typo

- src/OpenTelemetry.ResourceDetectors.Azure/AppServiceResourceDetector.cs
- test/OpenTelemetry.ResourceDetectors.Azure.Tests/AzureResourceDetectorTests.cs
> [Azure.ResourceDetectors] Add appservice service.instance.id

- .github/ISSUE_TEMPLATE/comp_resourcedetectors_azure.md
> Add issue template for ResourceDetectors.Azure

- src/OpenTelemetry.Exporter.Stackdriver/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Stackdriver/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ActivityExtensions.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/Constants.cs
- src/OpenTelemetry.Exporter.Stackdriver/StackdriverTraceExporter.cs
- src/OpenTelemetry.Exporter.Stackdriver/TracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Exporter.Stackdriver/Utils/CommonUtils.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/TestActivityProcessor.cs
Fix/suppress code analysis warnings in OpenTelemetry.Contrib.Exporter.Stackdriver.
> [Exporter.Stackdriver] Fix analysis warnings

- src/OpenTelemetry.Exporter.OneCollector/Internal/Serialization/CommonSchemaJsonSerializer.cs
* Update `Utf8JsonWriter` logic based on feedback from https://github.com/dotnet/runtime/issues/82314
> [OneCollector] Utf8JsonWriter logic tweak

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [GenevaExporter] Update CHANGELOG for 1.4.0 release

- src/OpenTelemetry.Extensions/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.MySqlData/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
Release for packages used by AutoInstrumentation.
Also fixes #1045.
> Releases based on OTel 1.4.0

- test/OpenTelemetry.Extensions.PersistentStorage.Tests/OpenTelemetry.Extensions.PersistentStorage.Tests.csproj
> [Extensions.PersistentStorage] Remove netcoreapp3.1 from tests

- test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests.csproj
Towards #1031 This component does not have an **owner**.
> [StackExchangeRedis] Remove netcoreapp3.1 from test

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
> [OneCollector] CHANGELOG update for 0.1.0-alpha.2 release

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
> Release OpenTelemetry.Instrumentation.ElasticsearchClient 1.0.0-beta.4

- src/OpenTelemetry.Contrib.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs
- src/OpenTelemetry.Contrib.Instrumentation.AWS/Implementation/Utils.cs
- src/OpenTelemetry.Contrib.Instrumentation.AWS/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/Tools/HttpResponseMessageBody.cs
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/Tools/MockHttpRequest.cs
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/Tools/MockWebResponse.cs
- test/OpenTelemetry.Contrib.Instrumentation.AWS.Tests/Tools/Utils.cs
Fix/suppress code analysis warnings in OpenTelemetry.Contrib.Extensions.AWS.
> [Extensions.AWS] Fix analysis warnings

- .github/ISSUE_TEMPLATE/comp_persistentstorage.abstractions.md
- .github/ISSUE_TEMPLATE/comp_persistentstorage_filesystem.md
Follow up #1079.
Labels already updated.
> [PersistentStorage] Fix issue templates

- src/OpenTelemetry.Instrumentation.AspNet/README.md
Towards https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2292
Changes based on https://github.com/open-telemetry/opentelemetry-dotnet/pull/4216/files
Document how to add metrics instrumentation for AspNet.
Document list of produced metrics for AspNet.
Replaces 51e0dbe54f71e952cdbb12f47a9df41bd9c9d645 which was pushed to the main branch by mistake.
Similar changes for AspNetCore under https://github.com/open-telemetry/opentelemetry-dotnet/pull/4321
> [Instrumentation.AspNet] Document metrics

- src/OpenTelemetry.Extensions.Docker/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.Extensions.Docker/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.Docker/.publicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Extensions.Docker/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Extensions.Docker/OpenTelemetry.Extensions.Docker.csproj
- src/OpenTelemetry.Extensions.Docker/Resources/DockerResourceDetector.cs
- test/OpenTelemetry.Extensions.Docker.Tests/OpenTelemetry.Extensions.Docker.Tests.csproj
Towards #894
Nullable for docker and tests.
> [Extensions.Docker] Nullable

- .github/component_owners.yml
Update codeowners for tests, same as for main project.
> [Extenstions.AzureMonitor] Codeowners for tests

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldTraceExporter.cs
- Fix a bug where incorrect key-value pair was being serialized special tags
> [Exporter.Geneva][TldTraceExporter] Fix serialization bug

- .github/ISSUE_TEMPLATE/comp_instrumentation_aspnet.md
- .github/ISSUE_TEMPLATE/comp_instrumentation_aspnet.telemetryhttpmodule.md
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1077#discussion_r1135210118
Issue Templates - lowercase labels
> Issue Templates - lowercase labels

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.5.0-alpha.2 version
> [Exporter.Geneva] Update CHANGELOG for 1.5.0-alpha.2 version

- src/OpenTelemetry.Instrumentation.Cassandra/CHANGELOG.md
> [Instrumentation.Cassandra] Release 1.0.0-beta.1

- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
[ResourceDetectors.Container] Release 1.0.0-beta.3
> [ResourceDetectors.Container] Release 1.0.0-beta.3

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
I'd also like to suggest the following general principles:
1. All versions of the releases (NuGet packages) must have corresponding entries in the main branch changelog.
2. Changelog should follow chronological order.
> [Exporter.Geneva] Fix changelog

- src/OpenTelemetry.PersistentStorage.Abstractions/OpenTelemetry.PersistentStorage.Abstractions.csproj
- src/OpenTelemetry.PersistentStorage.FileSystem/OpenTelemetry.PersistentStorage.FileSystem.csproj
Fixes release process for PersistentStorage.* projects
Sync tags between GH workflows and csprojs.
#1144 cannot be released without this changes.
> [PersistentStorage.*] Fix release tags in csproj

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.5.0-alpha.3 release
> [Exporter.Geneva] Update CHANGELOG for 1.5.0-alpha.3

- .github/component_owners.yml
- Update component owners for GenevaExporter
> [Exporter.Geneva] Update component owners

- src/OpenTelemetry.Exporter.Stackdriver/README.md
- src/OpenTelemetry.Instrumentation.Runtime/README.md
Fixes #1167.
Leftover from project rename.
> [Exporter.Stackdriver] Fix readme after project rename

- src/OpenTelemetry.Extensions.AzureMonitor/CHANGELOG.md
> [Extensions.AzureMonitor] Update changelog for release

- src/OpenTelemetry.Instrumentation.MySqlData/MySqlDataInstrumentationEventSource.cs
Fixes N/A.
[Instrumenation.MySqlData] Fix typos
> [Instrumenation.MySqlData] Fix typos

- .github/ISSUE_TEMPLATE/comp_exporter_influxdb.md
- .github/component_owners.yml
- .github/workflows/package-Exporter.InfluxDB.yml
- examples/InfluxDB/Examples.InfluxDB/Examples.InfluxDB.csproj
- examples/InfluxDB/Examples.InfluxDB/Program.cs
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- src/OpenTelemetry.Exporter.InfluxDB/IMetricsWriter.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBEventSource.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBExporterExtensions.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBMetricsExporter.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBMetricsExporterOptions.cs
- src/OpenTelemetry.Exporter.InfluxDB/MetricsSchema.cs
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
- src/OpenTelemetry.Exporter.InfluxDB/PointDataExtensions.cs
- src/OpenTelemetry.Exporter.InfluxDB/README.md
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV1.cs
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV2.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/InfluxDBMetricsExporterTests.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/OpenTelemetry.Exporter.InfluxDB.Tests.csproj
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/AssertUtils.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/InfluxDBFakeServer.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/InfluxDBMetricsExporterOptionsTestExtensions.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/LineProtocolParser.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/PointData.cs
Fixes #1172.
This is the initial implementation of InfluxDB Exporter. 
> Add InfluxDB exporter

- src/OpenTelemetry.Exporter.InfluxDB/MetricsSchema.cs
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
Fixes #1189.
Remove NoWarn exclusions from the cproj. 
> [OpenTelemetry.Exporter.InfluxDB] Get rid of the no-warn exclusions

- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- Update CHANGELOG for 1.0.0-alpha.1 release
> [Exporter.InfluxDB] Update CHANGELOG for 1.0.0-alpha.1 release

- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- Update CHANGELOG after the initial release
> [Exporter.InfluxDB] Update CHANGELOG after the initial release

- test/OpenTelemetry.Exporter.InfluxDB.Tests/OpenTelemetry.Exporter.InfluxDB.Tests.csproj
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/InfluxDBFakeServer.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/Utils/LineProtocolParser.cs
* VS is complaining about the `OpenTelemetry.Exporter.InfluxDB.Tests` project having invalid targets.
> [influxdb] Fix issues with the test project

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.5.0-rc.1
> [Exporter.Geneva] Update CHANGELOG for 1.5.0-rc.1

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- Update CHANGELOG for 1.5.0 release
> [Instrumentation.Runtime] Update CHANGELOG for 1.5.0

- src/OpenTelemetry.Exporter.Geneva/External/TraceLoggingDynamic.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ConnectionStringBuilder.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantActivityExportProcessor.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantExportProcessor.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/UnixDomainSocketDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/UnixDomainSocketEndPoint.cs
- Mark internal classes sealed
> [Exporter.Geneva] Mark internal classes sealed

- .github/workflows/package-Instrumentation.AspNet.TelemetryHttpModule.yml
- .github/workflows/package-Instrumentation.AspNet.yml
- .github/workflows/package-Instrumentation.StackExchangeRedis.yml
Fixes #1230.
Release packages with tag containing -rc9. as prerelease.
Condition added only to affected packages.
> Release packages with tag containing -rc9. as prerelease

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [Exporter.Geneva] Update CHANGELOG for 1.5.0

- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/AWSLambdaWrapperTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/Implementation/AWSLambdaHttpUtilsTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/Implementation/AWSMessagingUtilsTests.cs
- test/OpenTelemetry.Instrumentation.AWSLambda.Tests/OpenTelemetry.Instrumentation.AWSLambda.Tests.csproj
Towards #1031
Instrumentation.AWSLambda - execute tests with supported versions of .NET.
> [Instrumentation.AWSLambda] Tests - Supported versions of .NET

- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
- Update CHANGELOG for 1.0.0-alpha.2 release
> [Exporter.InfluxDB] Update CHANGELOG for 1.0.0-alpha.2 release

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
Update CHANGELOG for 1.5.0-beta.1 release
Fixes #1250
> [Instrumentation.Hangfire] Update CHANGELOG for 1.5.0-beta.1 release

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [Exporter.Geneva] Update CHANGELOG for 1.5.1

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
- Update CHANGELOG for 1.5.1-rc.1
> [Exporter.OneCollector] Update CHANGELOG for 1.5.1-rc.1

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- Update CHANGELOG for 1.6.0-alpha.1
> [Exporter.Geneva] Update CHANGELOG for 1.6.0-alpha.1

- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/README.md
- update changelog
- update readme for VM detector.
> [ResourceDetectors.Azure] update changelog and readme

- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
> [ResourceDetectors.Azure] Add unreleased section

- src/OpenTelemetry.ResourceDetectors.Azure/README.md
Follow up: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1277#discussion_r1272943541
> [ResourceDetectors.Azure] update readme to use `ConfigureResource`

- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/OpenTelemetry.ResourceDetectors.Azure.csproj
> Downgrade `system.text.json` OpenTelemetry.ResourceDetectors.Azure

- src/OpenTelemetry.ResourceDetectors.Azure/README.md
Update the documentation for the Azure App Service and Azure Virtual Machine resource detectors by introducing a detailed "Description" column for each attribute in the respective tables. The purpose of these descriptions is to provide clearer insights into what each attribute signifies, thereby enabling users to better understand the functionality of these detectors and the nature of the data they produce.
> [OpenTelemetry.ResourceDetectors.Azure] Update Readme for Azure App Service and VM Resource Detector

- build/Common.nonprod.props
- build/Common.props
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldTraceExporter.cs
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- src/OpenTelemetry.Instrumentation.AWS/Implementation/SnsRequestContextHelper.cs
- src/OpenTelemetry.Instrumentation.AWS/Implementation/SqsRequestContextHelper.cs
- src/OpenTelemetry.ResourceDetectors.Azure/AzureVmMetadataResponse.cs
- src/OpenTelemetry.ResourceDetectors.Azure/ResourceAttributeConstants.cs
- src/OpenTelemetry.Sampler.AWS/RateLimiter.cs
- src/OpenTelemetry.Sampler.AWS/RateLimitingSampler.cs
- test/OpenTelemetry.Exporter.InfluxDB.Tests/InfluxDBMetricsExporterTests.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Implementation/TestsHelper.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/MockHttpRequest.cs
- test/OpenTelemetry.Instrumentation.AWS.Tests/Tools/MockHttpRequestFactory.cs
- test/OpenTelemetry.Instrumentation.MySqlData.Tests/MySqlDataTests.cs
- test/OpenTelemetry.ResourceDetectors.Azure.Tests/OpenTelemetry.ResourceDetectors.Azure.Tests.csproj
Fixes #.
Bump common dependencies.
Fix newly detected issues.
While reviewing consider to check each commit separately.
> Bump common dependencies

- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
Instrumentation.AWSLambda 1.2.0-beta.1 release
> Instrumentation.AWSLambda 1.2.0-beta.1 release

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
Instrumentation.AWS 1.1.0-beta.1 release.
> Instrumentation.AWS 1.1.0-beta.1 release

- .github/workflows/package-Instrumentation.StackExchangeRedis.yml
- Fix typo introduced in #1301
> Fix StackExchangeRedis workflow

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
> [wcf] 1.0.0-rc.11 release

- src/OpenTelemetry.ResourceDetectors.Azure/AzureVMResourceDetector.cs
Fixes #.
This change avoids calling the metadata service multiple times in case the resource detector is used for multiple signals(logs, metrics, traces). This is to done in order to reduce the start up time.
> Avoid multiple outgoing requests for AzureVMResourceDetector

- src/OpenTelemetry.PersistentStorage.FileSystem/DirectorySizeTracker.cs
See https://github.com/open-telemetry/opentelemetry-dotnet/pull/4793#discussion_r1300623594
Fixes #.
> [persistent storage] IsSpaceAvailable doc follow-up

- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/net6.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/net6.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Exporter.InfluxDB/IMetricsWriter.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBExporterExtensions.cs
- src/OpenTelemetry.Exporter.InfluxDB/InfluxDBMetricsExporterOptions.cs
- src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
- src/OpenTelemetry.Exporter.InfluxDB/PointDataExtensions.cs
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV1.cs
- src/OpenTelemetry.Exporter.InfluxDB/TelegrafPrometheusWriterV2.cs
> OpenTelemetry.Exporter.InfluxDB nullable support

- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.PersistentStorage.FileSystem/OpenTelemetry.PersistentStorage.FileSystem.csproj
- Update `OpenTelemetry.PersistentStorage.Abstractions` package version
- Other minor changes to the `.sln` file
> [PersistentStorage.FileSystem] Update PersistentStorage FileSystem csproj

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
Changelog update for 1.0.0-rc.12 release.
> [wcf]1.0.0-rc.12 release

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/AspNetTelemetryEventSource.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModule.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModuleOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/.publicApi/net462/PublicAPI.Shipped.txt
- src/OpenTelemetry.Instrumentation.AspNet/.publicApi/net462/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/OpenTelemetry.Instrumentation.AspNet.csproj
- src/OpenTelemetry.Instrumentation.AspNet/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Contrib.Tests.Shared/EventSourceTestHelper.cs
- test/OpenTelemetry.Contrib.Tests.Shared/InMemoryEventListener.cs
- test/OpenTelemetry.Contrib.Tests.Shared/TestEventListener.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/ActivityHelperTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/HttpContextHelper.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests.csproj
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/WebConfigTransformTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.Tests/WebConfigWithLocationTagTransformTest.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/BasicTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/OpenTelemetry.Instrumentation.AspNet.Tests.csproj
> Nullable for ASP.NET instrumentation projects

- examples/AspNet/Controllers/WeatherForecastController.cs
- examples/AspNet/Examples.AspNet.csproj
- examples/AspNet/Global.asax.cs
- examples/AspNet/Models/WeatherForecast.cs
- examples/AspNet/SuppressInstrumentationHttpModule.cs
Towards #894
Nullable Examples.AspNet
> Nullable Examples.AspNet

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/OpenTelemetry.Instrumentation.ElasticsearchClient.csproj
- test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests.csproj
[Instrumentation.ElasticsearchClient] Execute tests on .NET Fx 4.6.2
> [Instrumentation.ElasticsearchClient] Execute tests on .NET Fx 4.6.2

- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
> [ResourceDetectors.Azure] Update CHANGELOG.md - Request for release

- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/OpenTelemetry.Instrumentation.EventCounters.Tests.csproj
Towards #894.
Nullable OpenTelemetry.Instrumentation.EventCounters.Tests~
Skipped tests executed locally. All passed.
> Nullable OpenTelemetry.Instrumentation.EventCounters.Tests

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [geneva] CHANGELOG update for GenevaExporter 1.7.0-alpha.1 release

- .github/codecov.yml
- .github/workflows/Component.BuildTest.yml
- .github/workflows/ci-Exporter.Geneva.yml
- .github/workflows/ci-Exporter.OneCollector-Integration.yml
- .github/workflows/ci-Exporter.OneCollector.yml
- .github/workflows/ci-Instrumentation.Owin.yml
- .github/workflows/ci-Instrumentation.Process.yml
- .github/workflows/ci-Instrumentation.Wcf.yml
- .github/workflows/ci.yml
- .github/workflows/package-Instrumentation.Owin.yml
- build/Projects/OpenTelemetry.Instrumentation.Owin.proj
- opentelemetry-dotnet-contrib.sln
* Adds dedicated CI for the OpenTelemetry.Instrumentation.Owin project.
> [repo] Add dedicated CI for Owin Instrumentation

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
> [onecollector] Update CHANGELOG for 1.6.0-rc.1 release

- .github/workflows/Component.Package.yml
> [repo] Fix a bug in the package workflow causing github release tagging issues

- src/OpenTelemetry.Exporter.InfluxDB/CHANGELOG.md
* Update CHANGELOG for 1.0.0-alpha.3 release
> [Exporter.InfluxDB] Update CHANGELOG for 1.0.0-alpha.3 release

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldTraceExporter.cs
- Fix serialization bug when there are no Part C fields
> [Exporter.Geneva][TLD] Fix serialization bug when there are no Part C fields

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/package-Extensions.yml
- build/Projects/OpenTelemetry.Extensions.proj
- opentelemetry-dotnet-contrib.sln
- src/OpenTelemetry.Extensions/OpenTelemetry.Extensions.csproj
- test/OpenTelemetry.Extensions.Tests/OpenTelemetry.Extensions.Tests.csproj
> [repo] Add dedicated CI for OpenTelemetry.Extensions

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/package-Instrumentation.EventCounters.yml
- .github/workflows/package-Instrumentation.Runtime.yml
- .github/workflows/verifyaotcompat.yml
- build/Projects/OpenTelemetry.Instrumentation.EventCounters.proj
- build/Projects/OpenTelemetry.Instrumentation.Runtime.proj
- opentelemetry-dotnet-contrib.sln
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/OpenTelemetry.Instrumentation.EventCounters.Tests.csproj
> [repo] Add dedicated CI for EventCounters and Runtime instrumentation projects

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/package-ResourceDetectors.Azure.yml
- build/Projects/OpenTelemetry.ResourceDetectors.Azure.proj
- opentelemetry-dotnet-contrib.sln
> [repo] Add dedicated CI for the OpenTelemetry.ResourceDetectors.Azure project

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/CHANGELOG.md
Please release the v1.0.0-beta.5
> Release OpenTelemetry.Instrumentation.ElasticsearchClient v1.0.0-beta.5

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
CHANGELOG update for 1.6.0 release
> [OneCollector] 1.6.0 release

- src/OpenTelemetry.Instrumentation.ElasticsearchClient/README.md
https://github.com/elastic/elasticsearch-net/pull/7931
Fixes #.
> Update Elastic.Clients.Elasticsearch ActivitySource name

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- Update CHANGELOG for 1.0.0-rc9.11
> [Instrumentation.StackExchangeRedis] Update CHANGELOG for 1.0.0-rc9.11

- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- Update CHANGELOG for 1.0.0-rc9.12
> [Instrumentation.StackExchangeRedis] Update CHANGELOG for 1.0.0-rc9.12

- test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj
> [aot] Added a note in aot test app to also update ci when being modified

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- Update CHANGELOG for AspNet and AspoNet.TelemetryHttpModule instrumentation
> [Instrumentation.AspNet] Update CHANGELOG for 1.6.0-beta.2 release

- README.md
Document changes from last SIG meeting.
Good luck @martinjt! 
You probably need this: 🧹 :)
> Martin Thwaites - triager

- src/OpenTelemetry.ResourceDetectors.ProcessRuntime/CHANGELOG.md
[ResourceDetectors.ProcessRuntime] Release 0.1.0-alpha.1
> [ResourceDetectors.ProcessRuntime] Release 0.1.0-alpha.1

- src/OpenTelemetry.ResourceDetectors.ProcessRuntime/README.md
> [ResourceDetector.ProcessRuntime] - fix shields.io image

- src/OpenTelemetry.Instrumentation.Hangfire/.publicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/Implementation/HangfireInstrumentation.cs
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
- src/OpenTelemetry.Instrumentation.Hangfire/README.md
- src/OpenTelemetry.Instrumentation.Hangfire/TracerProviderBuilderExtensions.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/DependencyInjectionConfigTests.cs
- test/OpenTelemetry.Instrumentation.Hangfire.Tests/OpenTelemetry.Instrumentation.Hangfire.Tests.csproj
> [Instrumenation.Hangfire] Add options support to hangfire instrumentation

- examples/AspNet/Controllers/WeatherForecastController.cs
- test/OpenTelemetry.Contrib.Tests.Shared/TestTextMapPropagator.cs
Fixes full local builds (with VS2023 17.8.3).
Fixes leftovers from migration to .NET8 and Moq removal.
> Local build fixes

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [Exporter.Geneva] Update CHANGELOG for 1.7.0

- README.md
@vishweshbankwar has been instrumental in getting the instrumentation libraries in the core repo towards stability. We have many instrumentations in the contrib repo too which can benefit from his experience in the main repo.
Fixes #.
> Add Vishwesh as maintainer

- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldTraceExporter.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/GenevaTraceExporterTests.cs
- Use HashSet instead of Dictionary to avoid unnecessary allocation of "true" strings
> [Exporter.Geneva] Use HashSet instead of Dictionary

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
> Release OpenTelemetry.Instrumentation.Hangfire 1.6.0-beta.1

- src/OpenTelemetry.Instrumentation.Hangfire/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
Fixes #.
Revert the downgrade done in #1502.
> Hangfire - Upgrade OTel to 1.7.0

- src/OpenTelemetry.ResourceDetectors.Host/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Process/CHANGELOG.md
Changelog update for host and process detectors 0.1.0-alpha.1 release.
> [detectors] host and process detectors 0.1.0-alpha.1 release

- examples/wcf/README.md
- src/OpenTelemetry.Exporter.Geneva/README.md
- src/OpenTelemetry.Extensions.Enrichment/README.md
- src/OpenTelemetry.Instrumentation.AWSLambda/README.md
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/README.md
- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.MassTransit/README.md
- src/OpenTelemetry.Instrumentation.MySqlData/README.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/README.md
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md
Use new md syntax for Notes.
Ref: https://github.com/orgs/community/discussions/16925
> Documentation - use new markdown syntax for Notes

- src/OpenTelemetry.Exporter.Geneva/README.md
> Minor docs fix

- src/OpenTelemetry.ResourceDetectors.Azure/README.md
Fixes this markdown lint warning: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1552#issuecomment-1915161824
> Fix markdown lint warning

- src/OpenTelemetry.Exporter.Geneva/README.md
> [geneva] Add guidance for configuring options using services retrieved from DI

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/OpenTelemetry.Instrumentation.Wcf.csproj
https://github.com/advisories/GHSA-vh55-786g-wjwj
> [wcf] Security fix: GHSA-vh55-786g-wjwj

- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/README.md
Fixes #.
* Update Readme for ACA 
* ChangeLog for 1.0.0-beta.5 release
> [AzureResourceDetector] Update Readme for ACA and ChangeLog for 1.0.0-beta.5 release

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
Fixes N/A
Release AspNet, EFCore instrumentation and Container Resource detector
Used by AutoInstrumentation. Release all packages with any changes in changelog.
> Release AspNet, EFCore instrumentation and Container Resource detector

- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
Fixes #.
I missed it while creating #1573
[Instrumentation.Wcf] Release 1.0.0-rc.15
> [Instrumentation.Wcf] Release 1.0.0-rc.15

- src/OpenTelemetry.ResourceDetectors.AWS/AWSResourcesEventSource.cs
- src/OpenTelemetry.ResourceDetectors.AWS/Http/ServerCertificateValidationProvider.cs
Fixes event source to write to the intended event as well as adjusted a couple of the log messages as to not repeat "Failed to validate certifacate".
> Minor adjustment to the AWS event source

- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1559#issuecomment-1932666176
Improve changelog
> [Instrumentation.EntityFrameworkCore] Improve changelog

- src/Shared/SpanHelper.cs
Fixes open-telemetry/opentelemetry-dotnet-contrib#1578.
> Align ResolveSpanStatusForHttpStatusCode implementation with main repo

- README.md
Fixes #1586 
Make it easier to find maintainers, approvers, component owners etc.
> Editorial fix to make it easy to find maintainers

- README.md
README - add link to triager requierments
> [doc] add link to triager requierments

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
[Instrumentation.Owin] Release 1.0.0-rc.4
* ~[ ] Design discussion issue #~
* ~[ ] Changes in public API reviewed~
> [Instrumentation.Owin] Release 1.0.0-rc.4

- opentelemetry-dotnet-contrib.sln
Cleanup solution file - shared folder
> Cleanup solution file - shared folder

- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
Towards #1585
Added support for double counter types.
> [Exporter.Geneva] [otlp format] Add double counter support

- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
Fixes #.
Added tests for updown counter scenarios.
> [Exporter.Geneva][otlp protobuf] Add test for updown counter

- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
Towards #1585
Adds support for exporting histogram instrument type.
> [Exporter.Geneva][otlp protobuf] Add histogram support

- test/OpenTelemetry.Exporter.Geneva.Benchmark/Exporter/MetricExporterBenchmarks.cs
Towards #1585 
Adding benchmarks for otlp format.
> Exporter.Geneva][otlp protobuf] Add benchmarks

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.EntityFrameworkCore/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Process/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Quartz/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.StackExchangeRedis/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.Wcf/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Azure/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Container/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Host/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.Process/CHANGELOG.md
- src/OpenTelemetry.ResourceDetectors.ProcessRuntime/CHANGELOG.md
Releases with OTel 1.8.0
needed by OpenTelemetry.AutoInstrumentation
> Releases with OTel 1.8.0

- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
Towards #1585 
Expanding the tests to cover different data types for attribute values.
> Exporter.Geneva][OTLP protobuf] Add tests for different data types

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
Requesting to release OpenTelemetry.Instrumentation.AWS. I would like to test the changes made in #1572 on a AWS .NET SDK project I am working on.
> Request to release OpenTelemetry.Instrumentation.AWS package

- README.md
As I informed the other maintainers and approvers already, I would be spending my time more on helping with another OpenTelemetry SIG. Therefore, I wouldn't be spending much of my time in this repo.
> Move Utkarsh to Emeritus Maintainer

- src/OpenTelemetry.Exporter.Geneva/Internal/ExporterEventSource.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- test/OpenTelemetry.Exporter.Geneva.Tests/OtlpProtobufMetricExporterTests.cs
Towards #1585 
Adds logging for exceptions encountered during serialization of metric point.
> [Exporter.Geneva][Otlp protobuf] Add logging for serialization exception

- src/OpenTelemetry.Instrumentation.Owin/CHANGELOG.md
> [Instrumentation.OWIN] Release 1.0.0-rc.6

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ResourceExtensions.cs
- src/OpenTelemetry.Exporter.Stackdriver/Implementation/ResourceSemanticConventions.cs
- src/OpenTelemetry.Exporter.Stackdriver/StackdriverTraceExporter.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/ResourceExtensionsTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/StackdriverExporterTests.cs
- test/OpenTelemetry.Exporter.Stackdriver.Tests/TestTraceServiceClient.cs
> exports service.name to StackDriver if the value is present in an instance of OpenTelemetry.Resources.Resource

- src/OpenTelemetry.Exporter.Stackdriver/CHANGELOG.md
> [Exporter.Stackdriver] Release 1.0.0-beta.6

- src/OpenTelemetry.Exporter.OneCollector/CHANGELOG.md
> [onecollector] Update CHANGELOG for 1.8.0 release

- examples/AspNet/Examples.AspNet.csproj
- examples/AspNet/Views/Web.config
- examples/AspNet/Web.config
Fixes: local build warnings while working with VS.
[Examples.AspNet] Update dependencies to fix local build warnings while working with VS.
> [Examples.AspNet] Update dependencies

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
Fixes #.
Release prep for 1.8.0-rc.2
> [Exporter.Geneva] Prepare release 1.8.0-rc.2

- src/OpenTelemetry.Instrumentation.Runtime/CHANGELOG.md
> [Instrumentation.Runtime] Prepare release 1.8.1

- .github/component_owners.yml
- (temporarily) remove atshaw43.
- add ppittle to additional aws project.
Fixes #1715
> Update component_owners.yml for aws projects

- opentelemetry-dotnet-contrib.sln
[repo] Fix Solution file (Resources.ProcessRuntime projects)
> [repo] Fix Solution file (Resources.ProcessRuntime projects)

- .github/workflows/ci.yml
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInMetricsListenerTests.cs
See https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1824#issuecomment-2123300785
* Fix AspNet rules so CI runs for AspNet changes
* Fix unit tests broken by #1824
> [aspnet] Fix AspNet rules in CI and issues introduced on latest PR

- src/OpenTelemetry.Instrumentation.AspNet/CHANGELOG.md
Related to #1696
With this release, implementation of #1696 will be easier on Auto Instrumentation side.
> [Instrumentation.AspNet] Release 1.8.0-beta.3

- src/OpenTelemetry.Instrumentation.AspNet/README.md
- src/OpenTelemetry.Instrumentation.AspNetCore/README.md
> [Instrumentation.AspNet, Instrumentation.AspNetCore] EnrichWithException - improve example

- src/OpenTelemetry.Resources.Gcp/CHANGELOG.md
> [Resources.GCP] Changelog - typo fix

- build/scripts/post-release.psm1
* Fix automation creating releases without changelog content
> [repo] Fix automation creating releases without changelog content

- src/OpenTelemetry.Sampler.AWS/README.md
Include `--prerelease` in package installing process. There is no stable package yet.
> [Sampler.AWS] Update documentation to install package

- .github/PULL_REQUEST_TEMPLATE.md
This PR aligns the PR template with main repo.
> [repo] Align PR template with main repo

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/component_owners.yml
Fixes yamlint issues.
* ~~[ ] Appropriate `CHANGELOG.md` fles updated for non-trivial changes~~
> Fix yamlint

- src/OpenTelemetry.Resources.AWS/AWSResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.AWS/README.md
- src/OpenTelemetry.Resources.Azure/AzureResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.Azure/README.md
- src/OpenTelemetry.Resources.Container/ContainerResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.Container/README.md
- src/OpenTelemetry.Resources.Gcp/GcpResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.Gcp/README.md
- src/OpenTelemetry.Resources.Host/HostResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.Host/README.md
- src/OpenTelemetry.Resources.OperatingSystem/OperatingSystemResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.OperatingSystem/README.md
- src/OpenTelemetry.Resources.Process/ProcessResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.Process/README.md
- src/OpenTelemetry.Resources.ProcessRuntime/ProcessRuntimeResourceBuilderExtensions.cs
- src/OpenTelemetry.Resources.ProcessRuntime/README.md
Addresses https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1943#discussion_r1674273335.
Fixes: #1509
> [repo] Clarify resource detectors README

- src/OpenTelemetry.Resources.OperatingSystem/README.md
> [Resources.OperatingSystem] readme typo fix

- examples/kafka/Examples.ConfluentKafka.csproj
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaExporterTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanSerializerTests.cs
- test/OpenTelemetry.Exporter.Instana.Tests/InstanaSpanTest.cs
- test/OpenTelemetry.Exporter.Instana.Tests/OpenTelemetry.Exporter.Instana.Tests.csproj
- test/OpenTelemetry.Exporter.Instana.Tests/TestActivityProcessor.cs
- test/OpenTelemetry.Exporter.Instana.Tests/TestSpanSender.cs
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/HostedTracingAndMeteringTests.cs
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/KafkaHelpers.cs
- test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/OpenTelemetry.Instrumentation.ConfluentKafka.Tests.csproj
Towards #894
[Tests] Nullable - Instrumentation.ConfluentKafka and Exporter.Instana
> [Tests] Nullable - Instrumentation.ConfluentKafka and Exporter.Instana

- src/OpenTelemetry.Exporter.Geneva/CHANGELOG.md
> [Exporter.Geneva] Edit 1.9.0 changelog to clarify exemplars support

- src/OpenTelemetry.Extensions/CHANGELOG.md
Fixes #
Adding changelog for https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1996
> Add changelog for rate limiting sampler

- src/OpenTelemetry.Instrumentation.Http/CHANGELOG.md
> Fix OpenTelemetry.Instrumentation.Http 1.9.0 release notes

- src/OpenTelemetry.Exporter.Geneva/GenevaExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/GenevaTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ConnectionStringBuilder.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/ReentrantExportProcessor.cs
- src/OpenTelemetry.Exporter.Geneva/Internal/TableNameSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/GenevaMetricExporterOptions.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/MetricSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/OtlpProtobufSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/OtlpProtobuf/ProtobufSerializerHelper.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/TlvMetricExporter.cs
- src/OpenTelemetry.Exporter.Geneva/Metrics/Transport/MetricEtwDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MessagePackSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/MsgPackTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/EtwDataTransport.cs
- src/OpenTelemetry.Exporter.Geneva/MsgPackExporter/Transport/UnixDomainSocketEndPoint.cs
- src/OpenTelemetry.Exporter.Geneva/OpenTelemetry.Exporter.Geneva.csproj
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/JsonSerializer.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldLogExporter.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/TldTraceExporter.cs
- src/OpenTelemetry.Exporter.Geneva/TLDExporter/UncheckedASCIIEncoding.cs
* Removes the suppression of a bunch of StyleCop warnings and updates the code to be compliant with the repo standards.
> [geneva] Update code to follow more of the repo style conventions

- .github/workflows/ci.yml
> [repo] Fix InfluxDB pipeline definition

- README.md
[docs] README - Fix links to membership descriptions
> [docs] README - Fix links to membership descriptions

- src/OpenTelemetry.Exporter.OneCollector/OpenTelemetry.Exporter.OneCollector.csproj
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2118#discussion_r1782129093
[onecollector] remove Author tag
it is inherited from props files
I do not found any other places with this.
> [onecollector] remove Author tag

- build/scripts/post-release.psm1
- test/OpenTelemetry.Instrumentation.AspNet.Tests/HttpInListenerTests.cs
> Typofixes - diable ->disable

- src/OpenTelemetry.Instrumentation.Cassandra/README.md
Handles https://docs.datastax.com/en/developer/csharp-driver/3.22/features/opentelemetry/index.html
[Instrumentation.Cassandra] Document how to enable tracing
> [Instrumentation.Cassandra] Document how to enable tracing

- src/OpenTelemetry.Resources.AWS/AWSECSDetector.cs
- src/OpenTelemetry.Resources.AWS/AWSEKSDetector.cs
- src/OpenTelemetry.Resources.AWS/AsyncHelper.cs
- src/OpenTelemetry.Resources.Azure/AppServiceResourceDetector.cs
- src/OpenTelemetry.Resources.Azure/AzureContainerAppsResourceDetector.cs
- src/OpenTelemetry.Resources.Azure/AzureVMResourceDetector.cs
- src/OpenTelemetry.Resources.Azure/AzureVmMetadataResponse.cs
- src/OpenTelemetry.Resources.Container/ContainerDetector.cs
- src/OpenTelemetry.Resources.Container/Utils/EncodingUtils.cs
- src/OpenTelemetry.Resources.Gcp/GcpResourceDetector.cs
- src/OpenTelemetry.Resources.Host/HostDetector.cs
- src/OpenTelemetry.Resources.OperatingSystem/OperatingSystemDetector.cs
- src/OpenTelemetry.Resources.ProcessRuntime/ProcessRuntimeDetector.cs
- src/Shared/ServerCertificateValidationProvider.cs
- test/OpenTelemetry.PersistentStorage.FileSystem.Tests/FileBlobTests.cs
- test/OpenTelemetry.Resources.AWS.Tests/AsyncHelperTests.cs
- test/OpenTelemetry.Resources.Container.Tests/ContainerDetectorTests.cs
- test/OpenTelemetry.Resources.Host.Tests/HostDetectorTests.cs
> [repo/Resources] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.Owin/Implementation/DiagnosticsMiddleware.cs
- test/OpenTelemetry.Instrumentation.Owin.Tests/DiagnosticsMiddlewareTests.cs
> [repo/OWIN] Prepare to .NET9

- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersInstrumentationOptions.cs
- src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs
- test/OpenTelemetry.Instrumentation.EventCounters.Tests/EventCountersMetricsTests.cs
> [repo/EventCounters] Prepare to .NET9

- .gitignore
Same as https://github.com/open-telemetry/opentelemetry-dotnet/pull/3587
> [infra] Update .gitignore to ignore config files for Visual Studio Live Unit Testing

- .github/component_owners.yml
- src/OpenTelemetry.Exporter.Geneva/README.md
- Removing myself from the list of GenevaExporter component owners
> [repo] Update GenevaExporter component owners

- src/OpenTelemetry.Instrumentation.AWSLambda/README.md
List OpenTelemetry.Instrumentation.AWSLambda as Stable in the README.md
> List OpenTelemetry.Instrumentation.AWSLambda as Stable 

- .github/component_owners.yml
- src/OpenTelemetry.Exporter.Geneva/README.md
Adding Mothra and myself as the component owners of GenevaExporter.
> Add TimothyMothra and xiang17 to GenevaExporter codeowner

- .github/workflows/Component.BuildTest.yml
codecov/codecov-action@v5 renamed `file` to `files`.
> [repo] CodeCove - Fix workflow warning

- src/OpenTelemetry.Instrumentation.Http/README.md
Fixes - slack request
[Instrumentation.Http] Fix stability in readme
> [Instrumentation.Http] Fix stability in readme

- src/OpenTelemetry.SemanticConventions/OpenTelemetry.SemanticConventions.csproj
[SemanticConventions] Make project packable
> [SemanticConventions] Make project packable

- src/OpenTelemetry.PersistentStorage.FileSystem/FileBlobProvider.cs
Needed for https://github.com/open-telemetry/opentelemetry-dotnet/issues/3958
Fixes when compiled with BUILDING_INTERNAL_PERSISTENT_STORAGE
> [PersistentStorage.FileSystem] fix compilation issues for main repo

- src/OpenTelemetry.Instrumentation.AWS/CHANGELOG.md
- src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md
- src/OpenTelemetry.Resources.AWS/CHANGELOG.md
> [docs] typo fixes

- .github/component_owners.yml
- README.md
- src/OpenTelemetry.Exporter.Geneva/README.md
- src/OpenTelemetry.Exporter.OneCollector/README.md
- src/OpenTelemetry.Instrumentation.Runtime/README.md
- src/OpenTelemetry.PersistentStorage.Abstractions/README.md
- src/OpenTelemetry.PersistentStorage.FileSystem/README.md
- src/OpenTelemetry.Resources.Azure/README.md
> Remove Mothra from codeowners and update affiliation

- .github/workflows/ci.yml
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2881#issuecomment-3056455500
Follow up to #2883 
Changes looks good on my fork. *.yml changes --- all steps executed on main, Owin file - only one OWIN executed.
> [infra] Checkout code on main to detect changes

- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/ActivityHelper.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/AspNetTelemetryEventSource.cs
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule.csproj
- src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule/TelemetryHttpModule.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentationMeterProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNet/AspNetInstrumentationTracerProviderBuilderExtensions.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpInListener.cs
- src/OpenTelemetry.Instrumentation.AspNet/Implementation/HttpRequestRouteHelper.cs
- src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreTraceInstrumentationOptions.cs
- src/Shared/Options/DelegatingOptionsFactoryServiceCollectionExtensions.cs
- test/Shared/TestTextMapPropagator.cs
Found during checking status for ##2909
[Instrumentation.AspNet] Code cleanup
> [Instrumentation.AspNet] Code cleanup

- .github/workflows/assign-reviewers.yml
Do not assign reviewers to draft pull requests.
> [Infra] Ignore drafts from PR review assignment

- src/OpenTelemetry.Instrumentation.SqlClient/README.md
Add missing space between words.
> [SqlClient] Fix spacing

- src/OpenTelemetry.OpAmp.Client/Internal/FrameBuilder.cs
- src/OpenTelemetry.OpAmp.Client/Internal/FrameDispatcher.cs
- src/OpenTelemetry.OpAmp.Client/Internal/IFrameBuilder.cs
- src/OpenTelemetry.OpAmp.Client/Internal/OpAmpClientEventSource.cs
- src/OpenTelemetry.OpAmp.Client/OpAmpClient.cs
- test/OpenTelemetry.OpAmp.Client.Tests/DataGenerators/FrameBuilderTestData.cs
* Adds agent disconnect message
> [OpAMP.Client] Add disconnect frame

- .github/workflows/automation.yml
- .github/workflows/prepare-release.yml
- build/scripts/prepare-release.psm1
Fixes https://github.com/open-telemetry/opentelemetry-dotnet-contrib/actions/runs/17818290023/job/50655678886
```log
2025-09-18T04:45:44.7804821Z 68cabcc8bb38e06ef65a7ddb6d4a18f5d0d9a7c4
2025-09-18T04:45:44.7957144Z ##[group]Run Import-Module .\build\scripts\prepare-release.psm1
2025-09-18T04:45:44.7957870Z [36;1mImport-Module .\build\scripts\prepare-release.psm1[0m
2025-09-18T04:45:44.7958364Z [36;1m[0m
2025-09-18T04:45:44.7958824Z [36;1mUpdateChangelogReleaseDatesAndPostNoticeOnPullRequest `[0m
2025-09-18T04:45:44.7959621Z [36;1m  -gitRepository ${env:GITHUB_REPOSITORY} `[0m
2025-09-18T04:45:44.7960175Z [36;1m  -pullRequestNumber ${env:ISSUE_NUMBER} `[0m
2025-09-18T04:45:44.7960638Z [36;1m  -botUserName ${env:BOT_USER_NAME} `[0m
2025-09-18T04:45:44.7961109Z [36;1m …
```
> [infra] Fix release process

- .github/workflows/prepare-release.yml
Follow up: #3128
PRs/comments are created by the application not the otelbot accoutn.
> [infra] Fix release process part 2

- build/scripts/post-release.psm1
Mirror fix from https://github.com/open-telemetry/opentelemetry-dotnet/pull/6549
> [infra] Fix post release steps related to artifacts output
